- usr/etc/mlnx/msn2100
- usr/etc/mlnx/msn2410
- usr/etc/mlnx/msn2420
- usr/etc/mlnx/msn2700
> Move shebang to the first line

- usr/etc/mlnx/msn2700
Add sequnce for i2c_dev in order to create /dev/i2c-xxx devices.
Signed-off-by: Vadim Pasternak <vadimp@mellanox.com>
> msn2700 init script - add module probing/removing records for i2c_dev

- mlnx-asic-drv.c
Reviewed-by: Vadim Pasternak <vadimp@mellanox.com>
> Added support for bind/unbind sx_core

- usr/etc/hw-management-sensors/msn3700_sensors.conf
- usr/etc/hw-management-sensors/msn3800_sensors.conf
Set delta 1100 vout limits in lm-sensors config,
to override bad values from PSUs.
> hw-mgmt: attributes: set delta 1100 limits

- usr/usr/bin/hw-management-thermal-control.sh
Sometimes two systems with the same thermal measurement could be
inconsistently set with different cooling device speed.
It might happen at initialization time in case ASIC temperature is
above “normal” threshold. There is fan speed enforcement mechanism
in hw-management package which should move fan from full speed
(initial state) to fan dynamic minimum speed. This move is performed
in case all thermal zones for ASIC and transceivers temperatures are
below “normal” thresholds. In this case if, for example at initial
state ASIC temperature is 75C (>= normal threshold, which is is 75C),
fan will stay at full speed. And while temperature is below or equal
"normal" threshold, thermal control will not touch cooling device.
For example one system at initial state was above "normal" threshold, …
> hw-mgmt: thermal: Fix cooling device enforcement criteria

- usr/usr/bin/hw-management-thermal-events.sh
Fix gearbox thermal zone name, which was lack suffix thermal zone number.
> hw-mgmt: thermal: Fix attribute name for critical temperature

- recipes-kernel/linux/linux-4.19/0087-Fix-cpld-_pn-reading.patch
- recipes-kernel/linux/linux-4.19/0087-platform-mellanox-mlxreg-io-Fix-read-access-of-attri.patch
- recipes-kernel/linux/linux-4.9/0073-Fix-cpld-_pn-reading.patch
- recipes-kernel/linux/linux-4.9/0073-platform-mellanox-mlxreg-io-Fix-read-access-of-attri.patch
Fix shift argument for function rol32(). It should be provided in bits,
while was provided in bytes.
Fixes: 86148190a7db: (" platform/mellanox: mlxreg-io: Add support for complex attributes")
> hw-mgmt: kernel patches: 4.9,4.19 platform/mellanox: mlxreg-io: Fix read access of attributes of n-bytes size

- usr/usr/bin/hw-management-thermal-events.sh
Fix PSU power sensor attributes capability crating. Add empty capability file crating
even if sensor haven't additional attributes.
> hw-mgmt: attributes: Fix PSU power sensor attributes capability

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-start-post.sh
Add CPLD_PORT version reading from SXD driver on old systems like MSN24xx
and MSN27xxx.
> hw-mgmt: attributes: Add cpld3 version reading from SXD driver

- usr/usr/bin/hw-management.sh
Change mqmxxx_msn37x_msn34x_specific psu fan max speed
from 23000 to 25000.
> hw-mgmt: system: mqmxxx_msn37x_msn34x_specific change psu fan max speed.

- usr/usr/bin/hw-management-thermal-events.sh
Expose PSU fan min/max speed from VPD. For PSUs without PMBUS VPD
psu fan speed limits taken from predefined per system config to VPD,
and then exposed in same way to hw-management/thermal/psu{n}_fan_max/min.
> hw-mgmt: attributes: expose PSU fan min/max speed.

- usr/usr/bin/hw-management.sh
> hw-mgmt: system: Change fru eeprom type to 24c512 for mqm9700 rev1 Change fru eeprom type 24c32->24c512 for mqm9700 rev1

- usr/usr/bin/hw-management-thermal-events.sh
If minimal speed read from VPD equal 0 set psu fan minimal speed
to 20% of maximum.
> hw-mgmt: attributes: fix psu fan minimal speed.

- usr/usr/bin/hw-management-thermal-events.sh
Set default fan speed value from config, it will be overwritten
from vpd if vpd read successfully.
> hw-mgmt: attributes: set default psu fan speed value.

- usr/usr/bin/hw-management-thermal-events.sh
> Fix issue of removing all temperature sensors links not related to switch. Delete just gearbox and module temperature links.

- usr/usr/bin/hw-management.sh
Add timeout before reading vpd with FAN dir config on systems with fixed FAN's.
> hw-mgmt: attributes: Fix fan_dir for systems with fixed FAN's

- recipes-kernel/linux/linux-4.19/0130-pinctrl-intel-Allow-to-request-locked-pads.patch
- recipes-kernel/linux/linux-4.19/0131-pinctrl-intel-Actually-disable-Tx-and-Rx-buffers-on-.patch
- recipes-kernel/linux/linux-4.19/0132-i2c-mlxcpld-check-correct-size-of-maximum-RECV_LEN-p.patch
Backport pacthes for CFL pin control.
Backport I2C upstream patch.
> hw-mgmt: patches: v4.19: Add new patches for pin control and I2C

- usr/etc/hw-management-sensors/msn4800_sensors.conf
Update sensors labels for PSU.
Update labels for mp2975 devices located at addresses 0x62, 0x64.
Package lm-sensors does not provide method to distinct between
devices with the same slave address, so it is not possible to
provide custom label names for these devices.
> hw-mgmt: sensors: Modify conf file for sensors

- usr/usr/bin/hw-management-thermal-events.sh
Fix calculation of HEX slave address for PSUs 3 and 4.
> hw-mgmt: events: Fix calculation for PSU EEPROM slave address

- usr/usr/bin/hw-management-thermal-events.sh
Add links for PSU sensors attributes like: minimum, maximum, critical minimum,
critical maximum. This attributes added to "{hw-management}/power" folder
for: voltage/current/power PSU sensors types.
Also added {sensor_name}_capability file with list of supporting attributes
separated by space.
> hw-mgmt: attributes: Add PSU power sensor attributes

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-generate-dump.sh
- usr/usr/bin/hw-management-start-post.sh
Fix cpld4 exposing on systems with 3 cpld
Add fan{x}_status existing check on fan_direction set
Set timeout for "journalctl" and "sx_sdk" on debug dump generation
> hw-mgmt: attributes: Fix cpld4 exposing on systems with 3 cpld

- usr/usr/bin/hw-management.sh
Add basic support for experimental mqm9700 power system type.
> hw-mgmt: topology: Extend support for mqm9700 system

- recipes-kernel/linux/linux-4.19/0092-platform-x86-mlx-platform-Extend-FAN-and-LED-config-.patch
- recipes-kernel/linux/linux-4.9/0066-platform-x86-mlx-platform-Extend-FAN-and-LED-config-.patch
- recipes-kernel/linux/linux-5.10/0065-platform-x86-mlx-platform-Extend-FAN-and-LED-config-.patch
Fix LED_FAN7 controll bits offset for system equipped with FAN7, like
"MQM97xx", which is based on Mellanox Quantum-2 ASIC. Changed controll bit from LSB
to MSB because LSB is using for Front_Fan_LED controll.
> hw-mgmt: kernel patches: 4.9,4.19,5.10: Fix LED_FAN7 register reading

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-4.19/0133-platform-x86-mlx-platform-Extend-FAN-platform-data-d.patch
- recipes-kernel/linux/linux-4.19/0134-hwmon-mlxreg-fan-Return-non-zero-value-when-fan-curr.patch
- recipes-kernel/linux/linux-4.19/0135-hwmon-mlxreg-fan-Extend-driver-to-support-multiply-P.patch
- recipes-kernel/linux/linux-4.19/0136-hwmon-mlxreg-fan-Extend-driver-to-support-multiply-c.patch
- recipes-kernel/linux/linux-4.19/0137-hwmon-mlxreg-fan-Fix-out-of-bounds-read-on-array-fan.patch
- recipes-kernel/linux/linux-4.19/0138-platform-x86-mlx-platform-Add-support-for-multiply-c.patch
Backport patches for virtual PWM support.
> hw-mgmt: pathes: 4.19: Support for multy PWM

- recipes-kernel/linux/linux-4.19/0064-platform-mellanox-mlxreg-io-Fix-read-access-of-n-byt.patch
Add missed line in patch
0064-platform-mellanox-mlxreg-io-Fix-read-access-of-n-byt.patch
=======================
Fix shift argument for function rol32(). It should be provided in bits,
while was provided in bytes.
Fixes: 86148190a7db: (" platform/mellanox: mlxreg-io: Add support for complex attributes")
========================
> kernel patches: 4.19: Add missed line in patch

- recipes-kernel/linux/linux-4.19/0126-mlxsw-minimal-Add-indexation-for-modules-on-for-line.patch
- recipes-kernel/linux/linux-4.19/0127-mlxsw-minimal-Obtain-maximum-number-of-slots-support.patch
- recipes-kernel/linux/linux-4.19/0128-mlxsw-minimal-Add-system-event-handler.patch
- recipes-kernel/linux/linux-4.19/0129-mlxsw-minimal-Add-interfaces-for-line-card-initializ.patch
Modify patch #0126 and rebase #0127 - #0129.
Signed-of-by: Vadim Pasternak <vadimp@nvidia.com>
> hw-mgmt: patches: v4.19: Rebase patches for minimal driver

- usr/usr/bin/hw-management-thermal-events.sh
Add symbolic links for cooling objects associated with pwm1, pwm2,
pwm3 attributes.
> hw-mgmt: events: Add symbolic links for cooling current states

- usr/usr/bin/hw-management-chassis-events.sh
Set a2d ID value in sensor name "/lc/environment/a2d_iio:device{ID}_*"
to start from 0 for each linecard.
> hw-mgmt: chassis events: Fix iio name index for linecard

- recipes-kernel/linux/linux-4.19/0140-hwmon-mlxreg-fan-Rename-cooling-devices.patch
- recipes-kernel/linux/linux-4.19/0141-mlxsw-core_thermal-Rename-cooling-devices.patch
Rename "mlxreg_fan" to "mlxreg_fan0".
Signed-of-by: Vadim Pasternak <vadimp@nvidia.com>
> hw-mgmt: patches: v4.19: Rename cooling device name

- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management.sh
- Use default thermal profile 60% instead of 100%.
- Use temporary WA for PSU fan speed - keep 100% until PS firmware
is not fixed.
> hw-mgmt: thermal: Use default dynamic minimum thermal profile for SN4800

- usr/usr/bin/hw-management-thermal-events.sh
Fix name for device "mlxreg_fan0".
Signed-of-by: Vadim Pasternak <vadimp@nvidia.com>
> hw-mgmt: events: Fix cooling device name

- usr/usr/bin/hw-management-start-post.sh
Fix cpld3 version reading on spc1 systems
> hw-mgmt: attributes: Fix cpld3 version reading on spc1 systems

- recipes-kernel/linux/linux-4.19/0154-platform-x86-mlx-platform-Add-support-for-new-system.patch
Add support for new system type XH3000, which is a water cooling
Ethernet switch blade equipped with 32x200G Ethernet ports.
The system is recognized by "DMI_BOARD_NAME" and "DMI_PRODUCT_SKU" matches,
when these fields are set to "VMOD0005" and "HI139" respectively.
> hw-mgmt: patches: v4.19: mlx-platform: Add support for new system XH3000

- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
Disabled ASIC operations for systems that do not support it. Affected SKU: HI132
> hw-mgmt: system: Disable ASIC oprations for systems that not supporting it

- usr/usr/bin/hw-management-chassis-events.sh
In some cases we can have duplicated of i2c bus/addr combination for several
different systems. In this case we will have duplication in udev rules and
several rules will be called twice. Second rule call of the same device can
overwrite already created links for voltmon. This fix add check for specific
combination of system type and voltmon address.
> hw-mgmt: chassis events: Add voltmon connection for specific system type

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: events: Add cleanup code for module and cables counters

- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management-thermal-events.sh
In some marginal cases ASIC temperature can grow up too fast.
Along with it at this time user space thermal loop could decrease fan
speed according to dynamic minimum value. If it happens at the
beginning of ASIC warming up trend, it can cause kernel's cooling
control algorithm stacking in dormant state, in which kernel will stop
fan cooling level increasing. It is extremely rare scenario, but it
worth to add protection against it.
> hw-mgmt: thermal: Add sanity check for ASIC temperature

- debian/changelog
- usr/usr/bin/hw-management-thermal-events.sh
> hw-mgmt: scripts: limit max_pwm=1 and max_tachos=4 on SN2201

- usr/lib/udev/rules.d/50-hw-management-events.rules
Add generic rule for netdevice. This rule is supposed to work
with kernel 5.10, becasue driver has support for devlink
callback, which activates newly added rule.
Old and new rules should not impact each other.
> hw-mgmt: rules: Add generic rule for netdevice renaming

- recipes-kernel/linux/linux-4.19/0134-hwmon-mlxreg-fan-Return-non-zero-value-when-fan-curr.patch
Patch #0134 is modifed due to following issue.
When current cooling level is set from user space to 10 + 'n' for
configuration purpose, due to return of non-zero value, this request
is retried by user space and it is resulted in the below flow:
cat /var/run/hw-management/thermal/cooling_cur_state
8
echo 16 > /var/run/hw-management/thermal/cooling_cur_state
cat /var/run/hw-management/thermal/cooling_cur_state
6
While 16 should just set limit and not change level from 8 to 6.
> hw-mgmt: kernel pacthes: 4.19: Modify patch #0134

- usr/usr/bin/hw-management-thermal-control.sh
Note: should be enabled again in next release after
chamber testing.
> hw-mgmt: thermal: Temporary disable thermal audit

- usr/usr/bin/hw_management_nvl_temperature_get.py
Add temperature reading script for NVL ASIC.
Example:
Reading chip_id 0 sensor 1
hw_management_nvl_temperature_get.py -n 0 -s 0
> hw-mgmt: Add temperature reading script for NVL ASIC

- recipes-kernel/linux/linux-5.10/0076-ethtool-Add-ability-to-control-transceiver-modules-p.patch
- recipes-kernel/linux/linux-5.10/0080-ethtool-Add-transceiver-module-extended-states.patch
Update patches #0076 and #0080 to match upstream.
> hw-mgmt: patches: 5.10: Align ethtool UAPI interface with upstream

- usr/lib/udev/rules.d/50-hw-management-events.rules
In order to avoid conflicts for ‘netdevice’ renaming, add validation of
port name attribute. Apply generic ‘udev’ rule only in case this
attribute is not empty.
> hw-mgmt: rules: Add validate of port name attribute

- usr/usr/bin/hw-management-thermal-events.sh
Intel CPU coretemp driver represents Denverton CPU cores as number 6 and 12
instead 0, 1. Make hw-mgmt links with usual core0, core1 names.
> hw-mgmt: scripts: workaround for weird CPU cores numbering on SN2201

- recipes-kernel/linux/linux-5.10/0086-hwmon-powr1220-Add-support-for-Lattice-s-POWR1014-po.patch
> hw-mgmt: kernel 5.10: Fix of powr1014 patch, correct device id.

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw_management_psu_fw_update_delta.py
- usr/usr/bin/hw_management_psu_fw_update_murata.py
Report only PSU FW version. Remove reporting of tool version, bus,
address and MCU type to make the output easier to read and parse.
> hw-mgmt: psu fw update tool: Simpify FW version reporting output

- usr/usr/bin/hw_management_psu_fw_update_delta.py
- usr/usr/bin/hw_management_psu_fw_update_murata.py
Add -S command line parameter to support skipping PSU redundancy check.
This makes it possible to update PSU FW on systems with a single active
PSU. This option already exists for Murata PSUs and is used for primary
and secondary FW update. Add it for Delta PSUs as well.
With PSU redundancy check disabled, Murata script will not perform PSU
reset after FW update, as this will cause power cycle on systems with
single active PSU.
> hw-mgmt: psu fw update tool: Allow skipping PSU redundancy check

- usr/usr/bin/hw-management-thermal-events.sh
Fix broken index for gearbox temprature symbolic link.
Read this index from gearbox counter.
> hw-mgmt: thermal events: Fix symbolic link creation for gearboxes

- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
> hw-mgmt: kernel 4.19: change patch 0151 of nvsw-sn2201 driver.

- usr/usr/bin/hw-management-thermal-events.sh
There are two different triggers to activate mlxsw_minimal driver:
If SDK is installed activations is trigerred by SDK udev event.
Otherwise by ASIC health event.
Extend criteria for SDK presence detection.
> hw-mgmt: events: Extend validation of SDK presence

- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
> hw-mgmt: kernel 5.10: change patch 0089 of nvsw-sn2201 driver.

- usr/usr/bin/hw-management.sh
Speed up only ASIC de-initialization by setting I2C half cycle register to
400KHz before probing and setting it back to original value in CPLD
after probing. It should switch to 400KHz only for ASIC I2C driver
removing (for probing already it is already supported) to reduce it
time in order to avoid collision with chip reset coming from SDK.
Apply this functionality only for specific system types for both
probing and removing flows.
> hw-mgmt: system: Speed up ASIC de-initialization for Spectrum1/2 systems

- recipes-kernel/linux/linux-5.10/0159-platform-x86-mlx-platform-Add-support-for-new-system.patch
Add support for new system type XH3000, which is a water cooling
Ethernet switch blade equipped with 32x200G Ethernet ports.
The system is recognized by "DMI_BOARD_NAME" and "DMI_PRODUCT_SKU"
matches, when these fields are set to "VMOD0005" and "HI139"
respectively.
> hw-mgmt: patches: 5.10: Add support for new system XH3000

- recipes-kernel/linux/linux-5.10/0160-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
Add support for MQM9510-N leaf and MQM9520-N spine blades for two
flavors of NDR InfiniBand chassis:
- MCS9500: 1,600Tb/s, 2048-port NDR InfiniBand chassis, which includes
32 leaves and 16 spines.
- MCS9510: 800Tb/s, 1024-port NDR InfiniBand chassis, which includes
16 leaves and 8 spines.
MQM9510-N leaf is Nvidia MellanoxÂQuantum(TM) 2 NDR InfiniBand switch
equipped with 64 NDR ports, 32 OSFP dual ports, Coffee Lake COMe
module, 2 Quantum¢ 2 NDR InfiniBand ASICs, 2 Power Supplies (AC) and
with hybrid cooled (liquid and air), supporting non-blocking switching
capacity of 2x25.6Tbps.
MQM9520-N spine is Nvidia MellanoxÂQuantum(TM) 2 NDR InfiniBand switch,
equipped with 64 NDR ports, Coffee Lake COMe module, 2 Quantumâ2 NDR
InfiniBand ASICs, 2 Power Supplies (AC) and with hybrid cooled …
> hw-mgmt: patches: 5.10: platform: mellanox: Introduce support for NDR InfiniBand modular chassis

- usr/usr/bin/hw-management.sh
Fix syntax on linecard events creation.
Changed name lc{N}_prsnt -> lc{N}_present
> hw-mgmt: events: Fix syntax on linecard events creation

- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
- usr/etc/hw-management-sensors/sn2201_sensors.conf
- usr/lib/udev/rules.d/50-hw-management-events.rules
Thermal sensor 0x4a will be removed on the final HW of SN2201
Changes are done in nvsw-sn2201 patches of kernel 4.19, 5.10, udev rules
and appropriate sensors.conf
Change names of several reset causes.
> hw-mgmt: kernel & udev: delete thermal sensor on SN2201

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
Add dynamic mapping between PCIe and I2C ASIC busses.
Support only for new coming systems.
The following attributes will be available:
/var/run/hw-management/config/
asic_num
asic1_i2c_bus_id
asic2_i2c_bus_id (for systems with two ASICs)
asic1_pci_bus_id (for new systems)
asic2_pci_bus_id (for new systems with two ASICs)
Signed-off-by: Vadim Pasternak <vadimp@nvdia.com>
> hw-mgmt: infra: Add support for mapping PCI to I2C ASIC bus

- usr/usr/bin/hw-management.sh
Add basic topology for MQM9510 and MQM9520 components.
> hw-mgmt: topolgy: Add preliminary topology for IB/NDR modular system

- recipes-kernel/linux/linux-5.10/0157-mlx-platform-Add-support-for-systems-equipped-with-t.patch
- recipes-kernel/linux/linux-5.10/0158-platform-mellanox-Introduce-support-for-COMe-NVSwitc.patch
- recipes-kernel/linux/linux-5.10/0159-platform-x86-mlx-platform-Add-support-for-new-system.patch
- recipes-kernel/linux/linux-5.10/0160-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
Update register map in patch #0157.
Rebase follwing after patches: #0158 - #0160.
> hw-mgmg: patches: 5.10: Update register map

- usr/usr/bin/hw-management.sh
Remove unecessary EEPROM 7-0053 for MQM9700 system
Change sensors.conf path for e3597 system
> hw-mgmt: topolgy: Remove unnecessary EEPROM 7-0053 for MQM9700 system

- usr/usr/bin/hw-management.sh
Fix creating of redundant psu3_i2c_addr, psu4_i2c_addr files for
the systems that have less than 4 PSUs count
> hw-mgmt: topolgy:Fix redundant psuX_i2c_addr for systems less than 4 PSU

- debian/changelog
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-helpers.sh
1. Use common helper function for connect/disconenct FAN EEPROMs on SN2201.
2. Fix common usage of i2c_bus_offset. New i2c_bus_offset attribute is added
to hw-management config directory.
> hw-mgmt: scripts: Fix FAN EEPROM insert/removal on SN2201. 		  Common i2c_bus_offset fix.

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-start-post.sh
Add udev event for Global Write Protect.
Add indication for system ready.
> hw-mgmt: events: Add indication for  Global WP and system ready events

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
In udev rules, we have filtering only by i2c address without bus number.
It can cause conflict when we have voltmons on the same addresses
but on different buses. Also, we have configuration when on 2 different systems
we have voltmons with different names but on the same i2c address.
With this commit we introducing voltmon-per-system definition.
For old system we don't need make any changed. For the new systems if we have
conflicts we need to define voltmon connection table in format:
system_dynamic_i2c_bus_connect_table=(
<dev_type> <i2c_addr> <i2c_bus> <voltmon_name> \
<dev_type> <i2c_addr> <i2c_bus> <voltmon_name> \
...
addr> <i2c_bus> <voltmon_name>)
and connect it in platform init:
add_i2c_dynamic_bus_dev_connection_table "${system_dynamic_i2c_bus_connect_table[@]}"
If voltmon …
> hw-mgmt: chassis events: Fix voltmon address conflict on connecting

- debian/changelog
- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
- usr/usr/bin/hw-management-start-post.sh
- usr/usr/bin/hw-management.sh
Changes are done in SN2201 platform driver nvsw_sn2201 for kernel 5.10 and 4.19
and also in user space scripts.
1. Fix shift in board component
2. Add CPLD Minimal versionfor main and CPU board CPLDs.
3. Align as much as possible reset cause names
4. Fix PN register offsets
5. Change register offsets to lower case letters.
> hw-mgmt: kernels & scripts: SN2201 fixes and additions.

- debian/changelog
- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
- usr/usr/bin/hw-management.sh
Fix CPU and MB CPLD access and representation in hw-management.
Clean unused defines in nvsw_sn2201 platform driver.
> hw-mgmt: kernels & script: fix CPLD PN representation on SN2201.

- usr/usr/bin/hw-management.sh
1. Remove max11603 voltage monitors
2. Use mp2888 voltage regulators instead of mp2975
3. Remove nonexisting voltage regulators at address 0x6a
4. Use dymamic i2c connection table for voltage regulators
> hw-mgmt: topology: Update MQM9510 and MQM9520 topologies:

- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Fix dynamic i2c tables for MQM9510 and MQM9520

- usr/usr/bin/hw-management-thermal-events.sh
Motivation to allow setting custom thresholds through 'sensors'
utilities - 'set' instruction.
> hw-mgmt: events: Reset PSU thresholds to read/write access for root user

- usr/usr/bin/hw-management-chassis-events.sh
Disable removal of CPLD3 version file during chipdown.
This fixes the problem of this file missing after chipdown-chip
sequence. Removing this file is unnecessary as CPLD version
cannot change without power cycle.
> hw-mgmt: events: Fix handling of CPLD3 version on SPC1 systems

- debian/hw-management.hw-management.service
Add 3 sec delay between service stop and start to mimic the
behavior of "hw-management.sh restart".
> hw-mgmt: service: Add restart delay to hw-mgmt systemd service

- recipes-kernel/linux/linux-4.19/0159-platform-mellanox-mlxreg-io-Add-locking-for-io-opera.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-mlxreg-io-Add-locking-for-io-opera.patch
Add lock to protect user read/write access to the registers.
> hw-mgmt: patches: 4.19/5.10 Add patch for locking operations

- debian/changelog
- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts: fix mix-up of jtag tdi - tdo pins on SN2201

- debian/changelog
- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
Add "dummy" CPLD FAN LEDs registers to the SN2201 system.
CPLD doesn't handle FAN LEDs on SN2201 but this register will allow triggering of actual LED change
through GPIO by hw-mgmt Udev handler script.
CPLD will change the state of the front panel FAN LED according to these registers.
Also, these registers add alignment of hw-mgmt attributes on SN2201 with other systems.
> hw-mgmt: patches: 4.19/5.10 Add FAN LEDs registers to SN2201 system.

- .github/workflows/build-release.yml
- rpm/gen_rpm.sh
- rpm/hw-management.spec
This patch set implements the following:
1. Support for building the RPM package for hw-management repo,
which can be installed on any Redhat / Fedora based nvidia
switches.
2. Automatically building and attaching deb/rpm packages to
a release. This is done by using GitHub action scripts.
> [PATCH] Support for rpm,deb package release builds

- recipes-kernel/linux/linux-4.19/0157-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0162-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- usr/usr/bin/hw-management.sh
Fix 16-ch i2c bus mux support in NVLink4 managed switch
> hw-mgmt: patches: 4.19/5.10 Fix 16-ch i2c bus mux support in NVLink4 managed switch

- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
Fix LED num for NVLink4 managed switch.
> hw-mgmt: patches: 4.19/5.10 Fix LED num for NVLink4 managed switch

- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Fix setting for SGX H100 system Fix I2C bus device address.

- usr/usr/bin/hw-management.sh
Expose PCI segments to /var/run/hw-management.
> hw-mgmt: config: Expose PCI bus for NV devices

- recipes-kernel/linux/linux-4.19/0159-leds-mlxreg-Send-udev-change-event.patch
- recipes-kernel/linux/linux-5.10/0166-leds-mlxreg-Send-udev-change-event.patch
Add sending udev event from leds-mlxreg driver in case of color change.
Likely these patches will not be accepted upstream as they provide not
so regular flow.
Patches should be taken to NOS's as exceptions in upstream.
> hw-mgmt: patches: 4.19/5.10: Add sending udev event from leds-mlxreg driver.

- debian/changelog
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-i2c-gpio-expander.sh
1. Add handling of LEDs udev change events on SN2201 system.
2. Create LEDs trigger,delay_on, delay_off links just incase that correspondent
files exist in sysfs.
> hw-mgmt: scripts: Add handling of LEDs udev change events on SN2201 system.

- usr/usr/bin/hw-management.sh
Fix issue in PCI bus for SGX-H100 system
Fix default values for sfp/module/gearbox counter
> hw-mgmt: config: Fix PCI bus for SGX-H100 system

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
1. Removed A2D sensor from all COMEX BRDWL boards
2. Add COMEX BRDWL boards with register defined (config3)
support of TPS/XPDE/MPS voltmon
> hw-mgmt: topology: Add COMEX BRDWL respin support

- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
Add config3 register support. This CPLD register using to
detect COMEX board revision.
> hw-mgmt: patches: 4.19/5.10: Add config3 register support

- usr/usr/bin/hw-management.sh
Remove A2D component from MQM9700 system
> hw-mgmt: topology: Remove A2D component from MQM9700 system

- recipes-kernel/linux/linux-5.10/0167-TMP-lan743x-Add-support-for-fixed-phy.patch
- usr/usr/bin/hw-management.sh
Add support for fixed phy for Micrchip LAN device (Vulcan).
Add VPD type for Vulcan system.
> hw-mgmt: pathes: 5.10: Add support for fixed phy

- usr/etc/hw-management-sensors/msn3700_sensors.conf
Add BWD COMEX A1 support to msn3700 system.
> Add BWD COMEX A1 support to msn3700 system.

- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts: Enable System EEPROM/VPD write-protect during hw-management init.

- recipes-kernel/linux/linux-5.10/0168-TMP-mlxsw-minimal-Ignore-error-reading-SPAD-register.patch
Workaround until the firmware will add support for SPAD register
for Infiniband systems.
> TMP: mlxsw: minimal: Ignore error reading SPAD

- usr/usr/bin/hw-management.sh
Removed A2D sensor support from:
1. COMEX CFL board
2. msn3700
3. msn3700C
4. mqm8700
5. msn4600
6. msn4600C
7. msn2700
8. msn2100
9. msn2010
10. mqm9700
11. mqm9510
12. mqm9520
> hw-mgmt: topology: Removed A2D sensor support

- usr/usr/bin/hw-management.sh
Handle MSN27002 system in the same manner as MSN2700:
set I2C bus frequency 400KHz during I2C ASIC drive probe / remove.
> hw-mgmt: Add probe/remove accelaration for MSN27002 system

- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
> kernel patches: 5.10/4.19: Add erot{X}_ap_reset attribute for NVLink4 managed switch

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management.sh
Move SN4800 from default to real table.
> hw-mgmt: thermal: Add dynamic minimum table for SN4800

- usr/usr/bin/hw-management.sh
Change from 22000 to 18000 RPM.
> hw-mgmt: thermal: Change fan maxumum speed for SN4800

- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0159-mlx-platform-Add-support-for-systems-equipped-with-t.patch
- recipes-kernel/linux/linux-5.10/0160-platform-mellanox-Introduce-support-for-COMe-NVSwitc.patch
- recipes-kernel/linux/linux-5.10/0161-platform-x86-mlx-platform-Add-support-for-new-system.patch
- recipes-kernel/linux/linux-5.10/0162-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
Fix access to CPLD register bits: erot{X}_reset, erot{X}_recovery
Fix spi_chnl_select access
Fix default value for PWM_CONTROL CPLD register
> kernel patches: 5.10/4.19: Fix NVLink4 CPLD registers access

- recipes-kernel/linux/linux-4.19/0161-i2c-mlxcpld-Fix-register-setting-for-400KHz-frequenc.patch
- recipes-kernel/linux/linux-5.10/0170-i2c-mlxcpld-Fix-register-setting-for-400KHz-frequenc.patch
- usr/etc/hw-management-sensors/msn4800_sensors_lc.conf
- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management.sh
Allow 400KHz as basic i2C frequency for SN4800 system.
> hw-mgmt: infra: Remove bring-up WA for basic I2C frequency

- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
> hw-mgmt: kernel patches 4.19 & 5.10: align reset_aux_pwr_or_ref attribute name on SN2201

- recipes-kernel/linux/linux-4.19/0162-platform-mellanox-mlxreg-lc-Fix-cleanup-on-failure-a.patch
- recipes-kernel/linux/linux-4.19/0163-TMP-DBG-platform-mellanox-mlxreg-lc-Add-debug-delay.patch
(1)
platform/mellanox: mlxreg-lc: Fix cleanup on failure and more verbosity in error flow
Clean client object in case of probing failure.
Prevent running remove routine in case probing failed.
Add error log for each kind of failures during probing.
Fixes: 62f9529b8d5c ("platform/mellanox: mlxreg-lc: Add initial support for Nvidia line card devices")
(2)
TMP: DBG: platform/mellanox: mlxreg-lc: Add debug delay
Add debug delay prior the first access to line card.
> hw-mgmt: kernel patches v4.19: Fixes for line card insertion/removing

- debian/changelog
- recipes-kernel/linux/linux-4.19/0145-hwmon-Add-support-for-EMC2305-RPM-based-PWM-Fan-Spee.patch
- recipes-kernel/linux/linux-5.10/0087-hwmon-Add-support-for-EMC2305-RPM-based-PWM-Fan-Spee.patch
Set the same manner of setting cooling_cur_state in SN2201 as on other systems,
where it's done through mlxreg_fan driver.
> hw-mgmt: kernel patches v4.19 & v5.10: Align emc2305 driver with mlxreg-fan driver.

- usr/usr/bin/hw-management-chassis-events.sh
Fix voltmon sensors linking by their labels.
vin/vin1 ->    *voltmon*_in1_input
vout/vout1 ->  *voltmon*_in2_input
vout2 ->       *voltmon*_in3_input
iin/iin1 ->    *voltmon*_curr1_input
iout/iout1 ->  *voltmon*_curr2_input
iout2 ->       *voltmon*_curr3_input
pin/pin1 ->    *voltmon*_power1_input
pout/pout1 ->  *voltmon*_power2_input
pout2 ->       *voltmon*_power3_input
> hw-mgmt: chassis events: Fix voltmon connection by label

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-start-post.sh
This patch fixes the incorrect number of cpld entries in
the '/var/run/hw-management/cpld*_*'. [cpld1..4]_* links are
created irrespective of the platform. For example, this
approach has lead to the existance of cpld4_* links, on a
platform with 3 cpld. This was happening due to a race
condition in which clean up of the unwanted symbolic links
executes before the actual entries are created.
Solution is to create the cpld links based on the platform
parameter 'cpld_num', which tells total number of cpld
per platform.
This addresses the bug 3107709
> Fixing the incorrect cpld entries

- usr/usr/bin/hw-management-ready.sh
Optime pre-init sequence and avoid endless loop.
> hw-mgmt: init: Optimize pre-init sequence

- usr/usr/bin/hw-management-chassis-events.sh
vin/vin1 -> voltmon_in1_input
vout/vout1 -> voltmon_in2_input
vout2 -> voltmon_in3_input
iin/iin1 -> voltmon_curr1_input
iout/iout1 -> voltmon_curr2_input
iout2 -> voltmon_curr3_input
pin/pin1 -> voltmon_power1_input
pout/pout1 -> voltmon_power2_input
pout2 -> voltmon_power3_input
> Fix voltmon sensors linking by their labels for mp2975.

- usr/usr/bin/hw-management-i2c-gpio-expander.sh
There is inconsistency in label name reported by pca9555 gpiochip.
In kernel 5.10.43 it's reported according to bus-address (7-0027) and
in kernel 4.19 it's reported by driver name - pca9555.
Check both cases when looking to gpiobase.
> hw-mgmt: scripts: Fix inconsistent label name of pca9555 gpiochip on SN2201

- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Remove A2D i2c sensors from MSN2700/MSN2410 systems Remove A2D i2c sensors from MSN2700/MSN2410 systems management + CPU board

- recipes-kernel/linux/linux-5.10/0135-mlxsw-core_linecards-Add-line-card-objects-and-imple.patch
In upstream code mlxsw driver has ability to burn INI.
This is not relevant for case when mlxsw_minimal driver is co-existing with
Nvidia SDK software, where this file is not supposed to be present.
Disable any attempt to find INI file to avoid output of warning message.
> hw-mgmt: patches: v5.10: Skip attempt to access line card INI

- usr/usr/bin/hw-management-thermal-events.sh
Delta 2000 PSU supports in-system FW update.
Add hw-management attribute reporting its FW version.
> hw-mgmt: psu: Report Delta 2000 FW version

- usr/lib/udev/rules.d/50-hw-management-events.rules
MQM9510 and MQM9520 have 4 and 9 leakage sensors respectively:
one is rope sensor and others are PCB sensors. Modify leakage
rules to reflect that.
> hw-mgmt: rules: Update leakage event rules

- recipes-kernel/linux/linux-4.19/0160-DS-leds-leds-mlxreg-Send-udev-event-from-leds-mlxreg.patch
- recipes-kernel/linux/linux-5.10/0167-DS-leds-leds-mlxreg-Send-udev-event-from-leds-mlxreg.patch
Reformat leds-mlgreg patches, so they can be applied with git am.
Rename them to show that these are just downstream patches.
> hw-mgmt: kernel patches 4.19, 5.10: Reformat downstream leds-mlxreg patch and rename them.

- recipes-kernel/linux/linux-5.10/0174-core-Add-support-for-OSFP-transceiver-modules.patch
Add support for OSFP transceiver modules by adding their SFF-8024
Identifier Value (0x19).
This is required for future NVIDIA Spectrum-4 based systems that will be
equipped with OSFP transceivers.
> hw-mgmt: patches: 5.10: Add OSFP support

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-if-rename.sh
On mutli-asic systems like MQM9510 and MQM9520 the current netdev
renaming udev rule will create conflicts, as each port name appears
on multiple switches. Fix this by incorporating switch name into
port name. Also, move the rule to the end of list to ensure it is
executed last and not overriden by the old MAC-based netdev rules.
> hw-mgmt: rules: Add support for netdev renaming on multi-asic systems

- recipes-kernel/linux/linux-5.10/0162-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Add-COME-board-revision-register.patch
- recipes-kernel/linux/linux-5.10/0164-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0173-TMP-platform-mlx-platform-Add-SPI-path-for-NVLink-sw.patch
Add support for CPLD5 sysfs attributes.
CPLD5 is introduced in MQM9520 NDR modular spine.
> hw-mgmt: patches: 5.10: Add CPLD5 support

- recipes-kernel/linux/linux-4.19/0145-hwmon-Add-support-for-EMC2305-RPM-based-PWM-Fan-Spee.patch
- recipes-kernel/linux/linux-5.10/0087-hwmon-Add-support-for-EMC2305-RPM-based-PWM-Fan-Spee.patch
- usr/usr/bin/hw-management.sh
1. Support 0 RPM report in case that tacho read is below minimal range.
2. Change Fan minimal to 2200 RPM. This is a real RPM speed when FAN still rotates.
> hw-mgmt: patches: 4.19 & 5.10: report 0 RPM speed in EMC2305 driver for SN2201 system.

- usr/usr/bin/hw-management.sh
Add symbolic links for I2C busses for mqm9510 and mqm9520 systems.
> hw-mgmt: Add symbolic links for I2C busses on main board for NDR systems

- recipes-kernel/linux/linux-4.19/0145-hwmon-Add-support-for-EMC2305-RPM-based-PWM-Fan-Spee.patch
- recipes-kernel/linux/linux-5.10/0087-hwmon-Add-support-for-EMC2305-RPM-based-PWM-Fan-Spee.patch
Remove blank lines and whitespaces in 5.10 and 4.19 patches.
They causes warning when patches are applied by "git am" command.
> hw-mgmt: patches 5.10 & 4.19: clean "git am" warnings of EMC2305 patches for SN2201 system

- usr/usr/bin/hw-management.sh
This patch enables the i2c 3.4MHz support for Aerial/Komodo
> Enable i2c 3.4MHz support for Komodo

- usr/usr/bin/hw-management.sh
Make sure the configuration parameters are set before udev is
started, otherwise they may be undefined in scripts started by
udev rules.
> hw-mgmt: init: Set config parameters before starting udev

- usr/usr/bin/hw-management-thermal-events.sh
> hw-mgmt: attributes: Fix naming of leakage sensor attributes

- usr/usr/bin/hw-management-thermal-events.sh
1. Don't create link to temp1_alarm. This attribute unneeded and undocumented.
2. Check if temp1_min attribute exist before link creation.
Old driver versions of nvme hwmon don't create this attribute.
> hw-mgmt: scripts: changes in links of NVMe SSD temperatures.

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-thermal-events.sh
On some systems SODIMM thermal sensor can be found on i2c bus  other then
default i2c-0. This commit add possibility to connect SODIMM i2c thermal
sensor on all i2c buses
> hw-mgmt: attributes: Fix SODIMM thermal sensor linkage

- usr/usr/bin/hw-management-devtree-check.sh
- usr/usr/bin/hw-management-devtree.sh
Add possibility to convert devtree and devtree_codes files that are created during
SMBios BOM string parsing to csv file.
This file can be opened later in Excel in order to compare with original design.
> hw-mgmt: scripts: add conversion of SMBIOS alternative BOM devtree file to csv format.

- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
- recipes-kernel/linux/linux-4.19/0159-platform-mellanox-Add-COME-board-revision-register.patch
- recipes-kernel/linux/linux-4.19/0160-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0162-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Add-COME-board-revision-register.patch
- recipes-kernel/linux/linux-5.10/0164-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0173-TMP-platform-mlx-platform-Add-SPI-path-for-NVLink-sw.patch
1. Add inversion to leakage status attributes
2. Fix leakage LED CPLD mask
> hw-mgmt: patches 5.10 & 4.19: Update NDR modular chassis patch

- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts: Fix mgmt board I2C bus offsets for MQM9510 and MQM9520

- usr/usr/bin/hw-management.sh
Change 'exit' to 'return' in add_come_named_busses().
Add missed spaces.
> hw-mgmt: Add fixes for naming bus and cosmetic changes

- usr/usr/bin/hw-management.sh
Change 'exit' to 'return' in add_come_named_busses().
Add missed spaces.
> Add fixes for naming bus and cosmetic changes

- usr/usr/bin/hw-management-thermal-control.sh
This patch updates the thermal control suspend resume behaviour
by not setting the policy during suspend.
Bugs Fixed: 3100612
> Thermal policy change during suspend

- usr/usr/bin/hw-management-thermal-events.sh
This patch fixes the missed out config/psu[1-2]_eeprom_us attributes
after the hw-management service is restarted. This issue happens
because psu controllers are not removed during the hw-management stop.
The corresponding eeprom device files
/sys/devices/platform/mlxplat/i2c_mlxcpld.1/i2c-1/i2c-4/4-00[50-51]/eeprom
are also not removed.
Bugs Fixed: 3168642
> Fixing the psu attributes on hw-management restart

- recipes-kernel/linux/linux-5.10/0176-platform-mellanox-fix-reset_pwr_converter_fail-attri.patch
- recipes-kernel/linux/linux-5.10/0177-Documentation-ABI-fix-description-of-fix-reset_pwr_c.patch
- recipes-kernel/linux/linux-5.10/0178-platform-mellanox-Introduce-support-for-next-generat.patch
This patchset series contains:
- fix reset_pwr_converter_fail attribute.
- fix description of fix reset_pwr_converter_fail attribute.
- introduce support for next-generation 800GB/s ethernet switch.
- add description of new attributes on NG800 family of systems.
> hw-mgmt: patches 5.10: add support of sn5600 systems.

- usr/usr/bin/hw-management.sh
This patch set implements:
1. Enable access to SyncE eeprom
2. Disable i2c 3.4MHz setting
> Komodo bring-up changes

- recipes-kernel/linux/linux-4.19/0169-platform-mellanox-fix-reset_pwr_converter_fail-attri.patch
Change incorrect reset_voltmon_upgrade_fail atitribute name to
reset_pwr_converter_fail.
> hw-mgmt: patches 4.19: fix reset_pwr_converter_fail attribute.

- recipes-kernel/linux/linux-5.10/0180-hwmon-pmbus-Fix-sensors-readouts-for-MPS-Multi-phase.patch
Fix scale factors for reading MPS Multi-phase mp2888 controller.
Fixed sensors:
- PIN/POUT: based on vendor documentation, set base scale factor 0.5W/LSB
- IOUT: based on vendor documentation, set base scale factor 0.25 A/LSB
- IOUT phases: fix calculation formula according to vendor documentation
Fixes: e4db7719d037 ("hwmon: (pmbus) Add support for MPS Multi-phase mp2888 controller")
> hw-mgmt: patches 5.10: hwmon: (pmbus) Fix sensors readouts for MPS Multi-phase mp2888 controller

- usr/etc/modules-load.d/05-hw-management-modules.conf
> hw-mgmt: modules-load.d: remove not upstreamed icp201xx module from list.

- usr/usr/bin/hw-management.sh
In some marginal cases during early initialization sysfs entry name for mlxreg-io driver can be created with some small delay. In such case the below error is output to syslog:
"ERR hw-management: mlxreg_io is not loaded".
Add retry mechanism to protect from such timing issue.
Fixes: [SONIC - Design - Bug SW #3177482] [Non-Functional ] [HW-mgmt] [error in log] | ERR hw-management: mlxreg_io is not loaded
> hw-mgmt: init: Add retry mechanism for regio detection

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Add generic function to be used for retries.
Function is defined as below
> hw-mgmt: init: Make common helper for retry mechanism

- usr/usr/bin/hw-management-thermal-control.sh
When TC starts, it checks the state of thermal zones. If some TZ
returns a wrong (zero) value in temp_trip_high together with the valid
temperature, then TC not returning the cooling level to normal value.
This fix adds stage of "re-init" cooling level value after temp_trip_high
value becomes normal
Fixes: RM #3200958 : Unexpected high FAN RPM value with CL5.2
> hw-mgmt: thermal: Fix unexpected high FAN RPM value during TC start

- usr/etc/hw-management-sensors/sn3750sx_sensors.conf
- usr/usr/bin/hw-management.sh
There has been a BOM change in the Komodo. Temperature sensor at 7-004a has been changed to tmp102 from adt75.
> [Komodo] Changing the temperature sensor

- usr/usr/bin/hw-management-chassis-events.sh
Remove sleep to speed-up initialization
> hw-mgmt: init: Remove redundant sleep from init flow

- debian/changelog
- usr/etc/hw-management-sensors/sn5600_sensors.conf
1. Ignore exception VLs (in2) of Delta power-converter.
This input isn't reported in standard linear form by vendor.
It still can be read by raw pmbus command, not through pmbus driver, and converted
by exception formula provided by Delta.
2. Beautify: fix indentations.
> hw-mgmt: sensors.conf: changes of SN5600 sensors configuration.

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
For most PSUs we assume that fan speed is always given in duty cycle (percentage) units. This may not always be the case, for example the PSU FW default units may be RPM, or the units can be modified by kernel driver or userspace tools. Create a routine to set PSU fan speed that expicitly sets speed units and use it at all places where PSU fan speed is being set.
> hw-mgmt: psu: Add routine to set PSU fan speed

- usr/etc/hw-management-sensors/sn3750sx_sensors.conf
Adding the missed out power/current fields
> sensors.conf: Correcting SN3750SX sensors config

- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Fix voltmon i2c bus addresses for P4697 system Fix mp2975 voltmon's i2c bus addresses for P4697 system

- debian/changelog
- recipes-kernel/linux/Patch_Status_Table.txt
- usr/etc/modules-load.d/05-hw-management-modules.conf
- usr/usr/bin/hw-management.sh
> hw-mgmt init & docs: remove icp201xx pressure sensor from common hw-mgmt handling

- debian/changelog
- usr/etc/hw-management-sensors/sn5600_sensors.conf
- usr/usr/bin/hw-management-thermal-events.sh
1. Sensors: Rename SODIMM, PCH and ACPI sensors
2. Sensors: Ignore curr2 in power converter
3. Sensors: space alignment
4. Script: fix psu2_info renaming
> hw-mgmt: sensors & scripts: changes for SN5600

- usr/usr/bin/hw-management.sh
There are only 2 CPLDs on MSB78xx systems, do not create cpld_port attribute to avoid reading cpld3 version on these systems. In case reading cpld3 version is attempted anyway, (e.g. due to error in system identification), do not display error message.
> hw-mgmt: attributes: Avoid reading cpld3 version om MSB78xx systems

- README.md
- debian/changelog
- usr/etc/modules-load.d/05-hw-management-modules.conf
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-thermal-events.sh
1. Drivetemp driver allows to report SSD temperature in sensors command.
2. Create drivetemp links in hw-management.
> hw-mgmt: scripts & udev: add SSD temperature report.

- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Add support for MQM9700 SYSID=5 with XDPE+STTS sensors

- recipes-kernel/linux/linux-4.19/0071-leds-mlxreg-Allow-multi-instantiation-of-same-name-L.patch
- recipes-kernel/linux/linux-4.19/0157-platform-mellanox-Introduce-support-for-COMe-managem.patch
- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
- recipes-kernel/linux/linux-4.19/0159-platform-mellanox-Add-COME-board-revision-register.patch
- recipes-kernel/linux/linux-4.19/0160-platform-mellanox-Introduce-support-for-rack-manager.patch
- recipes-kernel/linux/linux-5.10/0051-leds-mlxreg-Allow-multi-instantiation-of-same-name-L.patch
- recipes-kernel/linux/linux-5.10/0160-platform-mellanox-Introduce-support-for-COMe-managem.patch
- recipes-kernel/linux/linux-5.10/0161-platform-x86-mlx-platform-Add-support-for-new-system.patch
- recipes-kernel/linux/linux-5.10/0162-platform-mellanox-Add-COME-board-revision-register.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-rack-manager.patch
- recipes-kernel/linux/linux-5.10/0167-DS-lan743x-Add-support-for-fixed-phy.patch
- recipes-kernel/linux/linux-5.10/0172-DS-platform-mlx-platform-Add-SPI-path-for-rack-switc.patch
- recipes-kernel/linux/linux-5.10/0176-platform-mellanox-fix-reset_pwr_converter_fail-attri.patch
- recipes-kernel/linux/linux-5.10/0178-platform-mellanox-Introduce-support-for-next-generat.patch
Removing the internal product name references from the kernel patches.
> Modifying some kernel patch names and contents

- usr/usr/bin/hw-management-chassis-events.sh
> hw-mgmt: chassis events: Add link for reading voltmon thermal sensor

- usr/usr/bin/hw-management-thermal-events.sh
Added psuX_fan_dir attrbute to {hw-management}/thermal/ folder
Value in this file represents PSU fan direction:
0 - Forward (C2P)
1 - Reverse (P2C)
2 - unknown (read error or field missing)
PSU FAN direction value can be extracted from PSU VPD, which can be in 2 formats:
1. PN_VPD_FIELD: MTEF-PSF-AC-G
2. PN_VPD_FIELD: 930-9SPSU-00RA-00B
> hw-mgmt: psu: Add psuX_fan_dir attribute

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0181-Revert-Fix-out-of-bounds-memory-accesses-in-thermal.patch
This reverts commit e59d839743b50cb1d3f42a786bea48cc5621d254.
Commit is reverted until thermal infrastructure is ready for other fan devices used by Nvidia systems. Usage of `cooling_cur_state` for setting fan speed has been deprecated
in kernel 5.17 by thermal maintainers. New interface for fan
speed enforcing should be done from `hwmon`.
After all fan drivers are aligned, commit will be retuned back.
> mlxsw: thermal: Fix out-of-bounds memory accesses

- recipes-kernel/linux/linux-5.10/0181-Revert-Fix-out-of-bounds-memory-accesses-in-thermal.patch
This patch fixes the build break introduced by
0181-Revert-Fix-out-of-bounds-memory-accesses-in-thermal.patch
> Fixing a build break

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0182-platform-mellanox-Introduce-support-of-new-Nvidia-L1.patch
- recipes-kernel/linux/linux-5.10/0183-platform-mellanox-Split-initialization-procedure.patch
- recipes-kernel/linux/linux-5.10/0184-platform-mellanox-Split-logic-in-init-and-exit-flow.patch
- recipes-kernel/linux/linux-5.10/0185-platform-mellanox-Extend-all-systems-with-I2C-notifi.patch
- recipes-kernel/linux/linux-5.10/0186-platform-mellanox-mlxreg-hotplug-Allow-more-flexible.patch
Currently hotplug configuration in logic device assumes that all items are provided with no holes.
Thus, any group of hotplug events, associated with the specific status/event/mask registers is configured in those registers successively from bit zero to bit #n (#n < 8).
This logic is changed int order to allow non-successive definition to support configuration with the skipped bits – for example bits 3, 5, 7 in status/event/mask registers can be associated with hotplug events, while others can be skipped.
> hw-mgmt: kernel patches: Add patch for extending hotplug confuguration

- usr/usr/bin/hw-management-chassis-events.sh
> hw-mgmt: fan: Fix fan dir attribute for systems without CPLD fan direction attribute

- usr/usr/bin/hw_management_psu_fw_update_common.py
- usr/usr/bin/hw_management_psu_fw_update_delta.py
Delta 550 FW version reporting format (XX.YY.ZZ) differs from other Delta PSUs (2000/3000), which report FW version as XX.YY. Add check to detect 550 model and report its FW version correctly.
> hw-mgmt: psu: Fix reporting of Delta 550 FW version

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0187-platform_data-mlxreg-Add-field-with-mapped-resource-.patch
- recipes-kernel/linux/linux-5.10/0188-i2c-mux-Add-register-map-based-mux-driver.patch
- recipes-kernel/linux/linux-5.10/0189-i2c-mlxcpld-Allow-driver-to-run-on-ARM64-architectur.patch
- recipes-kernel/linux/linux-5.10/0190-i2c-mlxcpld-Modify-base-address-type.patch
- recipes-kernel/linux/linux-5.10/0191-i2c-mlxcpld-Allow-to-configure-base-address-of-regis.patch
- recipes-kernel/linux/linux-5.10/0192-i2c-mlxcpld-Add-support-for-extended-transaction-len.patch
- recipes-kernel/linux/linux-5.10/0193-platform-mellanox-mlx-platform-Add-mux-selection-reg.patch
- recipes-kernel/linux/linux-5.10/0194-platform-mellanox-mlx-platform-Move-bus-shift-assign.patch
- recipes-kernel/linux/linux-5.10/0195-platform-mellanox-Add-support-for-dynamic-I2C-channe.patch
- recipes-kernel/linux/linux-5.10/0196-platform-mellanox-Use-dynamic-I2C-channels-allocatio.patch
…nd extra I2C features
Add patches #0187 - #0196.
> hw-mgmt: kernel patches: Add patches for dynamic I2C bus allocation

- usr/etc/hw-management-sensors/p4697_sensors.conf
> hw-mgmt: topology: Fix NVL4 volrmon senor names

- usr/usr/bin/hw-management-generate-dump.sh
This patch adds the support for cpld dump capture in the hw-management dump generation script.
> Capturing cpld dump in the hw-management dump

- .github/workflows/build-release.yml
Updating the GitHub workflow script to support building arm64 debian package.
> Support for building arm64 deb package

- debian/changelog
- usr/usr/bin/hw-management-chassis-events.sh
This iio udev trigger is mixed-up on Moose system with iio pressure sensor.
> hw-mgmt: scripts: make ii0 a2d link just in case that file exist.

- usr/usr/bin/hw-management-helpers.sh
BlueField-3 uses Cortex-A78AE ARM cores, which have 0xD42 P/N.
> hw-mgmt: Fix detection of BlueField-3 CPU type

- debian/changelog
- usr/etc/hw-management-sensors/sn5600_sensors.conf
Delta 3K PSU does not support 0x31 (POUT_MAX) PMBus command. In response to this command it returns 0xff 0xff as data and 0xff as PEC. For PSU on address 0x5a the calculated PEC is indeed 0xff, which causes linux PMBus PSU driver to recognize this command as supported and create power2_cap sysfs attribute with some invalid data.
Add WA to show the value of this attribute as 0 in the output of "sensors" command.
> hw-mgmt: sensors: Add WA for unsupported PSU command in SN5600 config

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0269-platform-mellanox-Cosmetic-changes.patch
- recipes-kernel/linux/linux-5.10/0270-platform-mellanox-Fix-order-in-exit-flow.patch
- recipes-kernel/linux/linux-5.10/0271-platform-mellanox-Add-new-attributes.patch
Add patches:
0269-platform-mellanox-Cosmetic-changes.patch
0270-platform-mellanox-Fix-order-in-exit-flow.patch 0271-platform-mellanox-Add-new-attributes.patch
Update patch table.
> hw-mgmt: kernel v5.10: Add new patches

- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts: define I2C CPU brd offset in P4262 system.

- usr/usr/bin/hw-management.sh
Add JTAG offsets for CFL and BWL COME.
> hw-mgmt: Add configuration for JTAG offsets

- debian/changelog
- usr/etc/hw-management-sensors/p4262_sensors.conf
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management.sh
1. Update types and adresses of components.
2. Update sensors.conf components and their labels.
3. Fix VPD and IPMI EEPROMs link creation.
> hw-mgmt: scripts & conf: configuration changes and fix for P4262 system

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0273-platform-mellanox-Add-field-upgrade-capability-regis.patch
- recipes-kernel/linux/linux-5.10/0274-platform-mellanox-Modify-reset-causes-description.patch
Fix desription of patch:
0273-platform-mellanox-Add-field-upgrade-capability-regis.patch Add:
0274-platform-mellanox-Modify-reset-causes-description.patch
Update patch table.
> hw-mgmt: patches 5.10: Add and modfiy patches

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0094-hwmon-mlxreg-fan-Extend-driver-to-support-multiply-c.patch
> hw-mgmt: patches 5.10: Align patch with upstream

- usr/usr/bin/hw-management-chassis-events.sh
In newer switches, the LED color is amber and not orange. This patch renames the LED attributes that contains the string 'orange' to 'amber'. Also updates the capability string from 'orange' to 'amber'.
Issue addressed: #3234522
**Unit Test**
```
root@r-leopard-29:/var/run/hw-management/led# ls
led_fan1                  led_fan2_capability       led_fan3_state            led_fan5_amber_trigger    led_fan6_green_trigger      led_status_amber_delay_on
led_fan1_amber            led_fan2_green            led_fan4                  led_fan5_capability       led_fan6_state              led_status_amber_trigger
led_fan1_amber_delay_off  led_fan2_green_delay_off  led_fan4_amber            led_fan5_green            led_psu                     led_status_capability
led_fan1_amber_delay_on …
```
> hw-mgmt: scripts: LED color attribute change

- recipes-kernel/linux/linux-5.10/0278-platform-mellanox-mlx-platform-Modify-graceful-shutd.patch
- usr/etc/hw-management-sensors/p4262_sensors.conf
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
Remove empty labels.
Fix hotswap config.
> hw-mgmt: sensors: Fix configuration for P4262

- recipes-kernel/linux/deploy_kernel_patches.py
Change sort rule for "feature upstream" patches from "candidate" to "accepted"
> hw-mgmt: kernel patches: Fix deploy patch tool sort rule

- debian/rules
> hw-mgmt: thermal: Add TC service start by default

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/deploy_kernel_patches.py
1. Add OPT to deploy patch tool support list
2. Fix patch copy rule based on  patch status
> hw-mgmt: patches 5.10: Add OPT-OS support to deploy patch tool

- usr/usr/bin/hw_management_thermal_control.py
Fixed issue when ensors errors was handled even if sensor is blocked.
BUG: #3438388
> hw-mgmt: thermal: Fix adding sensors to block

- recipes-kernel/linux/Patch_Status_Table.txt
Change patch status:
0166-DS-leds-leds-mlxreg-Send-udev-event-from-leds-mlxreg.patch -> Downstream accepted
0167-DS-lan743x-Add-support-for-fixed-phy.patch -> Downstream
> hw-mgmt: kernel patches: Change patch stastus for 0166, 0167

- debian/changelog
- usr/usr/bin/hw_management_thermal_control.py
Fix for bug which can happens on stop TC when it in INIT state.
AttributeError: 'ThermalManagement' object has no attribute 'fan_drwr_num'
Bug: #3446102
> hw-mgmt: thermal: Fix bug ' object has no attribute 'fan_drwr_num'

- debian/changelog
- usr/usr/bin/hw-management-devtree.sh
1. Change driver to right name stts751 instead stts375
2. Add as additional alternative to Moose.
> hw-mgmt: scripts: SMBIOS BOM mechanism stts temp sensor fixes.

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0265-hwmon-mlxreg-fan-Return-zero-speed-for-broken-fan.patch
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-generate-dump.sh
- usr/usr/bin/hw-management-lc-fru-parser.py
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_psu_fw_update_common.py
- usr/usr/bin/hw_management_psu_fw_update_delta.py
- hw-mgmt: psu: Add psuX_fan_dir attribute
- hw-mgmt: fan: Fix fan dir attribute for systems without CPLD fan direction attribute
- hw-mgmt: psu: Fix wrong direction in psuX_fan_dir attribute
- Fix unknown FAN dir for fixed systems with the custom PN
- hw-mgmt: kernel patches: Add patches for fan speed fix
- hw-mgmt: scripts: fix cpu_core temperature links creation.
- hw-mgmt: psu: Add reporting of Delta PSU primary FW version
- hw-mgmt: psu: Fix reporting of Delta 550 FW version
- Capturing cpld dump in the hw-management dump
- hw-mgmt: debug: Add vpd binary dump
- hw-mgmt: Add command to expose reset cause
> V.7.0020.4100 BR

- recipes-kernel/linux/linux-5.10/patchwork/0188-i2c-mux-Add-register-map-based-mux-driver.patch.txt
Add "patchwork" whgich contains links for patchwork discussions
per patch name.
./recipes-kernel/linux/linux-<major_ver>/patchwork/<patch_name>.txt
> hw-mgmt: patches 5.10: Add patchwork folder

- usr/usr/bin/hw-management-generate-dump.sh
Remove i2cdetect from dump, since access to some
busses causes collision between SW and FW.
Fixes: [SONIC - Design] Bug SW #3447830: [Functional-DOA] [I2C] | I2C bus is getting stuck, recovered only by a power cycle
> hw-mgmt: dump: Remove i2cdetect from dump

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-generate-dump.sh
- usr/usr/bin/hw-management-ready.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
- usr/usr/bin/iorw.sh
On BF3 ARM64 systems mlx-platform driver uses ACPI to idenify the system. As a result, mlx-platform driver files under sysfs have different names than on X86 systems. This patch adds support for BF3 mlx-platform file names.
> hw-mgmt: Add support for mlx-platform driver on BF3 systems

- usr/usr/bin/hw-management-ready.sh
Fix hw-management init issue. It took sometimes tool much time ~ 180sec
Bug:#3485095
4#	usr/usr/bin/thermal_data_grabber.py
> hw-mgmt: init: Fix hw-management init

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0283-mlxsw-core_hwmon-Align-modules-label-name-assignment.patch
- usr/usr/bin/hw-management-thermal-events.sh
In newer platforms like Komodo there is an additional OCXO temperature sensor. This sensor is enabled in the firmware and the platform driver returns the SFP module number which starts with three and causes the
module*_temperature attributes to start with module2. This patch fixes the numbering issue.
> hw-mgmt: patches 5.10: Fix for asic sensor count

- debian/changelog
- usr/usr/bin/hw_management_thermal_control.py
1. If one of amb_sensor read error - ignore it and set "sensor_read" error
(after 3 times)
2. If >1 of amb sensors read error - set PWM to max (100%)
> hw-mgmt: thermal: Update ambiant sensor logic

- debian/changelog
- usr/etc/hw-management-sensors/msn4700_respin_sensors.conf
- usr/etc/hw-management-sensors/msn4700_sensors.conf
PSUs on SN4600/SN4700 systems reports on weird way FAN2 and FAN3
spite that only FAN1 exists. Ignore them.
Bug RMID# 3522603.
> hw-mgmt: sensors: ignore PSU fan2, fan3 on SN4600/SN4700 systems.

- usr/usr/bin/hw-management-chassis-events.sh
The attributes voltmon*_temp_input is not created and this patch fixes that.
Issue# 3530045
> Fix for Voltmon temperature attribute in Gorilla

- debian/changelog
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
1. Fix fan_map usage in case of mlxreg-fan.
2. Remove fan inversed settings for MSN27002.
It's now fixed in new HW carrier board.
> hw-mgmt: scripts: fix missing fan attributes on Panther-Comex system

- usr/usr/bin/hw-management.sh
Validate after 'chipup' that 'hwmon' object is created. If it is not - retry operation by 'chipdown' / 'chipup' up to 3 times.
For manual testing runat the same time:
hw-management.sh chipup &
/etc/init.d/sxdkernel start &
The second operation should reset ASIC and causing failure of the 1-st operation.
Retry mechanism should recover this failure.
> hw-mgmt: Add resiliency mechanism for chipup operation

- usr/etc/modules-load.d/05-hw-management-modules.conf
- usr/usr/bin/hw-management.sh
Some drivers are not available for older kernels. For
example drivetemp module is not present in 4.19 kernel.
This patch adds a function to load such modules based
on their availability in a specific kernel version.
Issue: #3516754
>  Loading modules based on the availability 

- usr/usr/bin/hw-management-generate-dump.sh
- usr/usr/bin/hw-management.sh
Add i2c trace to hw-management dump.
Add i2c trace log rotation.
> hw-mgmt: Extend i2c trace logging support

- usr/usr/bin/hw-management-ready.sh
- usr/usr/bin/hw-management.sh
This patch disables the hw-mgmt and hw-mgmt-tc
on the platforms where BSP platform emulation is
not supported.
> Disable hw-mgmt on SimX platforms

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-labels-maker.sh
Label maker script is invoked while creating the symbolic links during the udev events. In old systems which are having less powerful cpu, it's creating some performance
overhead. This patch moves the sku check to one levl above so that label maker script process will not be invoked.
> Fix performance issue in less powerful cpu systems

- usr/usr/bin/hw_management_thermal_control.py
Fixed file reading issue in TC: "[Errno 19] No such device"
Bug #3534779 "hw-management-tc failed to start after cold reboot and no automatic restart"
> hw-mgmt: thermal: TC fix file reading issue

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0285-platform-mellanox-nvsw-sn2201-change-fans-i2c-busses.patch
Define the exact i2c bus (adapter number) of fans on the SN2201 system.
This will cause fan's EEPROMs be connected already from nvsw-sn2201
platform driver and not from user space after receiving udev events.
> hw-mgmt: patches kernel 5.10: fix timing issue of add FAN EEPROMs on SN2201.

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
Set attributes "events_ready" to 1 after VPD parsing is
done.
> hw-mgmt: Add indicator for VPD parsing completion

- usr/usr/bin/hw_management_thermal_control.py
Fix TC service error for unsupported systems
Bug: #3517930
"fanless system fails hw-management-tc.service at boot up and also fails to restart after boot up"
> hw-mgmt: thermal: fix TC start for unsupported systems

- usr/usr/bin/hw-management.sh
For old MSN3700 systems SMBIOS SKU field is programmed as "MSN3700", instead
of the new format HIXXX.
This commit add support for "old style" SKU for "MSN3700/MSN3700C" systems.
Bug: #3541643
> hw-mgmt: scripts: fix msn3700/3700C init for systems with old SKU format

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-labels-maker.sh
- usr/usr/bin/hw-management-thermal-events.sh
This PR does the following:
- Fix for the temperature sensor attribute index. Replace
temp_input attribute to temp1_input to match with the
attribute name created by driver in the hwmon directory.
- Thers are voltmonX attributes which were reduntant and
pointing to already created attributes. This commit fixes
- Fix for PSU temperature alarm path
- Change 'psu_temp' attribute name to 'psu_temp1'
- Minor update to labels creation script
> hw-mgmt: Cleanup attributes

- recipes-kernel/linux/linux-5.10/0317-platform-mellanox-Introduce-support-for-switches-equ.patch
- recipes-kernel/linux/linux-6.1/0057-platform-mellanox-Introduce-support-for-switches-equ.patch
Fix mux selector in v5.10 #0317 and v6.1 #0057 patches.
Reviewed-by: Felix Radensky <fradensky@nvidia.com>
> hw-mgmt: patches: Add fix to FPGA patches

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
- Rename pcisw_amb to cx_amb.
- Add CX bus number for BF3 systems.
- Add additional handling for CX ambient temperature link inside COME
- case.
- Fix attribute for thermal path unlink in remove flow.
Reviewed-by: <Oleksandr Shamray oleksandrs@nvidia.com>
Reviewed-by: <Felix Radensky <fradensky@nvidia.com>
> hw-mgmt: thermal: Add link to CX ambient temperature

- usr/usr/bin/hw_management_thermal_control.py
This patch updates the voltmon temperature sensor
attribute name from voltmon_temp_input to
voltmon_temp1_input.
Reviewed-by: Oleksandr Shamray <oleksandrs@nvidia.com>
> hw-mgmt: thermal: Update TC voltmon sensor name

- recipes-kernel/linux/linux-5.10/0312-platform-mellanox-mlx-platform-Add-reset-callback.patch
- recipes-kernel/linux/linux-6.1/0025-platform-mellanox-mlx-platform-Add-reset-callback.patch
Modify patches:
- v5.10 - #0312.
- v6.1 - #0025.
Reviewed-by: Felix Radensky <fradensky@nvidia.com>
> hw-mgmt: patches: Modify reset callback

- usr/usr/bin/hw-management-chassis-events.sh
> hw-mgmt: scripts: add missing temperature links for voltmon on SN2201.

- usr/etc/hw-management-thermal/tc_config_default.json
- usr/etc/hw-management-thermal/tc_config_mqm8700.json
- usr/etc/hw-management-thermal/tc_config_mqm9700.json
- usr/etc/hw-management-thermal/tc_config_msn2010.json
- usr/etc/hw-management-thermal/tc_config_msn2100.json
- usr/etc/hw-management-thermal/tc_config_msn2201.json
- usr/etc/hw-management-thermal/tc_config_msn2700_msb7x00.json
- usr/etc/hw-management-thermal/tc_config_msn3420.json
- usr/etc/hw-management-thermal/tc_config_msn3700.json
- usr/etc/hw-management-thermal/tc_config_msn3700C.json
- usr/etc/hw-management-thermal/tc_config_msn3800.json
- usr/etc/hw-management-thermal/tc_config_msn4410.json
- usr/etc/hw-management-thermal/tc_config_msn4600.json
- usr/etc/hw-management-thermal/tc_config_msn4600C.json
- usr/etc/hw-management-thermal/tc_config_msn4700.json
- usr/etc/hw-management-thermal/tc_config_msn5600.json
- usr/etc/hw-management-thermal/tc_config_not_supported.json
- usr/usr/bin/hw_management_thermal_control.py
On init flow, TC scans available sensors and adds them to DB. Some sensors can be present or not depending on system types. For example sodimm2_temp present not in all systems, and sensors scan will add it only if exists sensor link in sysfs. But if the system should have sodimm2 but it is broken, we will not recognize such an issue.
Static sensor - a sensor that should be added, even if HW is not present or broken. Static sensor list can be added to TC system data JSON file:
"static_sensor_list": ["sodimm2", "sensor_amb", "cpu_pack"]
Bug: #3569409
> hw-mgmt: thermal: Add static sensor support

- usr/etc/modprobe.d/hw-management.conf
Add 'pcspkr'.
Reviewed-by: Ciju Rajan K <crajank@nvidia.com>
> hw-mgmt: kernel modules: Extend list of not allowed modules

- usr/etc/hw-management-thermal/tc_config_mqm9700.json
- usr/etc/hw-management-thermal/tc_config_msn2010.json
- usr/etc/hw-management-thermal/tc_config_msn2100.json
- usr/etc/hw-management-thermal/tc_config_msn2201.json
- usr/etc/hw-management-thermal/tc_config_msn5600.json
- usr/usr/bin/hw_management_thermal_control.py
1. Add drivetemp and ibc sensors support to TC
2. Add voltmon2 sensor to MSN2210 thermal data
> hw-mgmt: thermal: Add drivetemp and ibc sensors support to TC

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/0085-i2c-mlxcpld-Downstream-WA-to-avoid-error-for-SMBUS-r.patch
Add WA patch to avoid errors for read block command. Fix to be removed after CPLD fix for read block.
Reviewed-by: Felix Radensky <fradensky@nvidia.com>
> hw-mgmt: patches; Add WA patch for kernel v6.1

- usr/lib/udev/rules.d/50-hw-management-events.rules
Update udev rules in order to follow new nvme driver hwmon path.
Signed-off-by: Michael Shych <mshych@nvidia.com>
> hw-mgmt: udev: fix broken NVME SSD temp links

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0097-1-mlxsw-Use-u16-for-local_port-field.patch
- recipes-kernel/linux/linux-5.10/0097-2-mlxsw-i2c-Fix-chunk-size-setting.patch
- recipes-kernel/linux/linux-5.10/0097-3-mlxsw-core_hwmon-Adjust-module-label-names.patch
- recipes-kernel/linux/linux-5.10/0098-1-Revert-mlxsw-Use-u16-for-local_port-field.patch
- recipes-kernel/linux/linux-5.10/0098-2-Revert-mlxsw-i2c-Fix-chunk-size-setting.patch
- recipes-kernel/linux/linux-5.10/0098-3-Revert-mlxsw-core_hwmon-Adjust-module-label-names.patch
- recipes-kernel/linux/linux-5.10/0152-mlxsw-i2c-Prevent-transaction-execution-for-spec.patch
- recipes-kernel/linux/linux-5.10/0153-mlxsw-i2c-Add-support-for-system-events-handling.patch
- recipes-kernel/linux/linux-5.10/0186-platform-mellanox-mlxreg-hotplug-Allow-more-flexible.patch
- recipes-kernel/linux/linux-5.10/0274-platform-mellanox-Modify-reset-causes-description.patch
- recipes-kernel/linux/linux-5.10/0285-platform-mellanox-nvsw-sn2201-change-fans-i2c-busses.patch
This patchset fixes the issues with SONiC canonical build.
> hw-mgmt: patches: kernel 5.10: SONiC upstream rebase

- rpm/hw-management.spec
Updating the hw-management rpm spec file to accommodate the removal of 'hw-management-liquid-cooling.sh' script
Reviewed-by: Vadim Pasternak [vadimp@nvidia.com](mailto:vadimp@nvidia.com)
Signed-off-by: Ciju Rajan K [crajank@nvidia.com](mailto:crajank@nvidia.com)
> Fix for Github action script

- usr/usr/bin/hw_management_thermal_control.py
TC - disable autodetect for drivetemp sensor
> hw-mgmt: thermal: TC - disable autodetect for drivetemp sensor

- usr/etc/hw-management-sensors/msn4600c_2_sensors.conf
- usr/usr/bin/hw-management.sh
Add sensors.conf support for msn4600C sysid=2
Reviewed-by: Yehuda Yehudai <yyehudai@mellanox.com>
> hw-mgmt: sensors: Add sensors.conf for msn4600C sysid=2

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
New reset_attr_ready file is created and set to 1 when all reset cause links
for this system are created. It can be used as a trigger in other services
that they can check reset reason.
Signed-off-by: Michael Shych <mshych@nvidia.com>
> hw-mgmt: scripts: add new reset ready attribute.

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Add two new attributes:
/var/run/hw-management/config/asic_chipup_completed /var/run/hw-management/config/asics_init_done
'asic_chipup_completed' carries counter of completed ASIC devices probing.
'asics_init_done' is to be set to one, when 'asic_chipup_completed' attribute matches 'asic_num' attribute.
Motivation is to use 'asics_init_done' as criteria of system infrastructure readiness.
Reviwed-by: Felix Radensky <fradensky@nvidia.com>
Reviwed-by: Michael Shych <michaelsh@nvidia.com>
> hw-mgmt: system events: ASIC init complition done

- recipes-kernel/linux/linux-5.10/0067-platform-mellanox-Add-dedicated-match-for-system-typ.patch
Explain why this patch is needed in v5.10, even there is no plan to up-stream it.
> hw-mgmt: patches: 5.10: Update commit text for patch #0067

- usr/usr/bin/hw_management_thermal_control.py
1. Fix log sensor name for ambient sensor. Add failed file path instead
of just print sensor name
2. Fixed psu fan reading error.
If PSU not present no sense to add sensor_reading error for psu fan
3. Set pwm update worker immediate run only for hight PWM trend
It will make pwm_max_reduction timing more accurate in case several sensors
want to set pwm less pwm_max_reduction each but more than pwm_max_reduction in sum.
> hw-mgmt: thermal: TC code improvement

- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_thermal_control.py
On systems with ASIC FAN control (SPC1), TC will not be able to change PWNM
after ASIC is disabled. To prevent system overheating, added set PWM
to maximum (255) when ASIC state changed to disabled.
Bug: #3586921
> hw-mgmt: thermal: Fix PWM set 255 on ASIC disable

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw_management_thermal_control.py
Set pwm value to default (20%) on hw-management init
> hw-mgmt: scripts: Set pwm value to default on hw-management init

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Add helper function for ASIC hwmon detection.
On some systems, like SN2201 this process can take more time due to slower CPU.
So, make sure that hwmon obecect is exist in chipup flow.
> hw-mgmt: topology: Add helper function to detect ASIC hwmon existence

- usr/usr/bin/hw-management-thermal-events.sh
Change NVME SSD temperature sensor link to unified name "drivetemp" for Composite sensor
and drivertemp_sensor{N} for "Sensor 1,2..."
Reviewed-by: Felix Radensky <fradensky@nvidia.com>
Reviewed-by: Michael Shych <michaelsh@nvidia.com>
> hw-mgmt: scripts: Change NVME SSD temperature sensor link to unified name "drivetemp"

- usr/usr/bin/hw-management-thermal-events.sh
Remove depricated links:
coolingX_cur_state
coolingX_max_state
Since kernel thermal is disabled, we don't need these attributes and
those can be removed
> hw-mgmt: thermal: remove depricated links coolingX_state

- debian/rules
- usr/etc/logrotate.d/udev
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-generate-dump.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
This patch set enables udev event tracing. The logs are captured in /var/log/udev_events.log. It also adds the log rotation support using logrotate command.
> Tracing support for udev events

- usr/etc/hw-management-sensors/msn2010_sensors.conf
- usr/etc/hw-management-sensors/msn2100_sensors.conf
- usr/etc/hw-management-sensors/msn2410_sensors.conf
- usr/etc/hw-management-sensors/msn2700_sensors.conf
- usr/etc/hw-management-sensors/msn2740_sensors.conf
- usr/usr/bin/hw-management.sh
Fix tacho order for whe systems with inversed FAN order
bug: 3560591
> hw-mgmt: fan: Fix tacho order for whe systems with inversed FAN order

- debian/rules
- usr/usr/bin/iorw.sh
This patch adds the following fixes:
1. Modifies output formatting to match X86 version
2. Adds "base" command line parameter for compatibility with X86 version
3. Renames the tool to iorw during package installation to match X86 version
> hw-mgmt: Various fixes for ARM iorw tool

- debian/changelog
- usr/usr/bin/hw-management-thermal-events.sh
Add replacement for kernel tz attributes:
./mlxsw/temp_trip_crit=> ./asic_temp_trip_crit
./mlxsw-module{X}/temp_trip_crit=> ./module{X}_temp_trip_crit
./mlxsw-gearbox{X}/temp_trip_norm => ./gearbox{X}_temp_norm
./mlxsw-gearbox{X}/temp_trip_high => ./gearbox{X}_temp_crit
./mlxsw-gearbox{X}/temp_trip_hot =>  ./gearbox{X}_temp_emergency
./mlxsw-gearbox{X}/temp_trip_crit=> ./gearbox{X}_temp_trip_crit
> hw-mgmt: thermal: Add replacement for kernel tz attributes

- debian/rules
- usr/etc/modules-load.d/05-hw-management-modules-arm64.conf
Some kernel loadable modules for X86 platforms are not available on ARM platforms, this causes errors during module loading time. Create ARM specific version of kernel module configuration file to avoid errors.
Fixes: #3632299
> hw-mgmt: Add ARM version of kernel loadable module config file

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0329-gpio-mlxbf3-Fix-error-message.patch
- recipes-kernel/linux/linux-6.1/0086-gpio-mlxbf3-Fix-error-message.patch
Add 5.10 and 6.1 kernel patches to fix the following error message produced by BF3 GPIO driver:
mlxbf3_gpio MLNXBF33:01: IRQ index 0 not found
Fixes: #3632297
> hw-mgmt: patches: Fix error message produced by BF3 GPIO driver

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-ps-vpd.sh
- usr/usr/bin/hw-management-thermal-events.sh
While the platforms are running in virtual environment, there is some timing issue with loading the i2c traces for PSU and hence the initial reads of PSU attributes are wrong. This is a workaround to fix the issue by not changing the workflow for PSU initialization when creating PSU vpd.
> Fix PSU attribute values for virtual platforms

- usr/lib/udev/rules.d/50-hw-management-events.rules
Remove BF3 udev rules matching I2C address 0x48 with port ambient temperature sensor, as they result in creation of wrong port_amb link. The port ambient temperature sensor is not present on address 0x48 on BF3 based systems.
> hw-mgmt: rules: Fix port_amb symlink on BF3 systems

- usr/usr/bin/hw-management-thermal-events.sh
Add missing replacement for tz attributes
mlxsw/temp_trip_crit
mlxsw-gearbox{}/temp_trip_hot
mlxsw-gearbox{}/temp_trip_crit
Bug: 634579
> hw-mgmt: thermal: Add missing replacement for tz attributes

- usr/usr/bin/hw-management.sh
> Add mlxbf-ptm driver load. This driver implements debugfs interface for sodimm, cpu_core temperature reading on Bluefield systems

- usr/usr/bin/hw_management_thermal_control.py
When adding a new log level, SysLogHandler needs to know to which syslog level it is mapped, otherwise messages printed with the new log level will always be printed as WARNING.
Reference: https://docs.python.org/3/library/logging.handlers.html#logging.handlers.SysLogHandler.mapPriority
This fixes the log level inconsistency for NOTICE messages, such as:
WARNING hw-management-tc: NOTICE - ********************************
WARNING hw-management-tc: NOTICE - Init thermal control ver: v.2.0.1
WARNING hw-management-tc: NOTICE - ********************************
WARNING hw-management-tc: NOTICE - Thermal control state changed
UNCONFIGURED -> RUNNING reason:init
WARNING hw-management-tc: NOTICE - ********************************
WARNING hw-management-tc: NOTICE - Thermal control is running …
> Fix the log level of thermal control NOTICE messages

- usr/etc/modules-load.d/05-hw-management-modules-arm64.conf
- usr/usr/bin/hw-management.sh
Move loading of BF3 specific PTM driver into ARM specific module loading configuration file.
> hw-mgmt: scripts: Move loading of BF3 PTM driver into config file

- usr/etc/hw-management-thermal/tc_config_msn3700C.json
Fixed FAN drwr count for msn3700C system. Was defined: 6, should be: 4
Bug: 3649678
> hw-mgmt: thermal: Fixed TC FAN DRWR number for MSN3700C system

- usr/etc/hw-management-thermal/tc_config_msn3750.json
Fix voltmon2 missing issue on msn3750 system. This system have voltmon1
and voltmon3 sensors (voltmon2 renamed to voltmon 3)
Bug: 3647742
> hw-mgmt: thermal: Fix TC voltmon2 missing issue on MSN3750 system

- usr/usr/bin/hw-management.sh
P4262 should work with new SMBIOS BOM changes and legacy connection table
with current fix is used just if SMBIOS BOM string isn't burned.
> hw-mgmt: scripts: fix 2 eeproms definitions in P4262 system connection table.

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/8007-hwmon-mlxreg-fan-Downstream-Allow-fan-speed-setting-.patch
- recipes-kernel/linux/linux-6.1/8008-hwmon-emc2305-Downstream-Allow-fan-speed-setting-gra.patch
Add patches to allow fan speed setting granularity of 1 PWM for
mlxreg-fan and emc2305 drivers
> hw-mgmt: patches: Add  patches for v6.1

- usr/usr/bin/hw-management-devtree.sh
1. Add new port board type
2. Move port ambient sensor on XDR systems from main to port board
> hw-mgmt: devtree: Add support for port board type

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/8009-hwmon-mlxsw-Downstream-Allow-fan-speed-setting-granu.patch
Add patches to allow fan speed setting granularity of 1 PWM for
mlxminimal driver
> hw-mgmt: patches: Add patches for v6.1

- debian/changelog
- usr/usr/bin/hw-management-chassis-events.sh
This is fix for bug# 3660884
Panther-comex is combined system, it has new CPLD fan control but fan direction
is still should be checked in old way from fan EEPROM.
> hw-mgmt: scripts: fix fan direction setting on Panther-comex system.

- usr/lib/udev/rules.d/50-hw-management-events.rules
Add environment parameter to udev event to distinct between ADD/DELETE events raised from 'sx_core' driver and same events raised because of PCI reset.
In the first case 'minimal' driver should be triggered, while in the second case not.
This additional parameter aims to filter out events raised by PCI reset.
> hw-mgmt: udev events: Add extra parameter for ASIC core driver events

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0330-mlxsw-i2c-Downstream-Add-retry-mechanism-for-failed-.patch
Sometimes I2C transactions could broken or non-completed becasue of some noise on I2C line or because ASIC resources is busy handling big amount of PCIe tarnsactions.
Add re-try mechanism for re-sending transaction which was not properly completed.
Retry up to three times and produce error log only in case the last try is not successful.
> hw-mgmt: patches: 5.10: Add retry mechanism for failed transactions

- usr/usr/bin/hw-management-generate-dump.sh
While running hw-management-generate-dump.sh, if the system is stressed and the file read operations are not completed within the given time interval, timeouts are defined to stop the ongoing read operations. This may generate a warning 'tar: ./hw-management_val: file changed as we read it' while the files are being archived by tar command. This patch increases the timeout intervals and kills all the child process (which are still leftout) before creating the archive.
Bug: 3450086
> hw-mgmt: dump: Avoid file changed message

- recipes-kernel/linux/Patch_Status_Table.txt
Add to the list downstream patch #0098:
Use weak reverse dependencies for firmware flashing selection.
> hw-mgmt: patch table: Update patch table for v5.10

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/8010-mlxsw-i2c-Downstream-Add-retry-mechanism-for-failed-.patch
Sometimes I2C transactions could broken or non-completed becasue of some noise on I2C line or because ASIC resources is busy handling big amount of PCIe tarnsactions.
Add re-try mechanism for re-sending transaction which was not properly completed.
Retry up to three times and produce error log only in case the last try is not successful.
> hw-mgmt: patches: 6.1: Add retry mechanism for failed transactions

- usr/usr/bin/hw-management-thermal-events.sh
Fix driver name check when adding SODIMM thermal sensor
> hw-mgmt: Fix sodimm temp sensor

- usr/usr/bin/hw-management-thermal-events.sh
On QM3400 system, temperature sensors of the first 18 QFSPs are accessible via ASIC1, the rest - via ASIC2.
> hw-mgmt: scripts: Fix generation of QSFP temperature links for QM3400

- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management.sh
Earlier patch that introduced detection of new device categories has used wrong counter variable for each new category. Fix that by adding new counter variable for each new category.
> hw-mgmt: devtree: Fix detection of new device categories

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0332-platform-mellanox-indicate-deferred-I2C-bus-creation.patch
- recipes-kernel/linux/linux-6.1/0087-platform-mellanox-indicate-deferred-I2C-bus-creation.patch
This is fix for bug# 3650418
It fixes timing issue when during initialization hot-plug driver
attempts to attach a component to I2C bus, which is still not created.
Setting deferred bus parameter will force hot-plug driver to wait
until the bus is available.
> hw-mgmt: patches 5.10 & 6.1: indicate deferred I2C bus creation for a hot-plug driver on SN2201

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
Add name resolving based on names defined in BOM devtree.
If i2c device is defined in devtree, then will be used its name.
We have such a name resolving for voltmon. This commit adds also
support for eeprom and thermal sensor devices.
For back compatibility, in case if sensor name is not defined
in devree, then will be used "old style" naming from udev rules.
> hw-mgmt: devtree: Set dev name based on BOM devtree name

- recipes-kernel/linux/Patch_Status_Table.txt
Add 2 downstream patches to patch table:
8001-platform-mellanox-Downstream-Add-dedicated-match-for.patch
8002-platform-mlx-platform-Downstream-Add-SPI-path-for-ra.patch
> hw-mgmt: patches: 6.1: add patches to patch table

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/9003-i2c-mux-reg-Add-delay-after-channel-select.patch
Add delay to I2C mux driver channel selection routine to mitigate HW problem on XDR systems.
> hw-mgmt: patches: Add temporary mux driver patch to WA HW problem

- usr/usr/bin/hw-management-generate-dump.sh
Perform dump of sensors prior to journal dump.
> hw-mgmt: dump: Move output of sensors to the dump start

- debian/changelog
- usr/usr/bin/hw-management.sh
XDR systems support only reverse fan direction, system_flow_capability attribute is required by TC on systems with single flow direction.
> hw-mgmt: scripts: Add system_flow_capability attribute for XDR systems

- usr/usr/bin/hw_management_thermal_control.py
TC fix FAN_dir error for systems with one possible FAN direction
> hw-mgmt: thermal: TC fix FAN_dir error for systems with one possible FAN direction

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-ready.sh
- usr/usr/bin/hw-management.sh
This patch set adds more platforms to SimX support. Also it re-organizes the check_simx() function to take the list of platforms from a single variable. It also enables the TC explicitly for SimX platforms.
Bug #3696439
> hw-mgmt: scripts: Update SimX supported platforms

- debian/changelog
- usr/usr/bin/hw-management-helpers.sh
This patch fixes the wrong variable which was used for checking the platform sku when running in the SimX environment.
> hw-mgmt: scripts: Fix sku variable for SimX check

- usr/usr/bin/hw-management.sh
Change hw-management to use tc_config copy instred of soft link
3706219
> hw-mgmt: thermal: use tc_config copy instred of soft link

- debian/changelog
- usr/usr/bin/hw-management-thermal-events.sh
In SimX environment asic_health is 3. This will cause the minimal driver not to load. This patch will probe minimal always and run chipup only for those with good health.
> hw-mgmt: scripts: Fix asic health attribute

- debian/changelog
- recipes-kernel/linux/linux-5.10/0328-platform-mellanox-mlx-platform-Add-support-for-new-X.patch
Add missing tacho speed divider and remove unsupported fan PWM features.
> hw-mgmt: patches: 5.10: Update Mellanox platform driver XDR patch

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/9004-DS-OPT-mlxsw-minimal-Downstream-Disable-ethtool-interface.patch
Add temporary mlxsw_minimal driver patch to disable ethtool interface
> hw-mgmt: patches: 5.10: Add temporary mlxsw_minimal driver patch

- usr/etc/hw-management-sensors/mqm9700_rev1_sensors.conf
- usr/etc/hw-management-sensors/mqm9700_sensors.conf
PSUs on MQM9700 systems occasionally report errors for FAN2 and FAN3 although only FAN1 exists. Ignore FAN2 and FAN3 to avoid errors.
> hw-mgmt: sensors: ignore PSU fan2, fan3 on MQM9700 systems.

- usr/usr/bin/hw-management-thermal-events.sh
1. Fix long ASIC init time in special CI/verification OSes
2. Fix generation of OFSP module temperature sensor symlinks
> hw-mgmt: scripts: Fix ASIC init issues on XDR systems

- usr/etc/hw-management-sensors/e3597_sensors.conf
- usr/etc/hw-management-sensors/mqm9510_sensors.conf
- usr/etc/hw-management-sensors/mqm9520_sensors.conf
- usr/etc/hw-management-sensors/msn27002_sensors.conf
- usr/etc/hw-management-sensors/msn3420_sensors.conf
- usr/etc/hw-management-sensors/msn4800_sensors.conf
- usr/etc/hw-management-sensors/msn4800_sensors_lc.conf
- usr/etc/hw-management-sensors/p4697_sensors.conf
- usr/etc/hw-management-sensors/qm3000_sensors.conf
- usr/etc/hw-management-sensors/qm3400_sensors.conf
- usr/etc/hw-management-sensors/sn2201_sensors.conf
- usr/etc/hw-management-sensors/sn5600_sensors.conf
PSUs on multiple systems occasionally report errors for FAN2 and FAN3 although only PSU FAN1 exists. Ignore PSU FAN2 and FAN3 to avoid errors.
Fixes: #3723906
> hw-mgmt: sensors: Ignore PSU fan2, fan3 on multiple systems.

- usr/etc/hw-management-sensors/qm3000_sensors_labels.json
- usr/etc/hw-management-sensors/qm3400_sensors_labels.json
Correct the names for temperature sensors in the json file to match with the new naming format.
> hw-mgmt: scripts: ui: Fix naming for sensors

- usr/etc/hw-management-thermal/tc_config_msn5400.json
- usr/etc/hw-management-thermal/tc_config_qm3000.json
- usr/etc/hw-management-thermal/tc_config_qm3400.json
Add PSU [present, direction] error mask flag option for systems:
- SN5400
- QM3000
- QM3400
> hw-mgmt: thermal: Add PSU mask flag option

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
Generate ASIC temperature and ASIC hwmon symlinks for each ASIC on XDR systems.
> hw-mgmt: scripts: Add ASIC temperature symlinks for XDR systems

- usr/etc/hw-management-sensors/qm3000_sensors.conf
- usr/etc/hw-management-sensors/qm3400_sensors.conf
Ignore temp2 sensors on MP2891 VRs where these sensors are not connected.
> hw-mgmt: sensors: Update sensor configs for XDR systems

- usr/etc/hw-management-thermal/tc_config_qm3000.json
Fix TC system name in qm3000 thermal data
"qm3400" changed to "qm3000"
> hw-mgmt: thermal: Fix TC system name in qm3000 thermal data

- debian/control
Update HW-MGMT package dependency list.
Add: xxd, lm-sensors, libiio-utils, dmidecode, i2c-tools
> hw-mgmt: pickage: Update HW-MGMT package dependency list

- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
Add BF3 DPU to SMBIOS BOM.
Add AMD Comex to SMBIOS BOM.
Generalization of multiple boards processing.
Code clean.
> hw-mgmt: scripts: add DPU and Comex AMD to SMBIOS BOM plus improvements.

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
Add list of supported PSU PN to extract fan direction.
> hw-mgmt: thermal: Add list of supported PSU PN to extract fan direction.

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Make several attempts to probe for I2C devices if
initial probe fails.
> hw-mgmt: scripts; Add device probe retry support

- usr/usr/bin/hw-management.sh
This commit removes the non-existent come devices
on i2c-15 and i2c-16 for the smart switch SN4280.
> hw-mgmt: scripts: Fix smart switch come sensors

- usr/etc/hw-management-thermal/tc_config_msn27002.json
Remving voltmon6 entry from thermal profile for MSN27002. This will fix the error "ERROR - voltmon6_temp: read file thermal/voltmon6_temp1_input errors count 7'.
Bug #3726901
> hw-mgmt: thermal: Remove non existent sensor

- debian/changelog
- usr/usr/bin/hw-management-thermal-events.sh
> hw-mgmt: scripts: fix missing psu config attributes on SN5400

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Add creation of devices on dynamic boards according to SMBIOS BOM data.
Fix: don't use add_i2c_dynamic_bus_dev_connection_table with SMBIOS BOM data.
> hw-mgmt: scripts: Add dynamic boards to SMBIOS BOM mechanism.

- usr/etc/hw-management-thermal/tc_config_sn4280.json
Update thermal data for smart switch: removed DPS voltmon from TC monitoring
> hw-mgmt: thermal: Update thermal data for smart switch

- usr/etc/hw-management-thermal/tc_config_qm3000.json
- usr/usr/bin/hw_management_thermal_control.py
Add support for voltmon thermal sensors located on swb*.
New names for sensors: swb*_voltmon
> hw-mgmt: thermal: TC add voltmon swb* support

- debian/changelog
- usr/etc/hw-management-sensors/sn5600_sensors.conf
> hw-mgmt: sensors: fix labels for sensors output on SN5600/SN5400 systems.

- usr/usr/bin/hw-management.sh
Run "udevadm settle" after "udev trigger" to make sure that all udev events are handled before proceding with hw-management initialization. This fixes device initialization issues on XDR and BF3 platforms.
> hw-mgmt: scripts: Add wait for udev to complete device initialization

- usr/usr/bin/hw-management-chassis-events.sh
The pattern dpu*_ready in hotplug action script was causing both dpu[1-8]_ready and dpu[1-8]_shtdn_ready events to execute the dynamic sensor loading function. The problem was that the wild card character '*' was redirecting dpu*_shtdn_ready events to dpu*_ready case, because it ends with '_ready'. This patch fixes this problem by having the dpu slot numbers in the pattern checking, there by avoiding the '*' wild card character.
> hw-mgmt: scripts: Fix dpu_shtdn action script

- usr/usr/bin/hw-management-chassis-events.sh
Introducing a check for dpu_ready and dpu_shtdn_ready events to see if the udev events are valid and then only
connect / disconnect dynamic sensors.
> hw-mgmt: scripts: Check for dpu events

- usr/usr/bin/hw-management-thermal-events.sh
For PSU on udev event we have a delay 2 sec which is needed to
allow PSU controller to stabilize. This delay of 2 sec can be too much.
In this change, we replaced constant delay to PSU attribute polling,
which can help us to get the exact time when PSU is ready and reduce
wait time for PSU attributes init.
> hw-mgmt: infra: Optimize PSU init time

- recipes-kernel/linux/linux-5.10/0333-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
- recipes-kernel/linux/linux-6.1/0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
Fix the mlxreg-dpu attribute polarity for dpu pg/health events.
> hw-mgmt: patches: Fix DPU event polarity

- usr/lib/udev/rules.d/50-hw-management-events.rules
In virtual machines based on qemu, the jc42 driver attributes are located in a different path. It is not in the path /sys/devices/pci0000:00. So the sodimm sensor attributes were not created in /var/run/hw-management/thermal directory. This patch fixes this issue by adding a udev rule with the correct path for jc42 attributes on virtual platforms.
> hw-mgmt: scripts: Fix udev event path for sodimm

- usr/usr/bin/hw-management.sh
This patch introduces the pci bus to dpu slot number mapping. PCI buses can be different for CFL and AMD cpu comex. This also introduces a new config variable 'dpu_detected_num' which will tell the number of DPUs detected by lspci command.
> hw-mgmt: scripts: Mapping pci bus number to dpu slot

- usr/etc/hw-management-sensors/sn5600_sensors.conf
Add power2_cap setting for 2nd PSU.
By some reason this attribute is reported just on PSU address 0x5a.
It's better add for consistency also for PSU address 0x59.
Related commit: dd733a03cdaff88cbdf1a23f4e3a4eabb550f30c
> hw-mgmt: sensors: Add sensorss config rule for 2nd PSU in sn5600/sn5400 systems.

- recipes-kernel/linux/linux-5.10/0334-platform-mellanox-Introduce-support-of-Nvidia-smart-.patch
Add non_active_bios_select attribute.
Delete bios_authentication_failure attribute
Change access to bios_upgrade_failure attribute.
> hw-mgmt: kernel 5.10: update smartswitch regmap.

- usr/usr/bin/hw-management-chassis-events.sh
For the systems, with FANs equiped with FRU EEPRM fan_direction attr
value can be extracted from FRU PN field. If PN is not in MLNX
format (MTEF-FANR-A) or broken - not possible to get fan_direction
and fanX_dir attribute not crating.
With this fix added fan direction value == 2, which means "FAN
direction can't be extracted"
> hw-mgmt: scripts Fix FAN dir attribute for PN in none-MLNX format

- usr/usr/bin/hw_management_thermal_control.py
sensor_read_err => sensor_read_error
> hw-mgmt: thermal: TC fix "sensor missing error" display name. To be consistant with thermal table data, changed "sensor missing error" displayed name.

- usr/usr/bin/hw-management-vpd-parser.py
Fix vpd parser MAC display issue. In case if BASE_MAC/BASE_GUID data starting
with 0x0{X} and ends with 0x{X}0 BASE_MAC1 field decoding into 5-byte length
instead of 6-byte.
Was:
BASE_MAC_1:              43:f7:08:9a:5c
BASE_GUID_1:             43:f7:20:30:08:9a:5c
Fixed:
BASE_MAC_1:              04:3f:72:89:a5:c0
BASE_GUID_1:             04:3f:72:03:00:89:a5:c0
Bug: 3825753
> hw-mgmt: scripts: Fix vpd parser MAC display issue

- usr/usr/bin/hw-management-vpd-parser.py
Add to vpd parser support for up to 4 GUID blocks (was up to 2)
Iadd hidden option "verbose" to vpd parser.
> hw-mgmt: scripts: Add support for 4 GUID blocks to vpd parser

- usr/usr/bin/hw-management.sh
MSN3420 sensors config symlink was pointing to MSN3700 config file.
> hw-mgmt: sensors: Fix symlink of MSN3420 sensors config file

- usr/etc/hw-management-thermal/tc_config_qm3400.json
This commit removes the non existent ctx_amb ConnectX thermal sensor from the TC configuration.
Bug #3847931
> hw-mgmt: thermal: Update system profile for QM3400

- usr/etc/hw-management-thermal/tc_config_qm3000.json
This commit makes the following changes:
1. Removes non existent ctx_amb ConnectX-8 sensor
2. Adds missing SODIMM2 sensor
3. Fixes typo in ASIC3 sensor name
> hw-mgmt: thermal: Update system profile for QM3000

- usr/etc/hw-management-thermal/tc_config_jso.json
- usr/usr/bin/hw_management_thermal_control.py
1. Add "hotswap" and "bmc" TC sensor support
> hw-mgmt: thermal: Add "hotswap" and "bmc" TC sensor support

- usr/etc/hw-management-sensors/mqm9520_sensors.conf
- usr/etc/hw-management-sensors/msn4700_sensors.conf
Some some PSU1 labels for MSN4700 and MQM9520 are
incorrectly marked as PSU2.
> hw-mgmt: sensors: Fix some misnamed PSU labels

- debian/changelog
- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/9006-mlxsw-core_hwmon-Downstream-Fix-module-sensor-number-for-QM3200.patch
- recipes-kernel/linux/linux-6.1/9006-mlxsw-core_hwmon-Downstream-Fix-module-sensor-number-for-QM3200.patch
Add downsteam mlxsw minimal driver patch to hardcode the number of modules per ASICs on QM3200 systems instead of reading the actual number of modules from the MGPIR register. This is a WA for recent FW versions that incorrectly report the number of modules per ASIC.
> hw-mgmt: patches: Add downstream mlxsw minimal driver patch

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/deploy_kernel_patches.py
Add 'nvos' type for --os argument patch_deploy_tool
> hw-mgmt: patches: Add nvos type for --os argument patch_deploy_tool

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/deploy_kernel_patches.py
Add 'dvs' type for --os_type argument patch_deploy_tool
> hw-mgmt: patches: Add dvs type for --os_type argument patch_deploy_tool

- usr/usr/bin/hw_management_thermal_control.py
Fix issue when TC counts errors even it was paused by black list.
Bug: 3885405, 3883147
> hw-mgmt: thermal: Fix "blacklist is malfunction issue"

- usr/etc/hw-management-thermal/tc_config_msn3420.json
On FANs which have HW degradation and minimal PWM set (20%) - FAN rotation
speed can be lower than minimual. It can cause fan_fail sataus.
This commit fixed issue by set minmal PWM to 25%.
Bug: 3879220
> w-mgmt: thermal: fixed of sporadically FAN fail issue on msn3410

- README.md
- debian/changelog
- debian/control
- debian/rules
Set lm_sensor dependency as selectable parameter
To build deb package without lm_sensor dependecy (for Sonic-based OS)
run 'debuild --set-envvar=LM_DEPENDS=0 -us -uc'
or 'export LM_DEPENDS=0 && dpkg-buildpackage -us -uc -b'
Bug: 3895891
> hw-mgmt: package: Set lm_sensor dependency as selectable parameter

- usr/usr/bin/hw_management_thermal_control.py
Most systems have 2 amb thermal sensors. But some can have more or less.
In this case TC amb sensor should handle only existing (predefined in TC config) phisical
amb_{X} sensors.
This commit add fix for TC abm thermal sensor PWM calculation for systems with amb_{X} count  != 2
> hw-mgmt: thermal: TC fixed amb sensor handling for vaious sensor count

- recipes-kernel/linux/Patch_Status_Table.txt
Commit 2ec3e6ec633d792449bfb7044fccbf7d40dd43f3 accidentally removed a patch from 6.1 patch table that makes minimal driver work correctly on Q3200 systems with latest ASIC FW. This commit re-adds the missing patch.
Fixes: #3900159, #3900138
> hw-mgmt: patches: Re-add downstream minimal driver patch for kernel 6.1

- usr/usr/bin/hw-management-chassis-events.sh
vin/vin1 -> voltmon_in1_input
vout/vout1 -> voltmon_in2_input
vout2 -> voltmon_in3_input
iin/iin1 -> voltmon_curr1_input
iout/iout1 -> voltmon_curr2_input
iout2 -> voltmon_curr3_input
pin/pin1 -> voltmon_power1_input
pout/pout1 -> voltmon_power2_input
pout2 -> voltmon_power3_input
> Fix sensors linking by their labels for all voltmon sensors

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-devtree-check.sh
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
- hw-mgmt: scripts & udev: Add handling of AMD Epyc3000 CPU temperature.
- hw-mgmt: udev: Change trigger rules for SODIMMs temp sensors.
- hw-mgmt: scripts: fix devtree voltmon description on AMD comex.
- hw-mgmt: scripts: Add process SODIMM temp sensors events on AMD Epyc3000 CPU.
- hw-mgmt: scripts: add jtag configs for AMD CPU based systems.
- hw-mgmt: scripts: tempory code for testing AMD Comex on old systems. Should be reverted later.
- hw-mgmt: scripts: Add SODIMM temp sensors init on AMD Epyc3000 CPU.
> V.7.0040.1000 BR

- usr/usr/bin/hw-management-devtree-check.sh
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management.sh
1. Fix pdb_eeprom name on N5110 to be aligned with name on other systems pdb_info => pdb_eeprom
2. Fix gpio export/unexport on hw-mgmt stop.
> hw-mgmt: scripts: Fix gpio export/unexport. Fix pdb_eeprom name

- usr/usr/bin/hw_management_thermal_control.py
Add special configuration for sensor_read_error. It can be used for
ASIC thermal sensor read error which requires higher PWM value, compared
to value defined in dmin sensor_read_error table.
Minor fix: align outut style of sensor_error log messages.
> hw-mgmt: thermal: TC: Add special configuration for sensor_read_error

- usr/usr/bin/hw-management-vpd-parser.py
Fix vpd parser sanity check for none 'MLNX' fru
> hw-mgmt: scripts: Fix vpd parser sanity check

- usr/usr/bin/hw-management-generate-dump.sh
Fix debug dump for file values/eeprom. It cause switch
freezing after generating hw-mgmt dump few times in row
Bug: 3948113
> hw-mgmt: dump: Fix debug dump for file values/eeprom

- usr/usr/bin/hw-management.sh
Add i2c_asf driver load for n5110_LD system
> hw-mgmt: topology: n5110ld: Fix asf driver load.

- usr/usr/bin/hw-management.sh
In N5110-LD statem, FANs are not hot plug. Value in otplug_fans attribute
should be 0 (zero).
> hw-mgmt: topology: n5110ld: Fix hotplug_fans

- recipes-kernel/linux/linux-5.10/0334-platform-mellanox-mlx-platform-Fix-FAN-tacho-reading.patch
- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9005-platform-mellanox-Downstream-Add-dedicated-match-for.patch
Update kernel patches for n5110
1. Change "leakage_rope" to "leakage" sensor name
2. Add missing erot sttributes "erot_ap", "erot_reset"
> hw-mgmt: patches: Update kernel patches

- usr/usr/bin/hw-management-vpd-parser.py
Add to vpd parser support for up PSIID block.
This block contain string record up to 32 bytes length
> hw-mgmt: scripts: Add support for PSID block to vpd parser

- usr/usr/bin/hw-management-vpd-parser.py
In case if onie "Base MAC Address" filed ends with zero byte - vpd-parser
cut last byte in output.
Fixed issue.
Before:
Base MAC Address:        b0cf0e0b5a
After:
Base MAC Address:        b0cf0e0b5a00
> hw-mgmt: scripts: Fix vpd-parser with ONIE MAC decode

- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
Fix r/w attributes for bmc_to_cpu_ctrl (N5110_LD).
0200 => 0644
> hw-mgmt: patches: Fix r/w attributes for bmc_to_cpu_ctrl (N5110_LD)

- debian/changelog
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
DPU hotplug events were not updated correctly
in /var/run/hw-management/dpu[1-4]/events directory during a reboot or hw-mgmt restart. This commit
fixes the issue.
> hw-mgmt: scripts: Fix hotplug events from DPU

- usr/etc/hw-management-thermal/tc_config_default.json
- usr/usr/bin/hw_management_thermal_control.py
Disable auto add asic sensors to monitoring. Add ASIC thermal sensors only if it defined in TC thermal data .json
> hw-mgmt: thermal: TC: disable auto add asic sensors to monitoring

- usr/etc/modprobe.d/hw-management-arm64.conf
- usr/etc/modprobe.d/hw-management.conf
Prevents systemd-networkd from loading WIFI core driver and causing a bunch of errors showing up in the logs.
> hw-mgmt: kernel modules: Blacklist WIFI core driver

- usr/usr/bin/hw_management_thermal_control.py
TC was expecting the voltmon temperature sensor attribute from dpu as dpu_voltmon[1-2]_temp1_input. This commit removes the 'dpu' prefix.
> hw-mgmt: thermal: Correct DPU voltmon sensor attribute

- usr/usr/bin/hw-management.sh
The reset from carrier reset attribute was removed. So updating the total number of reset reasons to 17.
> hw-mgmt: scripts: Update the reset attribute count for SN4280

- debian/changelog
- recipes-kernel/linux/linux-5.10/0335-platform-mellanox-Introduce-support-of-Nvidia-smart-.patch
- recipes-kernel/linux/linux-6.1/0092-platform-mellanox-Introduce-support-of-Nvidia-smart-.patch
- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_thermal_control.py
1) This patch removes the reset_from_carrier reset reason as it is asserted for every power cycle and watchdog reboots.
Bug #3981606
2) Correct DPU voltmon sensor attribute
3) Update the reset attribute count for SN4280
> Update SN4280 platform driver

- usr/usr/bin/hw-management-devtree.sh
Fix fan_amb sensor name. Remove redundant ","
fan_amb, -> fan_amb
Bug: 3988849
> hw-mgmt: topology: n51xx: Fix fan_amb sensor name

- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9005-platform-mellanox-Downstream-Add-dedicated-match-for.patch
> hw-mgmt: patches: kernel 5.10/6.1: Fix N51XX platform patch Reduce (remove unused) regio attributes to not exeed maximum (96)

- usr/usr/bin/hw_management_redfish_client.py
- usr/usr/bin/hw_management_sync.py
Add to hw-management-sync service support for synchrinize BMC thermal sensor
from BMC to CPU board.
Sync working over the Redfish protocol.
> hw-mgmt: scripts: Add BMC sync to CPU for BMC sensor

- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management.sh
Fix misprint in COMEX i2c offset init for n51xx
Bug #4004253
> hw-mgmt: topology: Fix for n51xx COMEX i2c offset init

- usr/usr/bin/hw-management-chassis-events.sh
Due to the usage of wildcards in udev rules, the dpu directories were getting created on most of the platforms where DPUs are not present. This patch fixes it by having a check for hw sku, before creating the dpu directories. There by limiting it to only DPU platforms.
The problematic udev rule is with DPU topology creation DEVPATH=="/devices/platform/mlxplat/i2c_mlxcpld.*/i2c-*/i2c-*/*-0068"
This one gets triggered for voltage monitors with address 0x68. Having a sku check will prevent it.
Bugs #4001444
> hw-mgmt: scripts: Fix invalid dpu entry

- debian/changelog
- recipes-kernel/linux/linux-5.10/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/sonic/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-6.1/0048-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
This patch fixes the issue while shifting the bits in pmbus register 0xBD. A right shift of 14 bits
would make the value as 0 and the check for BIT(13) will always fail. This was causing the wrong scale value of 5mv to be used (instead of 2.5mv) for vou2.
Bug #3962952
> hw-mgmt: patches: Correct mp2891 voltage scaling

- debian/hw-management.hw-management.service
Add to hw-management service start/stop synchronisation with hw-mgmt-sync.service
hw-mgmt stop -> hw-mgmt-sync stop
hw-mgmt stuart -> hw-mgmt-sync start
> hw-mgmt: service: Add start/stop for sync service when hw-mgmt start/stop

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
The fanX_speed_tolerance attribute is defining how mutch FAN RPM can be different
from expected max/min. Value defined in percent.
Example:
fan1_max = 10000
fan1_speed_tolerance = 15
In this case, range 8500..12000 is considered as normal.
> w-mgmt: scripts: Add fanX_speed_tolerance attribute

- usr/lib/udev/rules.d/76-hw-management-bmc.rules
Add rules for plugin/plugout USB net interface connecting CPU host and BMC.
> hw-mgmt: rules: Add rules for network interface

- recipes-kernel/linux/Patch_Status_Table.txt
Make fix for Makefile for Cumulus/SOnic version of
0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
Mark accepted bugfixes.
> hw-mgmt: patches: v6.1: Add alternative patch

- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_thermal_control.py
In case hw-mgmgt running on unknown platform - TC should
treat it as "Unsupported platform".
Bug 4032775
> hw-mgmt: thermal: TC fix crash for unsuppotred platform

- usr/usr/bin/hw-management-ready.sh
- usr/usr/bin/hw-management.sh
Fix SKU/platform reading if it's not exists. This can be when running on
SimX platform.
log messages example before fix:
/usr/bin/hw-management.sh: line 61: /sys/devices/virtual/dmi/id/board_name: No such file or directory
/usr/bin/hw-management.sh: line 62: /sys/devices/virtual/dmi/id/product_sku: No such file or directory
/usr/bin/hw-management-helpers.sh: line 325: /var/run/hw-management/events/: Is a directory
> hw-mgmt: scripts: Fix init error fox SimX paltform

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-thermal-events.sh
This PR has two commits:
1)  hw-mgmt: scripts: Cleanup dpu sensor attributes
In the event of dpu[1-4]_shtdn_ready signal, dpu
sensor attributes under /var/run/hw-management/dpu[1-4]
directories in the folders alarm, thermal, environemnt
were not removed. This commit remove these stale entries.
Bugs #3995269
2) hw-mgmt: scripts: Fix psu fan dir for virtual environment
Psu fan direction attribute was missing from virtual
platforms. This commit adds this support.
Bugs #3851470
> hw-mgmt: scripts: Cleanup dpu sensor attributes

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
This commit does the following:
- Connect the DPU sensors only if DPUs are powered on
- Remove the 'dpu_detected_num' config variable
- Remove the pci addresses of DPUs from config folder
Bugs #4037464
> hw-mgmt: scripts: Support for DPU dark mode

- debian/changelog
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
This PR takes the following commits to V.7.0040.1000_BR
1)
commit 84e39de609eb3b2a77f39990e1c912e47321c67b
Author: Ciju Rajan K <crajank@nvidia.com>
Date:   Thu Aug 22 09:00:23 2024 +0300
Update changelog to V.7.0040.1011
2)
commit 4ecc77278ca169c9fa983df8422420fa1f20a93c
Author: Ciju Rajan K <crajank@nvidia.com>
Date:   Wed Aug 21 09:29:02 2024 +0300
hw-mgmt: scripts: Support for DPU dark mode
This commit does the following:
- Connect the DPU sensors only if DPUs are powered on
- Remove the 'dpu_detected_num' config variable
- Remove the pci addresses of DPUs from config folder
Bugs #4037464
3)
commit e465cc3d87545d55eef91bb01d477cdc2fab5f02
Author: Ciju Rajan K <crajank@nvidia.com>
Date: …
> DPU related commits

- usr/usr/bin/hw_management_thermal_control.py
In while loops like:
end = current_milli_time() + delay
while end > current_milli_time():
do_somthing()
We potentially can get incorrect delay in case if during loop system
time will be changed. It happens because current_milli_time() based on system time
and this time can be forwarded or rewinded.  To fix this issue - it needs to
change current_milli_time to time which can't be changed, like: system uptime,
application uptime etc.
This fix changing current_milli_time() to read CLOCK_PROCESS_CPUTIME_ID
(High-resolution per-process timer from the CPU) timer as reference.
Bug #4042294
> hw-mgmt: thermal: TC fix timer for while loops based on current system time

- usr/etc/modules-load.d/05-hw-management-modules.conf
- usr/usr/bin/hw-management.sh
Fix issue "Failed to insert module 'coretemp': No such device".
Module 'coretemp' doesn't support AND CPU.
Bug: 4042338
> hw-mgmt: scripts: Fix coretemp module insert  on AMD systems

- usr/usr/bin/hw_management_thermal_control.py
Change TC log mesage type to "Warning" instead of "Info". This message used
for unexpected thermal value warnings
Bug: #4050264
> hw-mgmt: thermal: TC change log message 'info' to 'warning'

- usr/etc/hw-management-thermal/tc_config_msn5400.json
- usr/etc/hw-management-thermal/tc_config_msn5600.json
Add SN5400 support for forward air flow direction.
> hw-mgmt: thermal: Add SN5400 support for forward air flow direction

- recipes-kernel/linux/Patch_Status_Table.txt
Update the description of 5.10 BF3 patches to be aligned with 6.1
> hw-mgmt: kernel: 5.10: Update the description of BF3 patches

- recipes-kernel/linux/linux-5.10/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/dvs/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/nvos/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/opt/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/sonic/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-6.1/0048-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
Fixing the wrong calculation in mp2891 for VOUT
thresholds.
> hw-mgmt: patches: Update mp2891 threshold limits

- usr/usr/bin/hw_management_sync.py
Fix hw-management-sync crash on BMC redfish fail
Bug: 4075088
> hw-mgmt: scripts: Fix hw-management-sync crash

- usr/usr/bin/hw-management-thermal-events.sh
Add missed asic thermal attributes for multi-asic systems.
Added:
$tpath/asic{N}_temp_trip_crit
$tpath/asic{N}_temp_emergency
$tpath/asic{N}_temp_crit
$tpath/asic{N}_temp_norm
> hw-mgmt: scripts: Add missed asic thermal attributes for multi-asic systems

- usr/lib/udev/rules.d/50-hw-management-events.rules
SDK raises KOBJ_OFFLINE prior entering ISSU.
Add this event to UDEV rules for removing minimal driver before ISSU is activated.
sxd_kernel: sending UDEV event from sx-core driver [bus=0000:07:00.0, action=5 (KOBJ_OFFLINE), origin='ISSU notification'] kernel: [ 3930.396462] sxd_kernel: ISSU FW DONE.
kernel: [ 3930.397867] mlxsw_minimal 2-0048:
HW semaphore is not released -> after ISSU FW DONE kernel: [ 3930.404402] mlxsw_minimal 2-0048:
Cmd exec failed
(opcode=40(ACCESS_REG),opcode_mod=0,in_mod=0,status=27(*UNKNOWN*))
Fixes: https://redmine.mellanox.com/issues/4063285
> hw-mgmt: udev rules: Add OFFLINE rule for SDK

- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
Backport kernel 5.10 patch of nvsw-sn2201 contained incorrect reset cause
that didsn't correspond to HW CPLD description and to Linux kernel upstream.
Change reset_aux_pwr_or_ref to reset_aux_pwr_or_fu.
> hw-mgmt: patches: change reset cause of SN2201 in 5.10 backport patch.

- recipes-kernel/linux/linux-5.10/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/dvs/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/nvos/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/opt/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/sonic/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
In 5.10 kernel, mp2891 driver was not initialized. It was due to a corrupted patch. Fixing the patch.
Bugs #4048801 #4082431
> hw-mgmt: patches: Fixing mp2891 driver loading

- usr/usr/bin/hw-management.sh
Since SimX doesn't support CPU core temp emulation - disables 'coretemp'
module load in case of running on SimX
Bug: 4093394
> hw-mgmt: scripts: Fix power coretamp module load on SimX

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/8012-hwmon-pmbus-Downstream-Workaround-for-psu-attributes.patch
Starting from kernel 5.12.rc-1, pmbus reads are always forced down to chip and get the values directly. Driver doesn't cache the values anymore.
This behviour change has caused problems in Delta-1.1K PSUs, on which pmbus registers were not written.
This patch introduces the driver caching.
Bugs# 3874682
> hw-mgmt: kernel: 6.1: Fix for PSU attributes

- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
Fix for power button reset cause – reset cause should be
“reset_pwr_button_or_leak_con”.
Required fix in CPU - renaming:
“reset_leak_con” -> “reset_pwr_button_or_leak_con”.
Until we don’t have this fix, reset cause will be exposed as “reset_leak_con”.
> hw-mgmt: patches: kernel 5.10/6.1: N51xx fix for power button reset cause

- usr/usr/bin/hw_management_sync.py
If asic/module sensor files already created and it's a soft link - skip
updating it
> hwmgmt: scripts: Skip asic/module sensor value update

- usr/etc/hw-management-sensors/sn5600_sensors.conf
SN5600 uses reverse (C2P) fans, so fan side temperature sensor is at air exhaust side and port side sensor is at air intake side.
> hw-mgmt: sensors: Fix temperature sensor descriptions for SN5600

- usr/etc/hw-management-sensors/msn4600c_2_sensors.conf
Update the sensor configuration with correct fan
names.
Issue #4124359
> hw-mgmt: sensor: Correct fan names for MSN4600

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-start-post.sh
Add fix for N5xxx with new power converter
> hw-mgmt: config: Add fix for N5xxx with new power converter

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/9007-mlxsw-core-Downstream-Fix-uninitialized-variable.patch
mlxsw: core: Downstream: Fix uninitialized variable
Set variable "status" to zero in function mlxsw_cmd_exec() to prevent garbage value to be passed from underling functions.
In case of transaction failure due to some hardware problem, uninitialized 'status' may be returned with some garbage value. This garbage can be interpreted as some special status, like MLXSW_CMD_STATUS_FW_ISSU (0x27) or MLXSW_CMD_STATUS_RUNNING_RESET (0x26).
Such codes are considered by the driver as a special flow, which is ended up with driver removing.
When such code is received - all the next transactions to ASIC are blocked.
In case this code is received unintentionally, driver will stop control PWM and stop monitor ASIC and receivers’ sensors and system may end up with thermal shutdown.
> hw-mgmt: patches 6.1: Add patch to fix uninitialized variable

- usr/usr/bin/hw-management.sh
CPLD update on AMD-based systems is done through the LPC CPLD interface.
So, GPIOs for JTAG are not relevant and shouldn't be initialised.
Bug: 4116810
> hw-mgmt: scripts: fix init errors of GPIOs for JTAG on AMD based systems.

- usr/usr/bin/hw_management_sync.py
Fix missing endline character in ./thermal/asic1.
Added '\n' at end of file
Bug SW #4172888
> hw-mgmt: topology: Fix missing endline character in ./asic1

- usr/usr/bin/hw_management_thermal_control.py
Fix log message "Write PSU1 PWM 80". Add log only in case PSU is
present. Prevously it was printed even if PSU is out.
This issue related only to TC logging system.
> hw-mgmt: thermal: TC Fix log for PSU pwm update

- usr/usr/bin/hw-management-devtree.sh
Add devtree support for lm90, tmp411 temperature sensors
Bug: 4187938
> hw-mgmt: topology: Add devtree support for lm90, tmp411 temperature sensors

- usr/usr/bin/hw_management_sync.py
Fix hw-management sync crash in case ASIC value is not exist
Bug: 4184342
> hw-mgmt: scripts: Fix ASIC temp populate in hw-mgmt-sync script

- usr/usr/bin/hw_management_sync.py
Fix in hw-mgmt sunc script max and crit values for ASIC temperatures
Bug: 4173495
> hw-mgmt: attributes: Fix max and crit values for ASIC temperatures

- usr/usr/bin/hw-management-thermal-events.sh
On some PSUs volt out value exposed in out2 pmbus attribute (instead of
vout) With this fix - added correct vout attribute linkage on PSUs which
have both vout/vout2 attributes
Bug: 4143199
> hw-mgmt: attributes: Fix PSU volt out attributebute

- usr/usr/bin/hw-management-thermal-events.sh
On some PSUs volt out value exposed in out2 pmbus attribute (instead of
vout) With this fix - added correct vout attribute linkage on PSUs which
have both vout/vout2 attributes
Bug: 4143199
> hw-mgmt: attributes: Fix PSU volt out attributes

- usr/etc/hw-management-sensors/sn5640_sensors.conf
- usr/etc/hw-management-thermal/tc_config_sn5610.json
- usr/usr/bin/hw-management-thermal-events.sh
There is only one SODIMM module on SN5610 and SN5640 systems at I2C address 0x1b. Name it SODIMM1 and adjust all relevant files.
> hw-mgmt: scripts: Fix SODIMM naming on SN5610 and SN5640

- usr/etc/hw-management-sensors/sn5640_sensors.conf
- usr/etc/hw-management-thermal/tc_config_sn5610.json
- usr/usr/bin/hw-management-thermal-events.sh
This reverts commit 809714281df616d4093b415be2d1816b7de9b468.
The SN5610 and SN5640 CPU boards will be modified to have the same SODIMM TS I2C address as other AMD CPU boards.
> Revert "hw-mgmt: scripts: Fix SODIMM naming on SN5610 and SN5640"

- usr/usr/bin/hw_management_sync.py
Update the hw_management sync script to fix module temperature reading
when in SW mode. Key changes:
1. Add a check for control mode (SW or FW) before reading. Skip reading
in SW mode.
2. Add validation for module presence.
3. Run scan and update for all modules in a single loop instead of
updating each module separately.
Bug: 4201043
> hw-mgmt: scripts: Fix module reading in sync script

- usr/usr/bin/hw_management_sync.py
Fix asic_chipup_completed for systems without minimal driver. Added
feature to sync script which will handle asic state and update
attributes/counters:
- asics_init_done
- asic_chipup_completed
Bug: 34304249
> hw-mgmt: scripts: Fix asic_chipup_completed for systems without minimal driver

- debian/rules
Do not install ARM64 version of this file  on X86_64 systems.
> hw-mgmt: rules: Fix install of /etc/modprobe.d/hw-management.conf

- unittest/hw_management_bmcaccessor_login_test.py
- usr/usr/bin/hw_management_redfish_client.py
Title:[Feature][Login] add support for new nos_bmc user
Description: hw mgmt makes sure new nos_bmc user will be valid with tpm pwd for nos/bmc i/f
Issue: #4149897
Dependent Changes: bmc 909 and onwards support new user, however hw mgmt keeps backwards compatible
> Title:[Feature][Login] add support for new nos_bmc user

- usr/usr/bin/hw_management_sync.py
When the ASIC SX driver is not available due to the ISSU state,
temperature reading is not available. This commit adds a check for the
asic{}_ready flag to determine if temperature reading is available:
/var/run/hw-management/config/asic{}_ready
1 - ASIC sx driver ready to temperature read
0 - ASIC driver not loaded of temperature is not avalible
> hw-mgmt: scripts: Add ASIC state check on temperature reading

- usr/usr/bin/hw-management.sh
Fix config file creation order on hw-mgmt start
Bug: 4209209
> hw-mgmt: config: Fix config files creation order on hw-mgmgmt start

- usr/usr/bin/hw_management_thermal_control.py
• If ASIC temperature is reading as zero 3 times sequential
(during 9 secs) – don’ trust to mlxsw_minimal readouts and run emergency
flow.
• Emergency flow should enforce fan to full speed forever until
system reboot or hw-mamagement restart.
• When it happens, hw-management-tc will set to '1' file
/var/run/hw-management/config/thermal_enforced_full_spped
OS can monitor thermal_enforced_full_spped and issue tech-support dump
for future debug
Bug: 4203784, 4203785, 4219113
> hw-mgmt: thermal: Add handler for miniaml i2c bus block

- usr/usr/bin/hw-management-thermal-events.sh
These files are generated when PSUs are detected on I2C bus. However they are not removed when PSUs are plugged out. This makes it difficult to differentiate between real and dummy PSUs since dummy PSUs are not visible on I2C.
> hw-mgmt: scripts: Delete psuN_i2c_bus files when PSUs are plugged out

- usr/usr/bin/hw_management_sync.py
In case of PWM enforce event hApens (because of TC issued it) debug dump
handler will be called.
Flag:
/var/run/hw-management/config/thermal_enforced_full_spped
will set in case of FAN full speed set in abnormal situations, like
ASIC not accesible.
When it happens, hw-management will call /usr/bin/hw-managemrnt-user-dump, which is user callback. OS on init can create symbolic link:
/usr/bin/hw-managemrnt-user-dump -> /usr/cumulus/bin/cl-support.
OS can set their callback, if needed or not set at all.
Bug: 4221324, 4221324
> hw-mgmgt: debug: Add debug dump handler for PWM enforce event

- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw_management_thermal_control.py
Fix devtree component indexes:
["g"]="lm90"
["h"]="emc1412"
["k"]="tmp451"
Bug: NA
> hw-mgmt: topo: Fix devtree component indexes

- usr/usr/bin/hw_management_sync.py
Fix sync service crash - misprint in hw_mgmt_sync.
Bug: 4247318
> hw-mgmt: script: Fix crash in the sync script

- usr/usr/bin/hw_management_sync.py
Fix hw-mgmgt sync scripyt crash.
Bug: 4248850
> hw-mgmgt: script: Fix hw-mgmt-sync failed issue on Juliet

- usr/etc/hw-management-thermal/tc_config_msn5400.json
- usr/etc/hw-management-thermal/tc_config_n5100ld.json
- usr/etc/hw-management-thermal/tc_config_n5110ld.json
- usr/etc/hw-management-thermal/tc_config_n5110ld_ttm.json
- usr/etc/hw-management-thermal/tc_config_q3200.json
- usr/etc/hw-management-thermal/tc_config_q3400.json
- usr/etc/hw-management-thermal/tc_config_sn4280.json
- usr/etc/hw-management-thermal/tc_config_sn5610.json
- usr/etc/hw-management-thermal/tc_config_sn5640.json
Fix tc_config files. Rename error_mask type:
psu -> psu_err
fan -> fan_err
Affected systems: msn5400, n5110ld, q3200, q3400, sn4280, sn5610, sn5640
Condition: if error happens on masked sensor - mask will be ignored.
Epecting pwm change even if error was masked.
Bug: 4248463
> hw-mgmt: thermal: Fix tc config files

- usr/etc/hw-management-sensors/n51xxld_sensors.conf
- usr/usr/bin/hw-management-devtree.sh
1. Fix i2c 14-4c sensor type in devtree lm90 -> emc1412
2. Fix HSC sensor type lm5066 -> lm5066i
Bug: N/A
> hw-mgmt: attributes: Fix PDB HSC/thermal sensor type

- usr/etc/modprobe.d/hw-management.conf
Initialization of usb network interface on BMC enabled systems occasionally results in the following error messages:
cdc_subset: probe of 1-2.1:1.0 failed with error -22
cdc_ether: probe of 1-2.1:1.0 failed with error -16
Since both cdc_subset and cdc_ether drivers can handle usb network interface between host CPU and BMC, blacklist the cdc_subset driver to make sure that only cdc_ether driver is loaded. This fixes the error messages above.
Bug: 4260024
> hw-mgmt: init: Blacklist cdc_subset network driver

- README.md
- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/0030-1-platform-mellanox-nvsw-sn2201-Add-check-for-platform.patch
- recipes-kernel/linux/linux-6.1/0030-platform-mellanox-nvsw-sn2201-change-fans-i2c-busses.patch
- recipes-kernel/linux/linux-6.1/0087-platform-mellanox-indicate-deferred-I2C-bus-creation.patch
- recipes-kernel/linux/linux-6.1/0095-platform-mellanox-nvsw-sn2201-Add-support-for-new-sy.patch
Add kernel 5.10.226/6.1.123 support
> hw-mgmt: patches: 5.10/6.1: Add kernel new kernel version support

- usr/usr/bin/hw-management-chassis-events.sh
By default in lm5066i VOUT_UV_WARN_LIMIT registrer == 0. Because of issue in
driver calculation formula it trasnsforms to -0.11V instead of 0, which is
not reasonable.
It can be fixed by writing 0 to *_in2_min sysfs attribute.
Bug: 4264364
> hw-mgmt: sensor: Fix for unexpected negative vout_min on lm5066i

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
Acbel PSUs equiped0 with eeporom 24c02. This fix add
check for PSU type and for connect 24c02 or 24c32 eeprom depending
of PSU type
Bug: 4227794
> hw-mgmgt: topo: Fix Acbel PSU eeprom type

- usr/usr/bin/hw_management_thermal_control.py
For systems that use sensor value scale factor != 1000 this
value should be applied to min/max sensor threshold.
This commit fix bug with min/max calculation for sensors with
value divider differents than default (1000)
Bug: 4284991
> hw-mgmt: thermal: TC fix for sensor min/max limits calculation

- usr/usr/bin/hw-management-ifupdown.sh
Udev rule to initialize usb network interface can run before configuration file /etc/network/interfaces was created or before the configuration data for usb network interface was added to this file. This can result in the following error messages:
(udev-worker): usb0: Process ‘/usr/sbin/ifup usb0’ failed with exit code 89.
Add checks to avoid such errors from showing in the logs.
Bug: 4260031
> hw-mgmt: rules: Fix initialization of usb network interface

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0303-platform-mellanox-mlxreg-io-Extend-number-of-hwmon-a.patch
- recipes-kernel/linux/linux-6.1/0098-platform-mellanox-mlxreg-io-Extend-number-of-hwmon-a.patch
Add BMC thermal sensor to TC sensor list. Fix BMC thermal sensor name
in N5xxx thermal config
Bug: 4288149
> hw-mgmgt: thermal: TC fix bmc sensor init for N5xxx systems

- usr/lib/udev/rules.d/76-hw-management-bmc.rules
In kernel version 6.1.123 the name of USB network interface has changed from usb0 to eth2. This breaks IP address assignement of this interface as our network configuration files assume usb0 as interface name. Fix udev rule to explicitcly set the name of this interface as usb0.
> hw-mgmt: rules: Explicitly set the name of USB network interface

- usr/etc/hw-management-sensors/sn4280_sensors.conf
- usr/etc/hw-management-sensors/sn5640_sensors.conf
Set to 'ignore' PHY MDIO on SN4280 and SN5640, since reading ofthis device is not stable.
And it is not considered for thermal monitoring.
> hw-mgmt: sensors: Remove MDIO PHY from sensors config

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0304-platform-mellanox-mlx-platform-Add-support-for-new-N.patch
- recipes-kernel/linux/linux-5.10/0305-platform-mellanox-Downstream-Add-support-for-new-Nvi.patch
- recipes-kernel/linux/linux-5.10/0306-platform-mellanox-Downstream-Add-support-DGX-flavor-.patch
- recipes-kernel/linux/linux-5.10/9003-platform-mellanox-Introduce-support-of-Nvidia-L1-tra.patch
- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
Reorder patches. Move patches for MQM97001/SN5600d/SN5610/SN5640
systems to general group of upstreamed patches with indexes 0XXX.
> hw-mgmmt: kernel 5.10: reorder (rebase) platform patches

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
Acbel PSUs equipped with eeporom 24c02. This fix adds check for PSU type and connects 24c02 or 24c32 eeprom depending on PSU type.
Bug: 4227794
> hw-mgmt: topo: Fix Acbel PSU eeprom type

- usr/usr/bin/hw-management-thermal-events.sh
Fix psu curr/power out attributes names. Add more conventional names
psuX_power_out and psuX_curr_out attributes in additional to existing
psuX_power and psuX_curr.
Attributes psu1_volt_in/out psu1_curr_in/out psu1_power_in/out will be
available for all platforms (if PSU supported).
Bug: 4150586
> hw-mgmt: attributes: Fix PSU attributes

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
Add event for "swb_info" event.
Set number of cartridges for GB200HD to zero.
> hw-mgmt: events: Add event handler for switch board  eeprom

- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
Remove none existing leakage_led from HI176/HI177 systems.
> hw-mgmt: kernel 6.1/5.10: Remove none existing leakage_led from 176/177 systems

- usr/usr/bin/hw_management_sync.py
Optimize sync script module update.
1. Change in system configuration. Define total module count instead
of per module definition.
2. Check SDK SW/FW reading mode by reading just one module config.
No need to check each module config because modules can't be initialized
in the "mixed" mode.
> hw-mgmt: script: Optimize sync script module update

- debian/hw-management.hw-management-fast-sysfs-monitor.init
- debian/hw-management.hw-management-fast-sysfs-monitor.service
- debian/hw-management.hw-management-sysfs-monitor.init
- debian/hw-management.hw-management-sysfs-monitor.service
- debian/rules
- usr/etc/hw-management-fast-sysfs-monitor/fast_sysfs_labels.json
- usr/lib/udev/rules.d/49-hw-management-fast-events.rules
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-fast-sysfs-monitor.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-sysfs-monitor.sh
- usr/usr/bin/hw-management.sh
Added support for:
1. Provide trigger event to signal all sysfs attributes are ready.
2. Provide fast boot indication for specific sysfs attributes.
3. Provide fast boot optimizations for specific devices.
> hw-mgmt: services: sysfs monitor and fast boot indication

- usr/usr/bin/hw-management.sh
Fix PSU count for mqm9701, sn5600d systems. Thease systems
doesn't support PSU. Set psu_cout = 0.
Bug: NA
> hw-ngngt: topo: Fix PSU count for mqm9701, sn5600d systems

- debian/hw-management.hw-management-fast-sysfs-monitor.init
- debian/hw-management.hw-management-sysfs-monitor.init
- usr/lib/udev/rules.d/49-hw-management-fast-events.rules
- usr/usr/bin/hw-management-fast-sysfs-monitor.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-sysfs-monitor.sh
1. Removed 'bc' tool usage which is missing from Sonic.
2. Added further optimization for fast boot.
> hw-mgmt: services: fix fast sysfs monitor service

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
If PSU FAN should be controlled by its FW we shouldn't set default PSU
FAN speed on init. PSU FAN default spped will be set only for systems
with TC controllable PSU FANs
Bug: N/A
> hw-mgmgt: thermal: Fix PSU_FAN speed control for FW controlled PSU

- usr/usr/bin/hw-management-thermal-events.sh
Fix thermal sensor link create for multi asic systems. For multi ASIC
systems hw-mgmt should check if i2c device doesn't belong to any ASIC
bus.
Bug: 4327177
> hw-mggmt: thermal: Fix thermal amb sensor link for multi asic systems

- usr/etc/hw-management-virtual/HI166/environment
- usr/etc/hw-management-virtual/HI166/thermal
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-start-post.sh
- usr/usr/bin/hw-management.sh
Bug: N/A
This patch set adds the support for
- Enabling platform emulation for Juliet
- Sensor attributes for which the sensor emulation driver is not available.
- Workaround for sodimm sensor availability in AMD based virtual platforms
> hw-mgmt: scripts: Enable Juliet platform emulation

- usr/etc/hw-management-sensors/sn5600d_sensors.conf
- usr/usr/bin/hw-management-devtree.sh
Fix missing pwr_conv sensor in SN5600D system.
Add alternative component support: raa228004
Bug: 4354380
> hw-mgmgt: sensors: Fix missing pwr_conv sensor in SN5600D system

- recipes-kernel/linux/Patch_Status_Table.txt
The patch 900X-platform-mellanox-mlx-platform-Change-register-0x28-.patch relies on patch 9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch that is skipped by Sonic build, thus causing build failure. Fix this by ignoring 900X-platform-mellanox-mlx-platform-Change-register-0x28-.patch as well for Sonic build.
> hw-mgmt: patches: Fix Sonic build by ignoring all Q3450 patches

- debian/changelog
- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
- recipes-kernel/linux/linux-6.1/0098-platform-mellanox-mlx-dpu-improve-interrupt-handling.patch
DPU auxiliary powering can cause interrupt flooding because
DPU interrupt handlers are not configured yet, while middle
interrupt aggregation register is unmasked by default during
initialization. Thus, interrupts are getting through, while
handlers are still not fully initialized. Do not unmask
aggregation interrupt register at initialization for all
DPUs. Instead do it per DPU, when its initialization is done.
This patch also adds the change to clear the DPU event
registers.
Bugs: 4338675
> hw-mgmt: patches: Improve dpu interrupt handling

- debian/changelog
- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/0098-platform-mellanox-mlx-dpu-improve-interrupt-handling.patch
- recipes-kernel/linux/linux-6.1/9003-platform-mellanox-Introduce-support-of-Nvidia-L1-tra.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/sonic/0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
There are patches on mlx-platform.c which are not taken by certain
NOSs. This commit rebases the patches and update the patch_status
table to avoid build failures.
Bugs: N/A
> hw-mgmt: patches: Rebase patches to fix NOS builds

- debian/changelog
- usr/etc/hw-management-virtual/HI166/environment
- usr/usr/bin/hw-management-helpers.sh
This patch updates values and adds missing values to voltage sensor data on Juliet Qemu emulation.
Bugs: 4363327
> hw-mgmt: scripts: Update platform emulation sensor values for Juliet

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-thermal-events.sh
Due to an error in the PSU firmware, some PSUs are returning incorrect
values for the attributes out_min, out_max, and out_lcrit. This issue
occurs with the Delta 1100 PSU. This fix adds initialization for these
attributes based on expected values.
Bug: 3874682
> hw-mgmgt: sensors: Fix PSU vout min/max atriburtes

- usr/usr/bin/hw-management.sh
Increase wait time from 2 to 5 seconds for VMOD0014 systems to align it with others SPC1 systems.
Bug: #4368754
> hw-mgmt: Increase wait time for testing hwmon object existence for ASIC

- debian/changelog
- recipes-kernel/linux/linux-6.1/0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
- recipes-kernel/linux/linux-6.1/sonic/0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
Recent rebase has caused an issue with dpu boot_progress register name change. This patch corrects it.
Bugs: 4378157
> hw-mgmt: patches: Fix dpu boot_progress attribute

- usr/usr/bin/hw-management-fast-sysfs-monitor.sh
- usr/usr/bin/hw-management-helpers.sh
Increase fast sysfs T.O for supporting lower end systems. Exit with warning in case of T.O
> hw-mgmt: Increase fast sysfs T.O

- debian/changelog
- recipes-kernel/linux/linux-6.1/0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
- recipes-kernel/linux/linux-6.1/sonic/0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
This commit fixes some of the dpu attribute masks.
Bugs: 4378157
> hw-mgmt: patches: Fix dpu attribute mask

- debian/hw-management.hw-management-fast-sysfs-monitor.init
- debian/hw-management.hw-management-sysfs-monitor.init
- debian/hw-management.hw-management.init
Added lsb block header for older systems with sysvinit support, in sysfs monitor init files.
> hw-mgmt: sysvinit files

- usr/usr/bin/hw-management-fast-sysfs-monitor.sh
- usr/usr/bin/hw-management-helpers.sh
Increase fast sysfs T.O for supporting lower end systems. Exit with warning in case of T.O
> hw-mgmt: Increase fast sysfs T.O (#1661)

- usr/usr/bin/hw-management-generate-dump.sh
Add CPLD registers dump by the direct reading with "iorw" cmd.
> hw-mgmgt: scripts: Improve debug dump

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-fast-sysfs-monitor.sh
Add protection in case race condition between
hw-management service and fast-sysfs service.
Bug: 4406920
> hw-management: fast sysfs monitor

- usr/etc/hw-management-thermal/tc_config_q3200.json
- usr/etc/hw-management-thermal/tc_config_q3400.json
Fix q3200_ra/q3400_ra name in thermal config.
> hw-mgmt: thermal: Fix q3200_ra/q3400_ra name in thermal config

- debian/hw-management.hw-management-fast-sysfs-monitor.service
- debian/hw-management.hw-management-sysfs-monitor.service
Remove TimeoutStopSec=1.
Timeout will be handled by systemd default.
Bug: 4406833
> hw-management: sysfs systemd services

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-ready.sh
- usr/usr/bin/hw-management-start-post.sh
On SIMX, hw-mgmt tries to start the TC service during initialization. However, the TC service has a strong dependency:
Requires=hw-management.service. This means the TC service cannot start before hw-mgmt starts. But hw-mgmt attempts to start TC earlier. In this case, neither hw-mgmt nor TC will complete initialization.
This commit resolves this deadlock by postponing the start of the TC service.
Bug: 4427090
> hw-mgmt: service: Fix deadlock for hw-gmgt <-> TC sevice start on SIMX

- debian/hw-management.hw-management-fast-sysfs-monitor.service
- debian/hw-management.hw-management-sysfs-monitor.service
Without oneshot definition Sonic service monitor shows the service status as "Down"
Bug: 4389689
> hw-mgmt: service: Define the type sysfs monitor services as oneshot

- debian/hw-management.hw-management-fast-sysfs-monitor.service
- usr/usr/bin/hw-management-fast-sysfs-monitor.sh
Since this service is a 'oneshot' type service,
Remove dependency with hw-management main service. Also add protection in case directory structure
is not ready.
Bug: 4439383
> hw-mgmt: service: Fix dependency of hw-mgmt-fast-sysfs-monitor service

- usr/etc/hw-management-sensors/sn5640_sensors.conf
The current labels for MP2891 VR at I2C address 0x6E are swapped between VDDSCC and DVDD_M rails, which results in incorrect current reporting.
Bug: 4404746
> hw-mgmt: sensors: Fix MP2891 current labels for SN5610/SN5640

- usr/usr/bin/hw_management_psu_fw_update_delta.py
The latest FW version of Acbel 2K PSUs changed the output of PMBUs command that reports FW version. The new output format is identical to that of Delta 2K PSUs. HW-MGMT script that reports PSU FW version should be updated to correctly report it for Acbel PSUs.
Bug: 4445621
> hw-mgmt: scripts: Change reading of Acbel 2K PSU FW version

- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-5.10/9007-platform-mellanox-mlx-platform-Change-register-0x28-.patch
- recipes-kernel/linux/linux-5.10/9008-platform-mellanox-mlx-platform-Add-support-for-Q3450.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9008-platform-mellanox-mlx-platform-Change-register-0x28-.patch
- recipes-kernel/linux/linux-6.1/9009-platform-mellanox-mlx-platform-Add-support-for-Q3450.patch
Add reset cause of cpu erot ./system/reset_from_erot
FR: 4441226
Bug: 4438900
> hw-mgmgt: kernel 5.10/6.1: patches: Add reset "reset_from_erot" reset cause.

- usr/usr/bin/hw-management.sh
New SED PBA, versions 83.01.0008 and up, reports version through EFI variable.
If applicable hw-management reads this ERFI variable and report to NOS.
> hw-mgmt: scripts: Add attribute with SED PBA version.

- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-5.10/9007-platform-mellanox-mlx-platform-Change-register-0x28-.patch
- recipes-kernel/linux/linux-5.10/9008-platform-mellanox-mlx-platform-Add-support-for-Q3450.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9008-platform-mellanox-mlx-platform-Change-register-0x28-.patch
- recipes-kernel/linux/linux-6.1/9009-platform-mellanox-mlx-platform-Add-support-for-Q3450.patch
Add missing reset cause to mlx-platform driver for NVL systems family
Added reset cause:
"reset_sw_reset", "reset_cpu_thermal", "reset_aux_pwr_or_reload"
> hw-mgmgt: kernel: patch: Add missing reset cause for NVL systems family

- usr/usr/bin/hw_management_thermal_control_2_5.py
TC has an option to smooth sensor input values (to suppress fast PWM
jumps).
By default, "No smoothing" should be used for sensor input values.
There was an error in the smoothing formula which unintentionally
enabled the minimum smoothing level for all sensors.
This fix sets the "No smoothing" level as the default for all sensor
inputs.
This is not a critical bug.
Bug: 4452512
> hw-mgmgt: thermal: TC: Fix default smoothing level for sensor input

- usr/usr/bin/hw_management_thermal_control_2_5.py
TC has an option to smooth sensor input values (to suppress fast PWM
jumps).
By default, "No smoothing" should be used for sensor input values.
There was an error in the smoothing formula which unintentionally
enabled the minimum smoothing level for all sensors.
This fix sets the "No smoothing" level as the default for all sensor
inputs.
This is not a critical bug.
Bug: 4452512
> hw-mgmgt: thermal: TC: Fix default input val smoothing level

- usr/usr/bin/hw_management_sync.py
Fix asic temp sync for systems with minimal disabled.
ASIC temperature sync should be updated independent of SDK mode.
Bug: 4463009
> hw-mgmgt: script: Fix asic temp sync

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Add cpld registers dump on system start. Dump will be
saved in the system 'syslog' logfile.
FR: 4458180
> hw-mgmgt: scripts: Add cpld registers dump on system start

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-start-post.sh
By mistake we had "reversed logic" for disabling ThermalControl
on systems without TC support.
Bug: 4466832
> hw-mgmt: thermal: Fix TC service disable on system start

- usr/usr/bin/hw_management_thermal_control_2_5.py
Added a flag to the TC to disable TEC feature support by default. It
should be removed after the qualification tests.
> hw-mgmt: thermal: TC add flag to disable tec support

- usr/usr/bin/hw_management_thermal_control_2_5.py
Fix code syntax issue in TC. Missing ':' symbol
Bug: 4474282
> hw-mgmt: thermal: Fix code syntax issue in TC

- usr/etc/hw-management-thermal/tc_config_q3450.json
Fix sysm name in TC config for q3450.
Add support for name variant q3450_ld
Bug: 4430499
> hw-mgmt: thermal: Fix sysm name in TC config for q3450

- usr/usr/bin/hw-management-generate-dump.sh
- usr/usr/bin/hw-management-helpers.sh
Add cpld registers dump to cyclic rotating log file. Dump will be saved
to /var/log/hw-mgmt-cpldreg.log file
Max number or dump records : 100
FR: 4458180
> hw-mgmgt: scripts: Add cpld registers dump to cyclic rotating log file

- usr/usr/bin/hw-management-chassis-events.sh
Error on run hw-management-chassis-events.sh hotplug-event FAN1 0
/usr/bin/hw-management-chassis-events.sh: line 480: [: 63: unary
operator expected
These error belong to FAN debounce function. It happens because
fan_dir_old variable was not initialized.
Fix: initialize fan_dir_old variable
Bug: 4486155
Signed-off-byr Oleksandr Shamray <oleksandrs@nvidia.com>
> hw-mgmgt: scripts: Fix FAN debounce function error

- usr/usr/bin/hw-management-ifupdown.sh
The check in hw-management-ifupdown.sh that usb0 configuration is present in /etc/network/interfaces is not robust enough. The NOS may decide to keep usb0 configuration in a different file included by /etc/network/interfaces. In that case usb0 configuration will fail. Use ifquery tool to perform the check, as it covers /etc/network/interfaces and all files it includes.
Bug: 4472264
> hw-mgmt: scripts: Fix the check for usb0 interface configuration

- usr/usr/bin/hw-management.sh
Set sn5610/sn5640 system FAN max/min speed according to spec.
Front FAN
max:  21800 RPM
min:  6879 RPM
Rear FAN
max:  20500 RPM
min:  6468 RPM
FAN speed tolerance +-10%
Bug: 4449649
> hw-mgmgt: thermal: Fix FAN min/max speed for sn5610/5640

- usr/usr/bin/hw-management-ifupdown.sh
Currently the validity checks for usb0 interface configuration assime that it is defined as "allow-hotplug usb0" in cofiguration file /etc/network/interfaces. Some NOSes may define it as "auto usb0", and validity checks will fail. This can result in usb0 remaining unconfigured on host side after BMC reboot. Adjust the checks to allow "auto usb0".
Bug: 4491046
> hw-mgmt: scripts: Adjust the check of usb0 interface configuration

- unittest/hw_mgmgt_sync/module_populate/README_tests.md
- unittest/hw_mgmgt_sync/module_populate/run_all_tests.py
- unittest/hw_mgmgt_sync/module_populate/run_module_tests.sh
- unittest/hw_mgmgt_sync/module_populate/run_tests.sh
- unittest/hw_mgmgt_sync/module_populate/simple_test.py
- unittest/hw_mgmgt_sync/module_populate/test_module_temp_populate.py
- usr/usr/bin/hw_management_sync.py
If the module is in SW mode, hw-mgmt shouldn't update the
./thermal/moduleX_* attributes.
In our algorithm, if a module is not present, we fill its attributes with zeros.
In SW mode, the "present" status is "0", which caused a conflict with a
similar OS process when hw-mgmt overwrote the module attributes with
zeros.
If affect thermal algo because it try to set PWM based on wrong inputs
(module temperature is 0).
In SW mode, hw-mgmt shouldn't even check the module status and should
give priority to the OS for updating the attributes.
This commit adds a check for the module's "mode" first, and if it's in SW mode,
skips the update. We don't even need to read the "present" status in this case
Bug: 4494119
Unittests incuded.
> hw-mgmt: scripts: Fix module temperature sync conflict in SW mode

- usr/usr/bin/hw_management_thermal_control_2_5.py
We had copy-paste issue in TC config load function.
Affect configuration parameter:
"pwm_update_period"
Not critical,  Low risk
Fix:
CONST.SYS_CONF_REDUNDANCY_PARAM -> SYS_CONF_GENERAL_CONFIG_PARAM
Bug: 4499238
> hw-mgmt: thermal: thermal control fix misprint in config load fuction

- usr/usr/bin/hw_management_redfish_client.py
Issue: [#4497091](https://redmine.mellanox.com/issues/4497091)
Why I did it
The root user of bmc is not changed automatically, leaving this default password is a security risk
root password written but not used and not called in the code or in hw-management-sync.service calling it.
Tested locally on a running system.
> remove root default password from code

- usr/usr/bin/hw-management-thermal-events.sh
In case hw-mgmt fails to initialize PSU EEPROM driver, the eeprom file under /sys will not be created. In that situation PSU EEPROM symlink under hw-mgmt tree should not be created to avoid generating dangling links.
Bug: 4478004
> hw-mgmt: scripts: Create PSU EEPROM symlinks only if actual files exist

- usr/usr/bin/hw_management_thermal_control_2_5.py
If module reading was failed we had issue with printing periodic report.
It happens because issue in module temperature value convert to float
in case value is not a numeric: "N/A".
Fix: convert to float only in case temperature value is numeric
Bug: 4502817
> hw-mgmt: thermal: TC fix module periodic report log

- usr/usr/bin/hw_management_redfish_client.py
Issue: [#4410461](https://redmine.mellanox.com/issues/4410461)
HLD: [BMC Credenials](https://confluence.nvidia.com/pages/viewpage.action?pageId=3984211056)
Why I did it
Strengthen the bmc credentials without breaking backward compatibility
How I did it
the TPM generation password now depends on platform number
> change BMC password to be platform based 

- usr/usr/bin/hw-management.sh
Revert FAN max/min speed attributes. These attributes was
removed because of implemented per-fan-direction speed definition.
But this breaks backward compatibility.
Reverted attributes:
./config/fan_min_speed
./config/fan_max_speed
Bug: 4505804
> hw-mgmt: thermal: Revert FAN max/min speed attributes

- usr/usr/bin/hw-management-thermal-events.sh
The fix for bug 3874682 has added voltage threshold calculations for Delta 1100 PSU based on the value of critical max threshold. However the reading of this value was done incorrectly, resulting in all calculated theresholds being defined as 0. This patch fixes the threshold calculation.
Bug: 4505817
> hw-mgmt: scripts: Fix voltage threshold calculation for Delta 1100 PSU

- usr/usr/bin/hw_management_redfish_client.py
Issue: [#4410461](https://redmine.mellanox.com/issues/4410461)
HLD: [BMC Credenials](https://confluence.nvidia.com/pages/viewpage.action?pageId=3984211056)
Why I did it
instead of taking a long closed list of platform names. changed logic to search for a unique pattern of a certain platform of system type 
How I did it
search on a pattern that is mutual for all platforms of this type (N5___LD)
> change closed list of platform to generic type catch

- usr/etc/hw-management-thermal/tc_config_q3450.json
Fix system name in TC config for q3450.
Add support for name variant q3450_ld
Bug: 4430499
> hw-mgmt: thermal: Fix system name in TC config for q3450

- usr/usr/bin/hw_management_thermal_control.py
- usr/usr/bin/hw_management_thermal_control_2_5.py
TC add lcrit/hcrit check for module sensor. Set "sensor read"
error in case of module temp not in range [lcrit..hcrit] (same as
for other sensors)
Bug: 4528292
> hw-mgmt: thermal: TC add lcrit/hcrit validation for module sensor

- unittest/hw_mgmt_thermal_control_2_0/Fan_thermal_insert_fault_test.txt
- usr/etc/hw-management-thermal/tc_config_sn4280.json
- usr/usr/bin/hw_management_thermal_control.py
A customer (case #4486661) was reported regarding
the fan start issues after re-insertion. After re-inserting
fans in some systems, it may fail to start rotating.
A stuck fan can start rotating by either of the following actions:
1) Pulling out and reinserting an additional fans.
2) Lowering the PWM of all fans for a few seconds.
The commit ff627 introduced FR #4521169 to Thermal
control 2.5. This patch enables the feature for Thermal
control 2.0.
Bugs:  #4360106
NVBug: #5317658
> hw-mgmt: thermal: Fan state validation after re-insertion

- usr/usr/bin/hw_management_sync.py
Fix module counter for SN5600 switch. Switch have 65 ports/modules.
Change module count:
66 -> 65
Bug: 4540295
> hw-mgmt: sensors: Fix module counter for SN5600 switch

- usr/usr/bin/hw_management_thermal_control.py
- usr/usr/bin/hw_management_thermal_control_2_5.py
In TC when simulating asic read error we continuously see error logs,
even after asic error recovered.
This commit fix error.
Bug: 4545207
> hw-mgmt: thermal: Fix not recover PWM after asic sensor reading error

- usr/etc/hw-management-thermal/tc_config_sn5610.json
- usr/etc/hw-management-thermal/tc_config_sn5640.json
Fix thermal data for sn5610/5640 systems.
"C2P:Sensor read failure" PWM level changed 80 -> 70 (aligned to value
provided by HW)
bug: 4528191
> hw-mgmt: thermal: Fix thermal data for sn5610/5640 systems

- usr/etc/hw-management-virtual/HI171/thermal
- usr/usr/bin/hw-management-start-post.sh
Adding the missing sensor (for the sensors which doesn't have the emulation drivers) attributes as static values in SN5640 platform. This will be helpful for running TC.
Bugs: #4546019, #4545909
> hw-mgmt: scripts: Update SN5640 virtual sensor attributes

- debian/hw-management.hw-management-tc.service
On some low-performance systems, stopping the hw-management-tc service
took longer than 1 second.
Fix: Increased the TimeoutStopSec value in the service file from 1 to 5
seconds.
Bug: 4543074
> hw-mgmt: service: Increase TC service stop timeout

- usr/usr/bin/hw-management.sh
Fixing the write error while setting the sodimm sensor attribute values.
Bug: #4540060
> hw-mgmt: scripts: Fix for setting sodimm attribute values

- usr/usr/bin/hw_management_sync.py
Some MSN3700/MSN3700C/MSN4700 systems have been customized with incorrect SMBIOS SKU field. This causes system detection failures in HW-MGMT sync service. Fix the sync service to properly identify such systems.
Bug: 4520864, 4544349
> hw-mgmt: scripts: Fix MSN3700/MSN3700C/MSN4700 detection in sync service

- usr/usr/bin/hw-management-helpers.sh
On systems that do not support thermal control, the thermal service
should be disabled. By mistake, we had the logic for thermal control
support detection inverted.
This commit fixes the TC support check logic:
Return 1 if TC is supported
Return 0 otherwise
Bug: 4567911
Manual tests passed:
On switch:
`systemctl enable hw-management-tc.service `
`systemctl start hw-management-tc.service `
check started
`systemctl status hw-management-tc.service `
run 
`hw-management-start-post.sh `
check started
`systemctl status hw-management-tc.service `
edit  /var/run/hw-management/config/tc_config.json
set TC not supported by adding to json:
` "platform_support" : 0,`
save
run 
`hw-management-start-post.sh `
check tc service disabled
`systemctl …
> hw-mgmt: script: Fix ThermalControl service disable logic

- usr/lib/udev/rules.d/50-hw-management-events.rules
Disable TPM runtime power management, i.e. TPM will always remain power-on.
It will allow avoiding rare cases of access to TPM when it's suspended.
The effect of always power-on the TPM on common power consumption is minimal.
Bug #4542714
> hw-mgmt: udev rules: disable TPM runtime power management.

- usr/usr/bin/hw-management.sh
For qm3401_LD we have only 17 reset causes. But defined 18.
In this case reset_ready not set because real reset_cause lower then
defined.
Fix:
change reset_attr_num attribute in ./config
18 -> 17.
Bug: 4577722
> hw-mgmt: topo: Fix reset_ready not set for qm3401_LD system

- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_sync.py
Add missed entries of synch process.
Fixes: #4564230: fix leak detection in cpu side on gb300
> hw-mgmt: leakage: Add missed entries for GB300 and Kyber high density

- usr/usr/bin/hw_management_thermal_control_2_5.py
Fix TC log level for "User config not defined" message.
This message is only informational, indicating a missing optional user
configuration file.
The log level of this message should be "info".
Fix:
Change message severity level from "warning" -> "info"
Bug: 4583302
> hw-mgmt: thermal: Fix TC log level for "User config not defined" message

- usr/usr/bin/hw-management-thermal-events.sh
Reverts commit df943c6cc38e7bc09136d2f69722c0dd46990f6d to prevent critical regression while documenting the original issue as a known limitation.
- Original issue: ASIC temperature reading problem (Redmine #4497061)
- Previous fix introduced critical regression (Redmine #4574847)
- Management decision: Revert fix to avoid critical bug, accept original issue as known limitation
- Reverts ASIC temperature reading fixes from hw-management-thermal-events.sh
- Documents the ASIC temperature reading issue as a known issue in Release.txt
- Critical regression (Redmine #4574847) should no longer occur
- Original ASIC temperature reading issue (Redmine #4497061) will return but is documented as known limitation
> Revert ASIC temperature reading fix to prevent critical regression

- usr/etc/hw-management-thermal/tc_config_q3450.json
Fix Q3450 thermal config. In "err_mask" field should be
changed "psu" -> "psu_err":
Change:
"error_mask" : {"psu" : ["direction", "present"]},
to
"error_mask" : {"psu_err" : ["direction", "present"]},
Bug: 4611676
> hw-mgmt: thermal: Fix misprint in Q3450 thermal config

- usr/etc/hw-management-sensors/sn4280_sensors.conf
This commit corrects a few typos for DPU sensor
attribute name configurations.
Bug: #4601092
> hw-mgmt: scripts: Fix SN4280 sensors config

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/8013-hwmon-pmbus-mp2975-Clear-interrupts-at-probe.patch
- recipes-kernel/linux/linux-6.12/8013-hwmon-pmbus-mp2975-Clear-interrupts-at-probe.patch
This patch clears the the registers 0xfd & 0x03
in both the pages to clear any of the stale interrupts.
NVBug: #5360318
> hw-mgmt: kernel: 6.1: mp2975: Clear interrupts at probe

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-thermal-events.sh
Due to an error in the PSU firmware, some PSUs are returning incorrect
values for the attributes out_min, out_max, and out_lcrit. This issue
occurs with the Delta 1100 PSU. This fix adds initialization for these
attributes based on expected values.
Bug: 3874682
> hw-mgmt: sensors: Fix PSU vout min/max attributes

- debian/hw-management.hw-management-fast-sysfs-monitor.service
- debian/hw-management.hw-management.service
The hw-management-sysfs-monitor does not automatically start when hw-mgmt is restarted. It is because the PartOf= directive only causes stop and restart operations on the main service to be propagated to the dependent. It does not cause a standard "start" or "restart" to also start the dependent if it was previously inactive. If hw-management-sysfs-monitor is not active at the moment hw-mgmt is restarted, it will stay inactive.
To make sure hw-management-sysfs-monitor also (re)starts whenever hw-mgmt is started or restarted, adding
'Wants=' directive to hw-management service.
Bug: 4540628, 4556756
Cursor Review
=========
Technical Analysis
✅ Positive Aspects:
Correct Solution: Adding Wants= to the main service ensures dependent services start when the main service starts
Proper Systemd …
> hw-mgmt: scripts: Correct dependency for systemd startup

- usr/usr/bin/hw-management-sysfs-monitor.sh
Adding the hw-mgmt tree dump before termination of sysfs monitor service to facilitate service debugging.
Bug: 4603973
> hw-mgmt: scripts: Add hw-mgmt tree dump to sysfs monitor service

- usr/usr/local/bin/hw-management-process-blacklist.sh
Cherry-pick commit 0bad29db05ce1bae450b605c6ca0d1a499b42b65 to add IPMI module blacklisting for n5500ld (HI176) systems.
This PR disables all IPMI kernel modules due to hardware signal integrity issues on n5500ld systems. The following IPMI modules will be blacklisted for HI176 systems:
- `ipmi_si`
- `ipmi_ssif` 
- `ipmi_devintf`
- `ipmi_msghandler`
- Added HI176 case to `hw-management-process-blacklist.sh` with IPMI module blacklisting
- Updated copyright headers with SPDX format
Bug #4432197
- Vadim Pasternak <vadimp@nvidia.com> (original author)
- Abraham Coifman <acoifman@nvidia.com> (cherry-pick)
> hw-mgmt: config: Disable IPMI module for n5500ld

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-start-post.sh
Very rarely on some smart switches, during a random kernel boot, some of the DPUs are not initialized. mlxreg-dpu driver fails to initialize. DPU attributes will not be available.
There is a timing issue with mlx-platfom driver and mlxreg-dpu driver. By the time, mlxreg-dpu driver tries to initialize the dpu, the relevant platform i2c bus is not created. Kernel provides a mechanism called deferred probing. In most of the cases, it does help, and we will get mlxreg-dpu probing done successfully. Very rarely, deferred probing timeout exceeds and we will end up having this issue.
This is a workaround to re-instantiate mlxreg-dpu if the kernel driver initialization failed
Bug: #4228063
> hw-mgmt: scripts: Re-instantiate mlxreg-dpu devices

- debian/hw-management.hw-management-fast-sysfs-monitor.service
- debian/hw-management.hw-management-sysfs-monitor.service
Sometimes, when starting the hw-mgmt service, the following error may appear:
"Failed with result 'start-limit-hit'"
This can occur for the hw-management-sysfs-monitor or
hw-management-fast-sysfs-monitor services. The reason is that these services are
limited to 5 starts within 20 minutes. If a user restarts hw-mgmt or any of
the listed services more than 5 times within that period, this error will occur.
The current limit of 5 restarts per 20 minutes is often too low and can be
triggered frequently during testing or normal usage. To prevent this issue,
restart limit can be increased to 10 times per 20 minutes.
Change in .service file:
StartLimitBurst 5 -> 10
Bug 4647168
> hw-mgmt: service: Fix service start-limit issue
