- mlnx-asic-drv.c
Signed-off-by: marian-pritsak <marianp@mellanox.com>
> [mlnx-asic-drv] Set temp_max attribute to 105000 mC

- usr/etc/mlnx/msn2100
Signed-off-by: marian-pritsak <marianp@mellanox.com>
> [msn2100]: Unload i2c_ismt on start.

- usr/etc/mlnx/msn2100
- usr/etc/mlnx/msn2410
Signed-off-by: marian-pritsak <marianp@mellanox.com>
> [msn2410 msn2100]: Add sys_eeprom device

- mlnx-cpld-drv.c
Upgated cpld_leds_profile structure.
Fix memset with wrong size issue
Fix psu module configuration
Signed-off-by: Oleksandr Shamray <oleksandrs@mellanox.com>
Reviewed-by: Vadim Pasternak <vadimp@mellanox.com>
> Upgated cpld_leds_profile structure.

- mlnx-asic-drv.c
- mlnx-cpld-drv.c
Signed-off-by: Oleksandr Shamray <oleksandrs@mellanox.com>
Reviewed-by: Vadim Pasternak <vadimp@mellanox.com>
> Fix "wrong reading qsfp eeprom" issue in mlnx-asic-drv driver

- include/mlnx-sys-type.h
- mlnx-a2d-drv.c
- mlnx-cpld-drv.c
- usr/etc/mlnx/msn2740
- usr/etc/modprobe.d/hw-management.conf
Signed-off-by: marian-pritsak <marianp@mellanox.com>
> [SN2740]: Add new platform

- debian/rules
- mlnx-asic-drv.c
- usr/lib/udev/rules.d/50-mellanox-system-event.rules
- usr/usr/bin/mellanox-system-event.sh
Porting hotplug support for Debian 8
> Adding hotplug support

- usr/lib/udev/rules.d/50-mellanox-system-event.rules
- usr/usr/bin/mellanox-system-event.sh
Signed-off-by: Vadim Pasternak <vadimp@mellanox.com>
Please enter the commit message for your changes. Lines starting
> Fixes for hotplug links

- usr/lib/udev/rules.d/50-mellanox-system-event.rules
- usr/usr/bin/mellanox-system-event.sh
Signed-off-by: Vadim Pasternak <vadimp@mellanox.com>
> Hotplug fixes

- usr/etc/mlnx/mlnx-hw-management
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>
> Fix system EEPROM for MSN2740 platform

- usr/etc/modprobe.d/mellanox-system-whitelist.conf
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>
> Add modprobe config for "at24" module

- usr/etc/mlnx/mlnx-hw-management
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
> move syseeprom to be first in connection table

- usr/etc/mlnx/msn2100
- usr/etc/mlnx/msn2410
- usr/etc/mlnx/msn2700
- usr/etc/mlnx/msn2740
- usr/lib/udev/rules.d/50-mellanox-system-event.rules
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
**HW-MGMT:** V1.0.0165
**Changelog:**
1. Fixed broken symlinks
2. Fixed PSU udev rules
3. Fixed log typos
4. Fixed indentations
5. Introduced start EEPROM action
> Introduce start EEPROM action

- debian/Release.txt
- debian/changelog
- usr/etc/hw-management-sensors/msn4700_respin_sensors.conf
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
> Cosmetic changes in text

- usr/usr/bin/hw-management-generate-dump.sh
Fix redirection all output to log files
> hw-mgmt: debug: Fix dmesg dump

- recipes-kernel/linux/linux-4.19/0079-leds-mlxreg-Provide-LED-color-conversion-from-hardwa.patch
- recipes-kernel/linux/linux-4.19/series
- usr/usr/bin/hw-management-chassis-events.sh
> hw-mgmt: attributes: add led trigger attribute

- usr/usr/bin/hw-management.sh
Fix config1 matching for MSN4600.
> hw-mgmt: system: MSN4600 A1 BU config1 fix

- usr/usr/bin/hw-management-thermal-control.sh
> squash to: "hw-mgmt: thermal: Fix cooling device enforcement criteria"

- recipes-kernel/linux/linux-4.19/0081-mlxsw-reg-Extend-MTMP-register-with-new-threshold-fi.patch
- recipes-kernel/linux/linux-4.19/0082-mlxsw-thermal-Add-function-for-reading-temperature-a.patch
- recipes-kernel/linux/linux-4.19/0083-mlxsw-Support-extended-capability-for-reading-temper.patch
- recipes-kernel/linux/linux-4.19/series
> hw-mgmt: patches 4.19: Add support for new feature provided by MTMP

- usr/usr/bin/hw-management-thermal-control.sh
Add temperature histeresis for dynamic_minimum change
> hw-mgmt: thermal: Add hysteresis fot dynamic_minimum change

- usr/usr/bin/hw-management.sh
> hw-mgmt: system: add msn3700 secured support

- recipes-kernel/linux/linux-4.19/0086-i2c-mlxcpld-Decrease-I2C-bus-polling-time.patch
- recipes-kernel/linux/linux-4.9/0072-Revert-i2c-busses-i2c-mlxcpld-Increase-transaction-p.patch
- usr/usr/bin/hw-management-generate-dump.sh
- hw-mgmt: kernel patches: 4.9,4.19: i2c: mlxcpld: Decrease I2C bus polling time
- hw-mgmt: debug: Fix dmesg dump
> V.7.0010.3100 BR

- usr/usr/bin/hw-management-thermal-events.sh
To optimize source code  size and quality - add separate functions for check and create/delete
link for sysfs attributes.
> hw-mgmt: attributes: add separate function for link/unlink sysfs attributes

- usr/usr/bin/hw-management-thermal-events.sh
Add links for PSU sensors attributes like: minimum, maximum, critical minimum,
critical maximum. This attributes added to "{hw-management}/power" folder
for: voltage/current/power PSU sensors types.
Also added {sensor_name}_capability file with list of supporting attributes
separated by space.
> hw-mgmt: attributes: Add PSU power sensor attributes

- usr/etc/hw-management-sensors/mqm9700_rev1_sensors.conf
- usr/usr/bin/hw-management.sh
> hw-mgmt: system: add mqm9700 rev1 support

- usr/usr/bin/hw-management-thermal-events.sh
- hw-mgmt: attributes: expose PSU fan min/max speed.
- hw-mgmt: attributes: fix psu fan minimal speed.
> V.7.0010.2300 BR

- usr/usr/bin/hw-management.sh
> hw-mgmt: system: Fix mqm9700 connect table Fix mqm9700 rev1 connect table

- usr/usr/bin/hw-management-start-post.sh
Change cpld3 version reading with using mlxreg tool on old systems like MSN24xx
and MSN27xxx.
Add more timeout for waiting cpld{n}_version sysfs crating
> hw-mgmt: attributes: Change cpld3 version reading with using mlxreg tool

- usr/etc/hw-management-sensors/mqm9700_rev1_sensors.conf
update mqm9700 sensors conf file
> hw-mgmt: update mqm9700 sensors conf file

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-start-post.sh
- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
Move duplicated functions from .sh scripts to separate hw-management-helper.sh file
> hw-mgmt: Move duplicated functions to separate helper file

- usr/usr/bin/hw-management-generate-dump.sh
Add timeout to generate-dump.sh
> hw-mgmt: debug: Add timeout to generate-dump.sh

- usr/usr/bin/hw-management-chassis-events.sh
Remove duplicate functions from  hw-management-chassis-events
which exist in hw-management-helpers
> hw-mgmt: Remove duplicated functions

- usr/usr/bin/hw-management-chassis-events.sh
In order to not create hw-management links for eeprom which is out of
mlxplat i2c bus space add check for eeprom address.
It will prevent to add eeprom with addresses like:
/sys/devices/pci0000:00/0000:XX:XX.X/i2c-0/0-0050
> hw-mgmt: chassis events: Add check if eeprom belong to mlxplat i2c bus

- usr/usr/bin/hw-management.sh
Fix mqm9700 hotplug_fans count
> hw-mgmt: system: Fix mqm9700 hotplug_fans count

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: attributes: Fix cpld_num for MSB78* systems Set cpld_num for MSB78* to "2" Small cleanups in source code

- usr/usr/bin/hw_management_psu_fw_update_murata.py
Change proceed flow. Fix msn4800 fail scenario.
> hw-mgmt: psu_fw_update_tool fix proceed.

- debian/changelog
> Update package version to 7.0010.3330. It should correspond to provided tag.

- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw_management_cpu_thermal.py
- hw-mgmt: thermal: add multi pwm cpu thermal control
- hw-mgmt: thermal: cpu thermal control improvements.
> V.7.0010.4000 BR

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-4.19/0139-hwmon-mlxreg-fan-Modify-PWM-connectivity-validation.patch
Align patch.
Update patch table.
> hw-mgmt: patches: v4.19: Align PWM pacth

- usr/usr/bin/hw-management-parse-eeprom.sh
Change parsing due to layout change.
> hw-mgmt: eeprom: Update parsing for line card INI

- README.md
Add kernel config options for SN2201.
Extend list of supported systems.
> hw-mgmt: README: Update kernel options and system list

- debian/changelog
> Update changelog 1.mlnx.7.0010.3330

- debian/changelog
> Change package version

- usr/etc/hw-management-sensors/e3597_sensors.conf
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management.sh
> hw-mgmt: system: Fix voltmon addresses for e35975 system

- debian/changelog
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-thermal-events.sh
Add and deletion of  "CPU Board Ambient" cpu_amb and "Switch Board Ambient"
swb_amb on SN2201 system.
> hw-mgmt: udev: create additional temperature sensors links on SN2201 system.

- recipes-kernel/linux/linux-4.19/0142-platform-x86-mlx-platform-Add-support-for-systems-eq.patch
- hw-mgmt: patches: 4.19: Fixes - comment out unused code
- hw-mgmt: patches: Remove unused code
> V.7.0020.1200 BR

- debian/changelog
- usr/usr/bin/hw-management.sh
> hw-mgmt: system: Add MSN600C A1 system support

- debian/changelog
- usr/usr/bin/hw-management-start-post.sh
- hw-mgmt: attributes: Fix cpld3 version reading on spc1 systems
- Update changelog     1.mlnx.7.0010.3331
> V.7.0010.3300 BR

- recipes-kernel/linux/linux-4.19/0142-platform-x86-mlx-platform-Add-support-for-systems-eq.patch
Fix commit 7f4eab8e8259b30db43e2ef8e76f04061d663c45
> hw-mgmt: patches: 4.19: Fix wrong patch change.

- recipes-kernel/linux/linux-4.19/0142-platform-x86-mlx-platform-Add-support-for-systems-eq.patch
> hw-mgmt: patches: 4.19: Fix asic[1/2]_reset control Fix asic[1/2]_reset control

- usr/usr/bin/hw-management-thermal-events.sh
> Fix merge issue

- debian/changelog
- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts: report CPLD2 version on SN22001 in decimal form.

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: thermal:  Add dynamic minimum table for MSN4600 system

- debian/changelog
> hw-mgmt: package: update version to 7.0020.1242

- debian/changelog
- usr/lib/udev/rules.d/50-hw-management-events.rules
> hw-mgmt: udev: Fix fan_amb matching rule for SN2201.

- usr/usr/bin/hw-management-thermal-control.sh
Change criteria for matching between cooling level
to be set and current cooling level: from 'le' to 'lt'.
Cosmetic changes for comments.
> hw-mgmt: thermal: Minor amendments and cosmetic changes

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-start-post.sh
- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
scripts cleanup and optimization
> hw-mgmt: scripts cleanup optimization

- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
1. Add supoort for FAN hot-plug events
2. Add WD support and init WD driver.
3. Add pwr_down and pwr_cycle attributes.
> hw-mgmt: patches: 4.19: Modify SN2201 platform driver.

- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
1. Add supoort for FAN hot-plug events
2. Add WD support and init WD driver.
3. Add pwr_down and pwr_cycle attributes.
> hw-mgmt: patches: 5.10: Modify SN2201 platform driver.

- debian/changelog
> Update hw-mgmt version.

- usr/usr/bin/hw-management.sh
> hw-mgmt: system: Fix number of hotplug PSUs on XH3000 system

- usr/usr/bin/hw_management_psu_fw_update_delta.py
- usr/usr/bin/hw_management_psu_fw_update_murata.py
Add argument to show PSU FW version in PSU FW update scripts
> hw-mgmt: psu fw update tool: add show FW version command

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: attributes: Add PSU FW version attributes

- recipes-kernel/linux/linux-5.10/0151-mlxsw-minimal-Prepare-driver-for-modular-system-supp.patch
- recipes-kernel/linux/linux-5.10/0155-mlxsw-minimal-Add-system-event-handler.patch
- recipes-kernel/linux/linux-5.10/0156-mlxsw-minimal-Add-interfaces-for-line-card-initializ.patch
Update patch #0151.
Rebase patches #0155, #0156.
> hw-mgmt: patches: 5.10: Add patches for SN4800 support

- usr/usr/bin/hw-management-thermal-control.sh
> hw-mgmt: thermal: add actual TC defines for SN2201.

- debian/changelog
- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-chassis-events.sh
- hw-mgmt: version: set version 7.0020.1334
- hw-mgmt: script & kernels: Change FAN hotplug event on SN2201 system
> V.7.0020.2000 BR

- usr/etc/hw-management-sensors/p2317_sensors.conf
- usr/usr/bin/hw-management-global-wp.sh
Add basic infrastructure for new VMOD0019.
Add skeleton for global write protect.
> hw-mgmt: infra: Add initial support NVIDIA HGX Vulcan Baseboard

- debian/changelog
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-thermal-events.sh
Add NVME SSD temperature reports to hw-management.
> hw-mgmt: script & udev: Add NVME temperature reports.

- recipes-kernel/linux/linux-5.10/0157-mlx-platform-Add-support-for-systems-equipped-with-t.patch
- recipes-kernel/linux/linux-5.10/0158-platform-mellanox-Introduce-support-for-COMe-NVSwitc.patch
Pathes provides:
Two ASICs system support.
COMe management module support.
> hw-mgmt: patches: 5.10: Add new patches

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Add P4697 system basic commit
<Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>
> hw-mgmt: system: Add P4697 system basic commit

- usr/etc/hw-management-sensors/p2317_sensors.conf
- usr/usr/bin/hw-management-global-wp.sh
- usr/usr/bin/hw-management.sh
Add topolgy for VMOD0012.
Few cosmetic changes.
> hw-mgmt: topolgy: Add support for P2317

- debian/changelog
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts: add fan direction indication on SN2201

- usr/etc/hw-management-sensors/p4697_sensors.conf
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
<Signed-off-by: Oleksandr Shamray <oleksandrs@nvidia.com>
> Add P4697 system basic commit

- usr/usr/bin/hw-management-global-wp.sh
Add more logic for global write protection handling.
> hw-mgmt: global wp: Extend global write protection script

- debian/changelog
- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
- usr/usr/bin/hw-management-start-post.sh
- usr/usr/bin/hw-management.sh
Rebase nvsw_sn2201 driver patches for PN report.
Change scripts for CPU CPLD PN report.
> hw-mgmt: kernel & scripts: add CPLD PN report on SN2201 system

- usr/usr/bin/hw-management-chassis-events.sh
> commit.log

- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
Add EROT events support for p4697 system
> hw-mgmt: topolgy: Add EROT events support for p4697 system

- recipes-kernel/linux/linux-5.10/0158-platform-mellanox-Introduce-support-for-COMe-NVSwitc.patch
- recipes-kernel/linux/linux-5.10/0159-platform-x86-mlx-platform-Add-support-for-new-system.patch
- recipes-kernel/linux/linux-5.10/0160-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
- recipes-kernel/linux/linux-5.10/0161-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
Rebase follwing after patches: #0158 - #0160.
Add patch #0161.
> hw-mgmg: patches: 5.10: Update register map

- recipes-kernel/linux/linux-5.10/0161-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
> hw-mgmg: patches: 5.10: Rebase after regmap changes

- recipes-kernel/linux/linux-5.10/0161-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
> hw-mgmt: pathes: 5.10: Fix patch #0161

- debian/changelog
- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
- usr/usr/bin/hw-management-start-post.sh
- usr/usr/bin/hw-management.sh
- hw-mgmt: kernels & scripts: SN2201 fixes and additions.
- hw-mgmt: kernels & script: fix CPLD PN representation on SN2201.
> V.7.0020.2100 BR

- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0161-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
> kernel: patches: 4.19/5.10: Add SPI cnhl select for NVLink managed switch

- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Fix setting for HGX H100 system

- usr/usr/bin/hw-management-global-wp.sh
- usr/usr/bin/hw-management.sh
Add init parameters for timing.
> hw-mgmt: protection: Modify global write protection script

- usr/usr/bin/hw-management-global-wp.sh
> hw-mgmt: scripts: Fix parameters for cpld update command line

- recipes-kernel/linux/linux-4.19/0151-platform-mellanox-Add-support-for-new-SN2201-system.patch
- recipes-kernel/linux/linux-5.10/0089-platform-mellanox-Add-support-for-new-SN2201-system.patch
> hw-mgmt: patches: 4.19/5.10 Fix max number of CPLD registers of SN2201 system.

- usr/usr/bin/hw-management-global-wp.sh
- usr/usr/bin/hw-management-start-post.sh
> hw-mgmt: infra: Change global write protect polarity

- usr/usr/bin/hw-management.sh
This commit fixed flow when we try to do chip up/down on the ASIC's that not
supporting this feature.
S commit fix flow when we try to do chip up/down on ASIC that no
> hw-mgmt: topology: Fix ASIC chip up/down command

- usr/etc/hw-management-sensors/p4697_sensors.conf
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Fix sensors address for SGX H100 system Fix i2c sensors address for SGX H100 system

- usr/etc/hw-management-sensors/p4697_sensors.conf
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Align ASIC i2c voltmons for P4697

- usr/usr/bin/hw-management.sh
Add msn3700 respin A1 with mps voltmon sensors
> hw-mgmt: topology: Add msn3700 respin A1 with mps voltmon

- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Fix BWD COMEX i2c sensors tree for regular version

- usr/usr/bin/hw-management-chassis-events.sh
Change logic for removed bus detection.
> hw-mgmt: topology: Fix remove line card flow

- README.md
- debian/changelog
> V.7.0099.2100 br

- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
> platform: mellanox: Add erot{X}_wp register support for NVl4 systems

- .github/workflows/build-release.yml
The following changes are made:
- Fix for lintian package download (Ticket: 1639973)
- Restricting package builds only for a published
release.
> Fixing the lintian package issue

- usr/usr/bin/hw-management.sh
1. Update voltage regulators on MQM9510 and MQM9520
2. Update temperature sensors on MQM9510 and MQM9520
> hw-mgmt: topology: Update MQM9510 and MQM9520 topologies:

- usr/etc/hw-management-sensors/mqm9510_sensors.conf
- usr/etc/hw-management-sensors/mqm9520_sensors.conf
> hw-mgmt: sensors: Add configuration files for MQM9510 and MQM9520

- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Fix A2D i2c sensors tree for mqm8700/msn4600 systems

- usr/usr/bin/hw-management.sh
> hw-mgmt: sensors: Fix config file installation for MQM9510 and MQM9520

- recipes-kernel/linux/linux-5.10/0162-platform-mellanox-Introduce-support-for-NDR-InfiniBa.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-NVLink4-mana.patch
> kernel patches: 5.10: Add support for clearing leakage sensor status

- usr/usr/bin/hw-management-chassis-events.sh
This reverts commit b3f9839273e1872370106d5806285680bc76006c.
This is has caused some breakages.
> Revert "hw-mgmt: chassis events: Fix voltmon connection by label"

- usr/usr/bin/hw-management-thermal-events.sh
> hw-mgmt: psu: Add special handling for Delta 2000 fan speed command

- usr/usr/bin/hw-management.sh
This reverts commit c917d262967fecd4e66ba836bc61dea930bb2e21.
> Revert "hw-mgmt: topology: Remove A2D i2c sensors from MSN2700/MSN2410 systems"

- usr/etc/hw-management-sensors/msn3700_A1_sensors.conf
- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Align i2c sensors tree for msn3700 respin A1

- usr/usr/bin/hw-management.sh
> hw-mgmt: attributes: Update number of CPLDs on MQM9520

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: attributes: Create leakage sensor symlinks and event files

- usr/usr/bin/hw-management-ready.sh
> Fix issue in hw-management-ready.sh which cause error on hw-management start.

- usr/usr/bin/hw-management.sh
Remove A2D i2c sensors from MSN2700/MSN2410/MSN3700 systems management + CPU board
> hw-mgmt: topology: Remove A2D i2c sensors from MSN2700/MSN2410/MSN3700 systems

- usr/usr/bin/hw-management.sh
Remove A2D i2c sensors from MSN4600C/MQM8700 systems management + CPU board
> hw-mgmt: topology: Remove A2D i2c sensors from MSN4600C/MQM8700 systems

- usr/etc/hw-management-sensors/mqm9700_rev1_sensors.conf
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: sensors: Added MQM9700 respin support

- .contrib/version_tag.py
- .github/workflows/autotag.yml
With this commit we introducing new functionality in hw-management workflow
This change provides you 2 new functions:
1. Automatically add new tag for your commit.
2. Update the changelog with the latest tag version
To add a new tag - please add the label "TAG" to your pull request.
It will take the latest tag from your branch and increment it +1
To update changelog - add the label "Update changelog" to your pull request.
You can use both labels simultaneously. In this case, tag will be
incremented and then added to changelog,
> Guthub: Add a tag to commit

- .github/workflows/autotag.yml
Change Label name for adding tag on PR. New name "Add TAG"
> Change Label name for adding tag on PR. New name "Add TAG"

- usr/usr/bin/hw-management-devtree.sh
> hw-mgmt: scripts: fix removal of component in SMBIOS BOM string.

- usr/usr/bin/hw-management-thermal-events.sh
> hw-mgmt: psu: Report Murata 2500 FW version

- usr/usr/bin/hw-management.sh
> hw-mgmt: infra: Fix PCI to I2C ASIC bus mapping on multi-asic systems

- usr/usr/bin/hw-management-if-rename.sh
Remove line card index from name
> hw-mgmt: rules: Rename line card interfaces

- usr/usr/bin/hw-management-generate-dump.sh
> hw-mgmt: dump: Add DMI type 15 to the output of dmidecode

- debian/changelog
- recipes-kernel/linux/linux-5.10/0179-DS-iio-pressure-icp20100-add-driver-for-InvenSense-ICP-.patch
- usr/etc/modules-load.d/05-hw-management-modules.conf
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: add supporrt of InvenSense ICP-201xx barometric pressure and temperature sensor.

- usr/usr/bin/hw-management-devtree.sh
> hw-mgmt: scripts: fix CFL commex bus in SMBios/devtree og legacy systems.

- usr/usr/bin/hw-management-parse-eeprom.sh
> hw-mgmt: psu: Add retry mechanism for PSU EEPROM parsing

- debian/changelog
> Update changelog to 7.0020.4030

- recipes-kernel/linux/Patch_Status_Table.txt
> hw-mgmt: patches 5.10: Fix patch status table (mp2888 patch)

- debian/changelog
- recipes-kernel/linux/linux-5.10/0178-platform-mellanox-Introduce-support-for-next-generat.patch
- usr/etc/hw-management-sensors/sn5600_sensors.conf
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts, sensors & 5.10 kernel patch: multiple changes for SN5600

- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Remove A2D component from P4697 system

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw_management_psu_fw_update_delta.py
1. Remove redundant trailing characters from Delta PSU FW version
2. Add reporting of Delta 3K PSU FW version
> hw-mgmt: psu: Report Delta 3K PSU FW version

- usr/usr/bin/hw-management.sh
>  hw-mgmt: topology: Remove A2D component from MSN4600/4700 systems

- debian/changelog
- usr/etc/hw-management-sensors/sn5600_sensors.conf
> hw-mgmt: sensors: rename SSD temperature in SN5600 config.

- README.md
> hw-mgmt: docs: correct kernel config option.

- usr/usr/bin/hw-management-thermal-events.sh
> hw-mgmt: psu: Fix PSU eeprom vpd reading

- usr/usr/bin/hw-management-thermal-events.sh
> hw-mgmt: scripts: increase scale of psu_power_capacity attribute.

- usr/usr/bin/hw-management-thermal-control.sh
Set fan not below 40% after thermal control is resumed.
> hw-mgmt: thermal: Increase fan minimum speed after suspend

- recipes-kernel/linux/linux-4.19/0011-platform-x86-mlx-platform-Modify-setting-for-new-sys.patch
- recipes-kernel/linux/linux-4.19/0027-platform-x86-mlx-platform-Remove-PSU-EEPROM-configur.patch
- recipes-kernel/linux/linux-4.19/0071-leds-mlxreg-Allow-multi-instantiation-of-same-name-L.patch
- recipes-kernel/linux/linux-4.19/0085-platform-x86-mlx-platform-Add-initial-support-for-ne.patch
- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-rack-switch-.patch
- recipes-kernel/linux/linux-4.19/0160-platform-mellanox-Introduce-support-for-rack-manager.patch
- recipes-kernel/linux/linux-5.10/0051-leds-mlxreg-Allow-multi-instantiation-of-same-name-L.patch
- recipes-kernel/linux/linux-5.10/0056-platform-x86-mlx-platform-Add-initial-support-for-ne.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-rack-manager.patch
- recipes-kernel/linux/linux-5.10/0168-TMP-mlxsw-minimal-Ignore-error-reading-SPAD-register.patch
Updating the kernel patches to remove some internal terminologies
> Removing some internal terminologies

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-4.19/0011-platform-x86-mlx-platform-Modify-setting-for-new-sys.patch
- recipes-kernel/linux/linux-4.19/0027-platform-x86-mlx-platform-Remove-PSU-EEPROM-configur.patch
- recipes-kernel/linux/linux-4.19/0071-leds-mlxreg-Allow-multi-instantiation-of-same-name-L.patch
- recipes-kernel/linux/linux-4.19/0085-platform-x86-mlx-platform-Add-initial-support-for-ne.patch
- recipes-kernel/linux/linux-4.19/0158-platform-mellanox-Introduce-support-for-rack-switch-.patch
- recipes-kernel/linux/linux-4.19/0160-platform-mellanox-Introduce-support-for-rack-manager.patch
- recipes-kernel/linux/linux-5.10/0051-leds-mlxreg-Allow-multi-instantiation-of-same-name-L.patch
- recipes-kernel/linux/linux-5.10/0056-platform-x86-mlx-platform-Add-initial-support-for-ne.patch
- recipes-kernel/linux/linux-5.10/0163-platform-mellanox-Introduce-support-for-rack-manager.patch
- recipes-kernel/linux/linux-5.10/0168-TMP-mlxsw-minimal-Ignore-error-reading-SPAD-register.patch
- recipes-kernel/linux/linux-5.10/0181-Revert-Fix-out-of-bounds-memory-accesses-in-thermal.patch
This PR is for back-porting the kernel patch renaming/changes to master branch.
> Backporting kernel patch changes to master

- recipes-kernel/linux/linux-5.10/0172-DS-platform-mlx-platform-Add-SPI-path-for-rack-switc.patch
- recipes-kernel/linux/linux-5.10/0178-platform-mellanox-Introduce-support-for-next-generat.patch
- recipes-kernel/linux/linux-5.10/0181-Revert-Fix-out-of-bounds-memory-accesses-in-thermal.patch
- recipes-kernel/linux/linux-5.10/0182-platform-mellanox-Introduce-support-of-new-Nvidia-L1.patch
- recipes-kernel/linux/linux-5.10/0183-platform-mellanox-Split-initialization-procedure.patch
- recipes-kernel/linux/linux-5.10/0184-platform-mellanox-Split-logic-in-init-and-exit-flow.patch
- recipes-kernel/linux/linux-5.10/0185-platform-mellanox-Extend-all-systems-with-I2C-notifi.patch
- usr/etc/hw-management-sensors/p4262_sensors.conf
- usr/usr/bin/hw-management-global-wp.sh
- usr/usr/bin/hw-management-thermal-control.sh
- usr/usr/bin/hw-management.sh
> V.7.0020.5000 br ranger goldstone

- recipes-kernel/linux/linux-5.10/0182-platform-mellanox-Introduce-support-of-new-Nvidia-L1.patch
- recipes-kernel/linux/linux-5.10/0183-platform-mellanox-Split-initialization-procedure.patch
- recipes-kernel/linux/linux-5.10/0184-platform-mellanox-Split-logic-in-init-and-exit-flow.patch
- recipes-kernel/linux/linux-5.10/0185-platform-mellanox-Extend-all-systems-with-I2C-notifi.patch
> hw-mgmt: Merge from development branch

- recipes-kernel/linux/Patch_Status_Table.txt
Extend table with new kernel patches.
> hw-mgmt: Patch table: Ad new patches

- usr/usr/bin/hw-management-thermal-events.sh
> hw-mgmt: psu: Add reporting of Delta PSU primary FW version

- recipes-kernel/linux/linux-4.19/0170-platform-mellanox-Fix-MQM97XX-FAN7-definitions.patch
> hw-mgmt: patches: 4.19: Fix MQM97XX FAN7 definitions

- usr/usr/bin/hw-management-thermal-events.sh
Denverton CPU on SN2201 has ridiculous CPU Core numbers 6, 12 instead 0, 1
These core id numbers also can differ in various CPU batches.
This was fixed in later version of coretemp driver e.g. in kernel 5.10.162
and core temperature is reported as in other Intel CPUs, core0 - temp2_input
core1 - temp3_input. Check this case and don't always apply workaround.
> hw-mgmt: scripts: fix cpu_core temperature links creation.

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0265-hwmon-mlxreg-fan-Return-zero-speed-for-broken-fan.patch
Add patche #0265.
Modify patch table.
> hw-mgmt: kernel patches: Add patches for fan speed fix

- recipes-kernel/linux/linux-5.10/9000-DS-iio-pressure-icp20100-add-driver-for-InvenSense-ICP-.patch
Modify downstream patch #9000 (pressure sensor)
> hw-mgmt: kernel patches: Modify pressure sensor patch

- usr/usr/bin/hw-management-devtree.sh
> hw-mgmt: scripts: comment out old systems from SMBIOS BOM support.

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-vpd-parser.py
> hw-mgmt: Add parser for system vpd

- debian/changelog
> Update hw-mgmt package version.

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management-vpd-parser.py
> Fix unknown FAN dir for fixed systems with the custom PN

- usr/usr/bin/hw-management-generate-dump.sh
> hw-mgmt: debug: Add vpd binary dump

- usr/usr/bin/hw-management-generate-dump.sh
Fix generate dump script output to file redirection
> hw-mgmt: debug: Fix generate dump script

- usr/usr/bin/hw-management-generate-dump.sh
> hw-mgmt: debug: Fix generate dump script 1. Fix command output redirect for debug dump 2. Add TC logs to debug dump

- recipes-kernel/linux/deploy_kernel_patches.py
Add kernel_deploy_patches tool
> hw-mgmt: kernel patches: Add kernel_deploy_patches tool

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0275-mlxsw-Use-u16-for-local_port-field-instead-of-u8.patch
- recipes-kernel/linux/linux-5.10/0276-mlxsw-minimal-Change-type-for-local-port.patch
- recipes-kernel/linux/linux-5.10/0277-mlxsw-i2c-Fix-chunk-size-setting-in-output-mailbox-b.patch
Add #0275 - #277 patches for minimal driver.
> hw-mgmt: patches 5.10: Add and modfiy patches

- debian/changelog
- recipes-kernel/linux/linux-5.10/0278-platform-mellanox-mlx-platform-Modify-graceful-shutd.patch
> hw-mgmt: patches 5.10: Modfiy patches

- usr/usr/bin/hw-management-chassis-events.sh
Fixing the led color change commit
> hw-mgmt: scripts: Fix led breakage

- recipes-kernel/linux/deploy_kernel_patches.py
Fix patch sourse for OSspecific patches
> hw-mgmt: kernel patches: Fix deploy patch tool

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0279-platform-mellanox-mlx-platform-Fix-signals-polarity-.patch
- recipes-kernel/linux/linux-5.10/0280-platform-mellanox-mlxreg-hotplug-Extend-condition-fo.patch
- recipes-kernel/linux/linux-5.10/0281-platform-mellanox-mlx-platform-Modify-health-and-pow.patch
> hw-mgmt: patches 5.10: Add new patches

- recipes-kernel/linux/Patch_Status_Table.txt
> hw-mgmt: Update patch table

- usr/etc/hw-management-thermal/tc_config_msn2201.json
> hw-mgmt: thermal: Fix thermal data MSN2201

- usr/usr/bin/hw_management_thermal_control.py
1. Fix TC crash on unexpected hw-mgmt folder removing
2. Code cleanup
> hw-mgmt: thermal: Fix TC crash on unexpected hw-mgmt folder removing

- debian/changelog
- usr/etc/hw-management-sensors/sn5600_sensors.conf
> hw-mgmt: sensors: fix swapped addresses of PSUs in SN5600

- usr/etc/hw-management-sensors/p4262_sensors.conf
Add scales for voltage and power calculation.
> hw-mgmt: sensors config for P4262 swicth

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/deploy_kernel_patches.py
Change patch sort rules:
Feature Upstream => Accepted
Feature Accepted => Accepted
Feature pending => Accepted
BugFix Upstream => Accepted
BugFix Accepted => Accepted
BugFix Pending => Accepted
Downstream => Candidate
New patch status:
Downstream accepted => Accepted
> hw-mgmt: patches 5.10: Change patch sort rule

- usr/usr/bin/hw-management-check-bios-update.sh
> hw-mgmt: scripts: add new script for check results of latest performed BIOS update.

- usr/usr/bin/hw_management_thermal_control.py
>  hw-mgmt: thermal: Fix FAN speed RPM validate

- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_thermal_control.py
- hw-mgmt: thermal: Update PSU FAN speed set cmd for TC
- hw-mgmt: Fix gpio controller driver check
> V.7.0030.1000 BR

- usr/usr/bin/hw_management_thermal_control.py
Fixing bug in syslog logging "Network is unreachable" when
the ip address on the lo interface gets deleted
Bug: #3445789
> hw-mgmt: thermal: Fix bug "Network is unreachable" in logger

- usr/usr/bin/hw_management_thermal_control.py
Optimized logging to reduce syslog data.
1. Redirect periodic report only to tc_log (remove it from syslog)
2. Optimize "missing sensor" error mesages. Reduce logging data
Bug: 3452101
> hw-mgmt: thermal: Fix bug "Syslog is flooded with error/warning messages"

- debian/changelog
- usr/etc/hw-management-sensors/sn5600_sensors.conf
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts: initial SN5400 support and add optional stts751 temp sensor.

- recipes-kernel/linux/linux-5.10/0282-platform-mellanox-mlx-platform-add-support-of-5th-CP.patch
Add report about 5th CPLD. SN5400 will have 5 CPLDs.
> hw-mgmt: kernel 5.10: add version, PN and minor version registers of 5th CPLD.

- debian/Release.txt
- debian/changelog
> V.7.0020.4300

- debian/changelog
- usr/usr/bin/hw_management_thermal_control.py
Add dynaic sfp module add/remove.
> hw-mgmt: thermal: Add dynamic module sensor scan

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw_management_thermal_control.py
> hw-mgmt: scripts: Fix misprint

- usr/etc/hw-management-sensors/msn27002_sensors.conf
- usr/usr/bin/hw-management.sh
> hw-mgmt: sensors: add sensor configuration for MSN27002

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0195-platform-x86-MLX_PLATFORM-select-REGMAP-instead-of-d.patch
- recipes-kernel/linux/linux-5.10/0196-platform-mellanox-Relocate-mlx-platform-driver.patch
Align patches to support 5.10.179
> hw-mgmt: kernel patches: Align patches to support 5.10.179

- usr/etc/hw-management-thermal/tc_config_msn3800.json
- usr/usr/bin/hw-management.sh
> hw-mgmt: thermal: Add thermal data for SN3800

- usr/usr/bin/hw_management_thermal_control.py
Fix cpu_pack sensor reading error handle.
> hw-mgmt: thermal: Fix cpu_pack "sensor reading error"

- usr/usr/bin/hw_management_thermal_control.py
> hw-mgmt: thermal: Add multi-ASIC support to TC

- debian/changelog
- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0284-platform-mellanox-mlx-platform-fix-CPLD4-PN-report.patch
> hw-mgmt: patches kernel 5.10: fix CPLD4 PN report.

- debian/changelog
- usr/etc/hw-management-sensors/sn5600_sensors.conf
> hw-mgmt: sensors: add alternative xdpe15284 voltage regulator to SN5600 seonsors config

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
Set attributes "events_ready" to 1 after VPD parsing is done.
> hw-mgmt: Add indicator for VPD parsing completion

- usr/usr/bin/hw_management_thermal_control.py
> hw-mgmt: thermal: Fix thermal log ASCI count info message

- usr/usr/bin/hw-management.sh
This patch reverts the change of depmod from it's original position.
>  Reverting the depmod 

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/sonic/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
> hw-mgmt: patches: align Sonic specific patches

- .github/CODEOWNERS
> Add default GitHub Code Owners

- usr/usr/bin/hw-management.sh
> hw-mgmt: thermal: Fix msn6560 tc config data link

- usr/usr/bin/hw_management_thermal_control.py
> hw-mgmt: thermal: perform TC 'stop' only from 'running' state

- usr/usr/bin/hw_management_thermal_control.py
In case if ASIC starting after TC it can set thermal zone mode to
'step_wise'.
This fix set thermal zone polict to 'user_space' after ASIC start.
> hw-mgmt: thermal: Fix ASIC tz mode

- usr/usr/bin/hw-management.sh
Use file system to store ASIC retry counter, instead of reading it from the stack.
> hw-mgmt: init: Store retry counter in file

- usr/usr/bin/hw_management_thermal_control.py
Added TC "conectx8" and BF3 "core_temp" sensors support
> hw-mgmt: thermal: Add "conectx8" and BF3 "core_temp" TC sensors support

- usr/etc/hw-management-thermal/tc_config_msn3750.json
- usr/usr/bin/hw-management.sh
Add msn3750 system support to TC
> hw-mgmt: thermal: Add new system support to TC

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0284-platform-mellanox-mlx-platform-fix-CPLD4-PN-report.patch
Modify status for patches: #0172 and #0284.
> hw-mgmt: patches: Modify status table for canonical build

- recipes-kernel/linux/linux-6.1/patchwork/0012-platform-mellanox-Fix-order-in-exit-flow.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0013-platform-mellanox-mlx-platform-Fix-signals-polarity-.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0014-platform-mellanox-mlx-platform-Modify-graceful-shutd.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0015-platform-mellanox-Change-register-offset-addresses.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0016-platform-mellanox-Add-new-attributes.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0017-platform-mellanox-Add-field-upgrade-capability-regis.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0018-platform-mellanox-Modify-reset-causes-description.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0019-platform-mellanox-mlx-platform-Modify-health-and-pow.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0020-platform-mellanox-mlx-platform-Add-reset-cause-attri.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0021-platform-mellanox-mlx-platform-add-support-for-addit.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0022-platform-mellanox-mlx-platform-Modify-power-off-call.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0023-platform-mellanox-Cosmetic-changes.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0024-platform-mellanox-mlx-platform-Add-reset-callback.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0025-platform-mellanox-mlx-platform-Prepare-driver-to-all.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0026-platform-mellanox-mlx-platform-Introduce-ACPI-init-f.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0027-platform-mellanox-mlx-platform-Get-interrupt-line-th.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0028-platform-mellanox-Add-initial-support-for-PCIe-based.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0030-platform-mellanox-nvsw-sn2201-change-fans-i2c-busses.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0033-i2c-mlxcpld-Allow-driver-to-run-on-ARM64-architectur.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0034-i2c-mlxcpld-Add-support-for-extended-transaction-len.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0036-mlxsw-i2c-Fix-chunk-size-setting-in-output-mailbox-b.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0037-mlxsw-i2c-Limit-single-transaction-buffer-size.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0038-mlxsw-core_hwmon-Adjust-module-label-names-based-on-.patch
- recipes-kernel/linux/linux-6.1/patchwork/0039-mlxsw-reg-Limit-MTBR-register-payload-to-a-single-da.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0040-mlxsw-core-Extend-allowed-list-of-external-cooling-d.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0041-mlxsw-i2c-Utilize-standard-macros-for-dividing-buffe.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0045-leds-mlxreg-Remove-code-for-amber-LED-colour.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0050-leds-mlxreg-Skip-setting-LED-color-during-initializa.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0052-i2c-mux-Add-register-map-based-mux-driver.patch.txt
Reviewed-by: Oleksandr Shamray <oleksandrs@nvidia.com>
> hw-mgmt: kernel: Add link to patchwork

- debian/changelog
> hw-mgmt: version: Update changelog

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/0085-hwmon-mlxreg-fan-Separate-methods-of-fan-setting-com.patch
- recipes-kernel/linux/linux-6.1/patchwork/0077-UBUNTU-SAUCE-mlx-bootctl-support-icm-carveout-eeprom.patch.txt
- recipes-kernel/linux/linux-6.1/patchwork/0078-UBUNTU-SAUCE-mlxbf-bootctl-support-SMC-call-for-sett.patch.txt
Add new patchwork links.
Add patch #0085.
Reviewed-by: Oleksandr Shamray <oleksandrs@nvidia.com>
> hw-mgmt: patches: Update patchwork links and add new patch

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0067-platform-mellanox-Add-dedicated-match-for-system-typ.patch
- recipes-kernel/linux/linux-5.10/0097-1-mlxsw-Use-u16-for-local_port-field.patch
- recipes-kernel/linux/linux-5.10/0097-2-mlxsw-i2c-Fix-chunk-size-setting.patch
- recipes-kernel/linux/linux-5.10/0097-3-mlxsw-core_hwmon-Adjust-module-label-names.patch
- recipes-kernel/linux/linux-5.10/0098-1-Revert-mlxsw-Use-u16-for-local_port-field.patch
- recipes-kernel/linux/linux-5.10/0098-2-Revert-mlxsw-i2c-Fix-chunk-size-setting.patch
- recipes-kernel/linux/linux-5.10/0098-3-Revert-mlxsw-core_hwmon-Adjust-module-label-names.patch
- recipes-kernel/linux/linux-5.10/0152-mlxsw-i2c-Prevent-transaction-execution-for-spec.patch
- recipes-kernel/linux/linux-5.10/0153-mlxsw-i2c-Add-support-for-system-events-handling.patch
Align patch table to match Sonic canonical build.
> hw-mgmt: patches: Align patch table

- recipes-kernel/linux/deploy_kernel_patches.py
We have different kernel CONFIG_* sets for different ARCH.
With this commit, we added the option to select ARCH in patch_deploy_tool
--arch {amd64,arm64}  Arch type amd64/arm64/... (default: amd64)
> hw-mgmt: patches 5.10: Add ARCH select support to patch_deploy_tool

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0307-leds-mlxreg-Add-support-for-new-flavour-of-capabilit.patch
- recipes-kernel/linux/linux-5.10/0308-leds-mlxreg-Remove-code-for-amber-LED-colour.patch
- recipes-kernel/linux/linux-5.10/0308-platform_data-mlxreg-Add-capability-bit-and-mask-fie.patch
- recipes-kernel/linux/linux-5.10/0309-hwmon-mlxreg-fan-Add-support-for-new-flavour-of-capa.patch
- recipes-kernel/linux/linux-5.10/0310-hwmon-mlxreg-fan-Extend-number-of-supporetd-fans.patch
> hw-mgmt: patches: 5.10: Update LED and fan patches

- usr/etc/hw-management-thermal/tc_config_msn27002.json
- usr/etc/hw-management-thermal/tc_config_msn5400.json
- usr/usr/bin/hw-management.sh
> hw-mgmt: thermal: Add thermal data for msn27002/msn5400 systems

- usr/usr/bin/hw-management.sh
Fix missing voltmon links for msn4700 bf3 system
Bug:  #3613781
> hw-mgmt: scripts: Fix missing voltmon links for msn4700 bf3 system

- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw_management_thermal_control.py
- hw-mgmt: thermal: Add links to BF3 core_temp/ddr_temp temperature
- hw-mgmt: thermal: TC add sensor *_scale support
> V.7.0030.3000 BR

- usr/usr/bin/hw_management_thermal_control.py
> hw-mgmt: thermal: Set thermal sensor_read_err only for thermal sensors type

- usr/usr/bin/hw_management_thermal_control.py
> hw-mgmt: thermal: Add TC error mask feature support

- usr/etc/hw-management-thermal/tc_config_msn4700_mps.json
- usr/usr/bin/hw-management.sh
> hw-mgmt: thermal: Add thermal data for msn4700 with mps voltmon system

- debian/rules
This patch updates the hw-management .deb package
to include the new files created under
/etc/hw-management-virtual directory.
> Update hw-management deb package

- usr/usr/bin/hw_management_thermal_control.py
Fix issue:  Logging Error in TC Log writing dmesg: RuntimeError: reentrant call inside
Bug: 3630148
> hw-mgmt: thermal: Fix issue "RuntimeError: reentrant call inside"

- usr/usr/bin/hw_management_thermal_control.py
> hw-mgmt: thermal: code cleanup and beautifying

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_independent_mode_update.py
Motivation is to provide API for setting temperatures by OS.
> hw-mgmt: infra: Add basic infrastructure for independent mode support

- debian/changelog
- hw-mgmt: patches: Add patches for v6.1
- V.7.0030.2007 Update changelog
> V.7.0030.2000 BR

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-vpd-parser.py
Upgrade VPD parser
1. Add ONIE vendor specific field decoder for MLNX format
2. SYSTEM_VPD decode upport (ONIE + MLNX)
3. MLNX_CPU_CPD decode support (MLNX)
4. MLNX_FAN_VPD decode support (MLNX)
5. Add autodetect ONIE/MLNX format
> hw-mgmt: scripts: Upgrade VPD parser

- recipes-kernel/linux/linux-5.10/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
> hw-mgmt: pathes: v5.10: Modify patch for mp2891 device

- usr/usr/bin/hw-management-devtree.sh
Detect the following new categories in SMBIOS BOM string:
1. Network Device
2. GPIO Expander
3. Jitter Attenuator
4. Oscillator
> hw-mgmt: devtree: Add detection of new device categories

- usr/usr/bin/hw-management-vpd-parser.py
Fix vpd parser to support DPU block
> hw-mgmt: scripts: Fix vpd parser to support DPU block

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/9003-platform-mellanox-Introduce-support-of-Nvidia-L1-tra.patch
- recipes-kernel/linux/linux-6.1/9003-platform-mellanox-Introduce-support-of-Nvidia-L1-tra.patch
- usr/etc/hw-management-sensors/p4300_sensors.conf
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Add support for new system P4300
> hw-mgmt: Add support for new system P4300

- recipes-kernel/linux/linux-5.10/sonic/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
> hw-mgmt: pathes (sonic): v5.10: Modify patch for mp2891 device

- usr/etc/hw-management-thermal/tc_config_qm3400.json
- usr/usr/bin/hw_management_thermal_control.py
1. TC fix periodic report message for >2 error
2. TC fix thermal data for qm3400
3. TC Fix spelling
> hw-mgmt: thermal: TC fix periodic report message for >2 error

- usr/usr/bin/hw_management_thermal_control.py
TC fix crash on FAN disconnect. This fix for code which
was added in previous commit
> hw-mgmt: thermal: TC fix crash on FAN disconnect.

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/9003-DS-OPT-mlxsw-minimal-Downstream-Disable-ethtool-interface.patch
Add temporary mlxsw_minimal driver patch to disable ethtool interface
> hw-mgmt: patches: Add temporary mlxsw_minimal driver patch

- debian/changelog
- usr/usr/bin/hw-management.sh
This patch fixes the issue while finding the asic hwmon path existance.
Bugs: #3719967
> hw-mgmt: scripts: Fix asic hwmon retry

- usr/usr/bin/hw_management_thermal_control.py
Add to TC a new feature for device redundancy.
Minimum number of PSUs to be considered as "PSU prsnt" error. 
Additional "PSU prsnt" error will be considered as ">=2 errors".
Minimum number of Fans to be considered as Fan error. Additional any 
FAN error (prsnt, TACHO, direction) will be considered as ">=2 errors".
Optionally, for the "REDUNDANT" rule list of errors can be configured.
For example, for PSU can be enabled only "PSU prsnt" error and all other 
errors are to be handled as usual.
These redundancy rules also can coexist with "error_mask" feature. 
While "error_mask" has the highest priority than REDUNDANCY. 
For example, if system has 5+2 fans, "min_err_cnt" parameter = 2.
This means if 1 fan has an error, it will be ignored by TC.
If additional fan will have an error, TC will …
> dd to TC a new feature for device redundancy.

- usr/etc/hw-management-thermal/tc_config_sn4280.json
- usr/usr/bin/hw-management.sh
Add thermal data for smart switch
> hw-mgmt: thermal: Add thermal data for smart switch

- recipes-kernel/linux/linux-5.10/0334-platform-mellanox-Introduce-support-of-Nvidia-smart-.patch
- recipes-kernel/linux/linux-5.10/9003-platform-mellanox-Introduce-support-of-Nvidia-L1-tra.patch
- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- usr/usr/bin/hw-management.sh
Add offset for smart switch COME I2C bus.
Modify kernel patches.
Remove 3-rd DPU voltage regulator.
> hw-mgmt: topology: Modify topology for SN4280 system

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
This commits does the following:
- Update VR addresses for Comex
- Fixes number of Tachos to for FANs
- Fixes the duplicate calls for cpu bus
> hw-mgmt: scripts: Come sensor updates for smart switch

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/0042-hwmon-mlxreg-fan-Add-support-for-new-flavour-of-capa.patch
- recipes-kernel/linux/linux-6.1/0043-hwmon-mlxreg-fan-Extend-number-of-supporetd-fans.patch
- recipes-kernel/linux/linux-6.1/0044-leds-mlxreg-Add-support-for-new-flavour-of-capabilit.patch
- recipes-kernel/linux/linux-6.1/0045-leds-mlxreg-Remove-code-for-amber-LED-colour.patch
- recipes-kernel/linux/linux-6.1/0048-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-6.1/0050-leds-mlxreg-Skip-setting-LED-color-during-initializa.patch
- recipes-kernel/linux/linux-6.1/0085-hwmon-mlxreg-fan-Separate-methods-of-fan-setting-com.patch
- recipes-kernel/linux/linux-6.1/0087-platform_data-mlxreg-Add-capability-bit-and-mask-fie.patch
- recipes-kernel/linux/linux-6.1/0088-platform-mellanox-mlxreg-hotplug-Add-support-for-new.patch
- recipes-kernel/linux/linux-6.1/0089-platform-mellanox-mlx-platform-Change-register-name.patch
- recipes-kernel/linux/linux-6.1/0090-platform-mellanox-mlx-platform-Add-support-for-new-X.patch
- recipes-kernel/linux/linux-6.1/0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
- recipes-kernel/linux/linux-6.1/0092-platform-mellanox-Introduce-support-of-Nvidia-smart-.patch
- recipes-kernel/linux/linux-6.1/0093-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2855-c.patch
- recipes-kernel/linux/linux-6.1/8002-platform-mlx-platform-Downstream-Add-SPI-path-for-ra.patch
- recipes-kernel/linux/linux-6.1/8005-leds-leds-mlxreg-Downstream-Send-udev-event-from-led.patch
- recipes-kernel/linux/linux-6.1/8007-hwmon-mlxreg-fan-Downstream-Allow-fan-speed-setting-.patch
- recipes-kernel/linux/linux-6.1/8011-mlxsw-minimal-Downstream-Disable-ethtool-interface.patch
- recipes-kernel/linux/linux-6.1/9003-platform-mellanox-Introduce-support-of-Nvidia-L1-tra.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9005-platform-mellanox-Downstream-Add-dedicated-match-for.patch
- recipes-kernel/linux/linux-6.1/patchwork/0048-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch.txt
Update and add kernel patches and modify table.
> hw-mgmt: patches: 6.1: Update kernel patches

- usr/usr/bin/hw_management_thermal_control.py
> hw-mgmt: thermal: TC code cleanup

- usr/etc/hw-management-thermal/tc_config_sn4280.json
Update thermal data for smart switch
> hw-mgmt: thermal: Update thermal data for smart switch

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Add hotplug hooks for DPU devices.
> hw-mgmt: topoogy: Add dynamic devices for smart switch

- recipes-kernel/linux/linux-5.10/0333-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
- recipes-kernel/linux/linux-5.10/0334-platform-mellanox-Introduce-support-of-Nvidia-smart-.patch
- recipes-kernel/linux/linux-5.10/9003-platform-mellanox-Introduce-support-of-Nvidia-L1-tra.patch
- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
> hw-mgmt: patches: v5.10: Update patches

- usr/usr/bin/hw-management-devtree.sh
> Update SMBios components of SN4280 system.

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/0094-i2c-asf-Introduce-MCTP-support-over-ASF-controller.patch
Add patch for AMD/ASF master/slave SMBus driver.
> hw-mgmt: patches: v6.1: Add AMD master/slave driver

- usr/usr/bin/hw-management.sh
> hw-management: scripts: Add GPIO configuration for AMD Comex.

- recipes-kernel/linux/linux-6.1/8011-mlxsw-minimal-Downstream-Disable-ethtool-interface.patch
Disable 'ethtool' interface, since it is un-used and just created un-necessary 'netdevice' interfaces.
> Disable 'ethtool' interface,

- recipes-kernel/linux/linux-5.10/sonic/0144-mlxsw-core-Introduce-flash-update-components.patch
Customization to avoid applying conflicts with SDK.
> hw-mgmt: pathes: sonic: Add custom devlink patch

- debian/changelog
> Update changelog V.7.0030.3006

- usr/usr/bin/hw-management.sh
Correct the Max/Min rpm for system fans.
Bugs: 3835080
> hw-mgmt: scripts: Fix fan rpm config for smart switch

- usr/usr/bin/hw-management.sh
Increase for SP1/SPC2 systems only.
Fix: #3748535.
> hw-mgmt: infra: Increase time for validation chip hwmon object creation

- usr/usr/bin/hw-management.sh
Set "not supported" TC config for SGN2410 system
3847741
> hw-mgmt: thermal: Fix TC data for SGN2410 system

- usr/usr/bin/hw-management-pldm-fw-update.sh
This commit adds the ability to query the Firmwware inventory on the pldm update service.
> hw-mgmt: scripts: pldm fw update: Firmware Inventory

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/deploy_kernel_patches.py
- hw-mgmt: patches: Add nvos type for --os argument patch_deploy_tool
- hw-mgmt: patches: Add dvs type for --os_type argument patch_deploy_tool
> V.7.0030.4000 BR

- README.md
- debian/control
- debian/rules
- usr/etc/hw-management-thermal/tc_config_msn3420.json
- w-mgmt: thermal: fixed of sporadically FAN fail issue on msn3410
- hw-mgmt: package: Set lm_sensor dependency as selectable parameter
> V.7.0040.1000 BR

- usr/etc/modprobe.d/hw-management.conf
- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-ready.sh
- usr/usr/bin/hw-management.sh
> hw-mgmt: topology: Initial commit for n5110ld

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/deploy_kernel_patches.py
- recipes-kernel/linux/linux-5.10/dvs/0013-hwmon-pmbus-shrink-code-and-remove-pmbus_do_remove.patch
- recipes-kernel/linux/linux-5.10/dvs/0036-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2888-c.patch
- recipes-kernel/linux/linux-5.10/dvs/0144-mlxsw-core-Introduce-flash-update-components.patch
- recipes-kernel/linux/linux-5.10/dvs/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/dvs/0318-mellanox-Relocate-mlx-platform-driver.patch
- recipes-kernel/linux/linux-5.10/dvs/0336-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2855-c.patch
- recipes-kernel/linux/linux-5.10/nvos/0013-hwmon-pmbus-shrink-code-and-remove-pmbus_do_remove.patch
- recipes-kernel/linux/linux-5.10/nvos/0036-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2888-c.patch
- recipes-kernel/linux/linux-5.10/nvos/0144-mlxsw-core-Introduce-flash-update-components.patch
- recipes-kernel/linux/linux-5.10/nvos/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/nvos/0318-mellanox-Relocate-mlx-platform-driver.patch
- recipes-kernel/linux/linux-5.10/nvos/0336-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2855-c.patch
- recipes-kernel/linux/linux-5.10/opt/0013-hwmon-pmbus-shrink-code-and-remove-pmbus_do_remove.patch
- recipes-kernel/linux/linux-5.10/opt/0036-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2888-c.patch
- recipes-kernel/linux/linux-5.10/opt/0144-mlxsw-core-Introduce-flash-update-components.patch
- recipes-kernel/linux/linux-5.10/opt/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/opt/0318-mellanox-Relocate-mlx-platform-driver.patch
- recipes-kernel/linux/linux-5.10/opt/0336-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2855-c.patch
Add per OS folder for patch_deploy tool
> hw-mgmt: patches: Add per OS folder for patch_deploy tool

- usr/usr/bin/hw-management-vpd-parser.py
Add 'hidden' verbode output option to VPD parser for in-system VPD data debug
> hw-mgmt: scripts: Add 'hidden' trace option for VPD parser debug

- usr/etc/hw-management-sensors/n5110ld_sensors.conf
Add pwr_conv sensor definition for n5110_ld lm sensors conf file
> hw-mgmt: topology: Update lm sensors conf for n5510_ld

- debian/changelog
> Update changelog V.7.0040.0034

- usr/etc/hw-management-thermal/tc_config_n5110ld_ttm.json
- usr/usr/bin/hw-management.sh
Fix n5110_LD TTM fan/drwr count
fan = 8
drwr = 4
> hw-mgmt: topology: Fix n5110_LD TTM fan/drwr count

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
This commit addresses the system reboot & hw-mgmt restart flows for:
- Dynamic dpu sensor loading
- DPU hotplug events
> hw-mgmt: scripts: Fix DPU events and sensor loading

- debian/rules
- usr/etc/systemd/network/70-redfish-static.network
This reverts commit 323d1614fbf8e23a497aca46dfe70cd5e2934ee3.
> Revert "hw-mgmt: Add network configuration for usb0 adapter"

- debian/changelog
> Update changelog V.7.0040.1030

- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9005-platform-mellanox-Downstream-Add-dedicated-match-for.patch
1. Add support for new SKU: HI162: N5110_LD HI166: N5110_LD TTM HI167: N5100
2. Add support for new CPLD version
> Ehw-mgmt: patches: kernel 5.10/6.1: Update N51XX platform patch

- usr/usr/bin/hw_management_thermal_control.py
Add validation for abnormal FAN tacho count in DRWR
> hw-mgmt: thermal: TC add more robustness on FAN init

- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9005-platform-mellanox-Downstream-Add-dedicated-match-for.patch
Fix fan count for N51XX platform
> hw-mgmt: patches: kernel 5.10/6.1: Fix fan count for N51XX platform

- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts: Fix power events init

- usr/usr/bin/hw_management_sync.py
Fix sync script: set ystem differentiate by SKU instead of system type
Bug: 4013975
> hw-mgmt: scripts: Fix attribute sync

- recipes-kernel/linux/linux-5.10/dvs/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/nvos/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/opt/0294-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
This commit updates mp2891 driver for various NOSs.
Bug #3962952
> hw-mgmt: patches: Update mp2891 driver

- usr/etc/hw-management-sensors/sn2201_sensors.conf
- usr/etc/hw-management-thermal/tc_config_msn2201_busbar.json
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management.sh
SN2201, SKU:HI168
Add PDB board support for new SN2201, SKU:HI168 in hw-mgmt package.
Signed-off-by: Claud Chang <claud.chang@deltaww.com>
> Add PDB board support for new

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Clean leftovers after removing TC ver 1.0
> hw-mgmt: scripts: Clean leftovers after removing TC ver 1.0

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0337-crypto-ccp-Reject-SEV-commands-with-mismatching-comm.patch
- recipes-kernel/linux/linux-5.10/0338-crypto-ccp-Play-nice-with-vmalloc-d-memory-for-SEV-c.patch
Add upstream bugfix patches for crypto CCP driver
Bug #3896662
> hw-mgmt: kernel: patches: 5.10: Add upstream bugfix patches

- debian/changelog
> Update changelog V.7.0040.1034

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-6.1/0095-platform-mellanox-nvsw-sn2201-Add-support-for-new-sy.patch
- usr/etc/hw-management-sensors/sn2201_sensors.conf
- usr/etc/hw-management-thermal/tc_config_msn2201_busbar.json
- usr/lib/udev/rules.d/50-hw-management-events.rules
- usr/usr/bin/hw-management.sh
- hw-mgmt: patches: 6.1: Add patch for new SN2201 modification
- hw-mgmt: patches: 6.1: Update patch for new SN2201 modification
- Add PDB board support for new
- hw-mgmt: patches: 6.1: Update SN2201 patch for busbar system
> V.7.0040.2000 BR

- debian/changelog
> Update changelog V.7.0040.1035

- debian/changelog
> Update changelog V.7.0040.1014

- usr/usr/bin/hw-management-generate-dump.sh
Add hw-mgmt package version to debug dump
> hw-mgmt: dump: Add package version to debug dump

- usr/usr/bin/hw-management.sh
Issue: update license header of one file
Reviewed By: soleksandr
Testing Done: no
update license header of only one file
> update license header

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0246-mlxsw-i2c-Fix-chunk-size-setting-in-output-mailbox-b.patch
- recipes-kernel/linux/linux-5.10/0300-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2855-c.patch
> Fix kernel patches table for 5.10

- usr/usr/bin/hw_management_sync.py
Add sync for asics_init_done attribute
> hw-mgmt: scripts: add sync for asics_init_done attribute

- recipes-kernel/linux/deploy_kernel_patches.py
> hw-mgmt: patches: fix patch deploy tool

- recipes-kernel/linux/linux-6.1/0097-platform-mellanox-mlx-platform-Add-support-for-new-N.patch
- recipes-kernel/linux/linux-6.1/9003-platform-mellanox-Introduce-support-of-Nvidia-L1-tra.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- usr/usr/bin/hw_management_sync.py
1. Add kernel support for SN5640 sku:HI172
2. Fix ASIC count for SN5640
> hw-mgmt: patches: 6.1: Add support for SN5640 sku HI172

- usr/usr/bin/hw-management-devtree.sh
> Add new Renesas power-converter in devtree parsing.

- usr/usr/bin/hw_management_thermal_control.py
In the BMC based platforms, during the BMC reset
workflow, i2c bus control will be taken over by BMC. This commit introduces a check to see if the cpu
owns the i2c bus control before reading the sensors and suspends the TC daemon till the BMC relinquishes the i2c bus control back to cpu.
Issue #4075077
> hw-mgmt: thermal: Check for i2c bus owner

- debian/changelog
Update changelog to V.7.0040.2010
> Update changelog to V.7.0040.2010

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-start-post.sh
Add fix for N5xxx with new power converster
> hw-mgmt: config: Add fix for N5xxx with new power converter

- recipes-kernel/linux/linux-5.10/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/dvs/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/nvos/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/opt/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-5.10/sonic/0261-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
- recipes-kernel/linux/linux-6.1/0048-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2891-c.patch
> hw-mgmt: patches: Fix mp2891 threshold limits

- debian/changelog
- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_dpu_thermal_update.py
This commit does the following:
- Correct the dpu_num path
- Copy the dpu thermal script to /var/run/hw-management/bin/
Bugs #417374 #4170646
> hw-mgmt: scripts: Update dpu thermal script

- usr/etc/hw-management-sensors/n52xxld_sensors_labels.json
- usr/usr/bin/hw-management-labels-maker.sh
- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_parse_labels.py
Add BOM mapping for sensors labeling
> Add BOM mapping for sensors labeling

- usr/usr/bin/hw_management_redfish_client.py
Update redfish client get_pass_login function : sync with NVOS code
Bug: 4176442
> hw-mgmt: scripts: Update redfish client get_pass_login

- debian/changelog
- usr/usr/bin/hw_management_sync.py
- hw-mgmt: attributes: Fix PSU volt out attributebute
- hw-mgmt: attributes: Fix module temp input mame in sync script
- hw-mgmt: attributes: Fix module temp input count for 5610
- Update checngelog
> V.7.0040.3000 BR

- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw_management_sync.py
- hw-mgmt: topology: Add devtree support for lm90, tmp411 temperature sensors
- hw-mgmt: scripts: Fix ASIC temp populate in hw-mgmt-sync script
- hw-mgmt: attributes: Fix module temp input name in sync script
> V.7.0040.1500 for QS

- usr/etc/hw-management-thermal/tc_config_sn5610.json
- usr/usr/bin/hw-management.sh
Add Thermal config for SN5610
Bug: 4200580
> hw-mgmt: config: Add Thermal config for SN5610

- .pulse-trufflehog-allowlist.json
> Add Trufflehog Scan exception for hw_management_redfish_client.py

- usr/lib/udev/rules.d/76-hw-management-bmc.rules
Add rules for plugin/plugout USB net interface connecting CPU host and BMC.
Bug: 4146744
> hw-mgmt: rules: Add rules for network interface

- usr/etc/hw-management-sensors/n51xxld_sensors.conf
- usr/usr/bin/hw-management-devtree.sh
1. Fix lm90 sensor bus addr 20 -> 6
2. Fix FPGA thermal sensor description
Bug: #4207762
> hw-mgmt: attributes: Fix PDB thermal sensor name/address

- usr/usr/bin/hw_management_sync.py
- hw-mgmt: scripts: Fix module reading in sync script
- hw-mgmt: scripts: Fix asic_chipup_completed for systems without minimal driver
> V.7.0040.1800 BR

- usr/usr/bin/hw_management_sync.py
- usr/usr/bin/hw_management_thermal_control.py
1. Fix PWM change reason - update reason in case >= 2 errors
condition set/clear
2. Set sensor value status to "M/A" in case of sensor read error
3. Set amb sensor status to "N/A" in case of all amb sensor read error
Bug: 4220139
> hw-mgmt: thermal: TC Fix debug log printouts

- usr/usr/bin/hw_management_thermal_control.py
TC add check for abnmormal values on termal sensors.
For example:
ASIC temperature can't be 0 (Possible switch installed outside at Arctic?)
In case of abnormal temperature readed - assume sensor_read_error
hasppens.
Bug: NA (internal)
> hw-mgmt: thermal: TC add check for abnmormal values on termal sensors

- usr/usr/bin/hw_management_thermal_control.py
TC add more debug printouts
Bug: N/A
> hw-mgmgt: thermal: TC add more debug printouts

- usr/usr/bin/hw-management.sh
Fix reset count validation after removing several reset flags in
platform driver
Bug: 4237150
> hw-mgmt: config: Fix N5XXX reset count

- usr/etc/hw-management-thermal/tc_config_q3450.json
- usr/usr/bin/hw_management_thermal_control.py
- hw-mgmt: thermal: add PCH thermal sensor support
- hw-mgmt: thermal: Add thermal data for QM3450
> V.7.0040.3000 Q3450

- usr/usr/bin/hw_management_sync.py
If SDK is in independent mode - ASIC/module temperature should
be updated by OS. This fix disable hw-mgmgt ASIC temperature sync
update if independent mode enabled.
Bug: 4219397
> hw-mgmt: script: fix update asic temp independent mode

- usr/usr/bin/hw_management_thermal_control.py
> Add support of lcrit/hcrit to asic/amb sensor

- debian/changelog
> Update version V.7.0040.2107

- usr/usr/bin/hw-management-chassis-events.sh
There is a problem in VCORE output of VR on Comex board. This output depends
on CPU frequency and according to MPS vendor theoretically can be 0.
Thus reported low critical should be 0 too.
Currently problem is reported just for CFL CPU comex VR.
Bug: 4184688
> hw-mgmt: script: Fix CPU VR Vcore out of range problem.

- usr/usr/bin/hw_management_redfish_client.py
Fix redfish login issue. Was incorrect tpm read command
Bug: 4250700
> hw-mgmgt: script: Fix redfish login issue

- usr/usr/bin/hw_management_thermal_control.py
Fix Fan_blacklist not working issue
Bug: 4256275
> hw-mgmt: thermal: TC fix blacklist not working issue

- usr/usr/bin/hw-management.sh
Fix tehermal control config for SN5640/5610
Bug: 4281218
> hw-mgmt: thermal: Fix tehermal control config for SN5640/5610

- usr/usr/bin/hw-management-devtree.sh
Add new devices: VR, power convertor, hotsawp.
Add templates for GB300 and GB200HD.
> hw-mgmt: devtree: Extend BOM with new device for GB200HD/GB300 L1 switch

- usr/usr/bin/hw-management.sh
Fix thermal control config for SN5640/5610
Bug: 4281218
> hw-mgmt: thermal: Fix thermal control config for SN5640/5610

- .github/CODEOWNERS
- usr/usr/bin/hw-management-devtree.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-thermal-events.sh
- usr/usr/bin/hw-management.sh
- usr/usr/bin/hw_management_dpu_thermal_update.py
- Update changelog to V.7.0040.2010
- hw-mgmt: scripts: Fix Q3400 sensor label file name
- hw-mgmt: config: Add fix for N5xxx with new power converter
- hw-mgmt: patches 6.1: Add patch to fix uninitialized variable
- hw-mgmt: patches: Update mp2891 threshold limits
- hw-mgmt: patches: Fix mp2891 threshold limits
- hw-mgmt: scripts: Update dpu thermal script
- hw-mgmt: topology: Fix ui folder for Juliet with new PDB
- hw-mgmt: topology: Fix ui labels parding for drivetemp sensor
- hw-mgmt: topology: Fix missing endline character in ./asic1
- hw-mgmt: topology: Add TC component monitoring based on devtree
- hw-mgmt: thermal: TC Fix log for PSU pwm update
- hw-mgmt: config: Add fix for N5xxx with new power converter
- hw-mgmt: patches: Update mp2891 threshold limits
- hw-mgmt: patches: Fix …
> V.7.0040.3000 kyber3 gb300 dev

- usr/usr/bin/hw-management-devtree.sh
Align between host CPU and BMC.
> hw-mgmt: BOM: Align BOM data base

- recipes-kernel/linux/Patch_Status_Table.txt
- recipes-kernel/linux/linux-5.10/0307-platform_data-mlxreg-Add-fields-for-interrupt-storm-.patch
- recipes-kernel/linux/linux-5.10/0308-platform-mellanox-mlxreg-hotplug-Add-support-for-han.patch
- recipes-kernel/linux/linux-6.1/0101-platform_data-mlxreg-Add-fields-for-interrupt-storm-.patch
- recipes-kernel/linux/linux-6.1/0102-platform-mellanox-mlxreg-hotplug-Add-support-for-han.patch
mlxreg-hotplug: Add support for handling interrupt storm. Updated patch status table.
> Added kernel patches for interrupt storm protection.

- recipes-kernel/linux/linux-5.10/9005-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
- recipes-kernel/linux/linux-6.1/9004-platform-mellanox-Downstream-Introduce-support-of-Nv.patch
Update pathes 5.10/#9005 and 6.1/#9004.
> hw-mgmt: patches: Add reset_platform cuase

- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
Temporarily enable traces of power converter initialization on SN5600 to catch very rare initialization failures.
Bug: 4252430
> hw-mgmt: scripts: Add tracing of power converter devices on SN5600

- recipes-kernel/linux/linux-5.10/0308-platform-mellanox-mlxreg-hotplug-Add-support-for-han.patch
- recipes-kernel/linux/linux-6.1/0102-platform-mellanox-mlxreg-hotplug-Add-support-for-han.patch
Fix for interrtupt counter time of use and time of check. 
Fix for window and current timestamp comparison.
> Kernel patches: interrupt storm handling patches

- debian/hw-management.hw-management-fast-sysfs-monitor.init
- debian/hw-management.hw-management-sysfs-monitor.init
- usr/lib/udev/rules.d/49-hw-management-fast-events.rules
- usr/usr/bin/hw-management-fast-sysfs-monitor.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management-sysfs-monitor.sh
1. Removed 'bc' tool usage which is missing from Sonic.
2. Added further optimization for fast boot.
> hw-mgmt: services: fast sysfs monitor services

- debian/changelog
> Update changelog to V.7.0040.1873

- debian/changelog
> Update changelog to V.7.0040.3935

- usr/usr/bin/hw-management-chassis-events.sh
- usr/usr/bin/hw-management.sh
Dummy PSUs may be installed instead of real PSUs to ensure the proper chassis air flow on systems where some real PSUs are missing. Such PSUs have presence bit but do not show up on I2C bus. To differentiate them from real PSUs that are not connected to power add the code to detect them during boot and hotplug and create psuN_is_dummy attributes.
Bug: 4343164
> hw-mgmt: scripts: Add detection of dummy PSUs on Q3200/Q3400 systems

- usr/usr/bin/hw-management.sh
> hw-mgmt: scripts: Fix min chassis fan RPM on SN5610/SN5640 systems

- .pulse-trufflehog-allowlist.json
- usr/usr/bin/hw_management_thermal_control.py
hw-mgmgt: thermal: TC fix redundancy config reading from tc_config.json
>  hw-mgmgt: thermal: TC fix redundancy config reading from tc_config.json

- usr/usr/bin/hw_management_sync.py
Fix ASIC attribues sync
Bug: 4280981
> hw-mgmgt: scripts: Fix ASIC attributes sync

- .pulse-trufflehog-allowlist.json
> Update Trufflehog Scan exception list

- usr/usr/bin/hw-management-chassis-events.sh
When real PSU is inserted, it takes several seconds for relevant I2C device to be created. Dummy PSUs have no I2C device associated with them. The code that checks if inserted PSU is dummy does not take the aforementioned delay into account and can erroneously mark real PSU as dummy. Fix that by adding retries and delays to dummy PSU detection code.
Bug: 4176785
> hw-mgmt: scripts: Fix dummy PSU detection during PSU hotplug events

- recipes-kernel/linux/linux-6.1/cumulus/0091-platform-mellanox-mlxreg-dpu-Add-initial-support-for.patch
Fix CL specific patch 0091-* which block 0103-* patch apply
Bug: 4426244
> hw-mgmt: patches: kernel 6.1: Fix CL patch apply

- usr/etc/hw-management-thermal/tc_config_sn5640.json
- usr/usr/bin/hw-management-start-post.sh
- usr/usr/bin/hw_management_thermal_control.py
- Revert "Revert "hw-mgmgt: thermal: TC fix redundancy config reading from tc_config.json""
- Revert "Revert "hw-mgmgt: thermal: Add TC parameter to configure PWM update time""
- Revert "Revert "TC: increase thermal calculation precision""
- Revert "Revert "TC: increase thermal calculation precision""
- Revert "Revert "hw-mgmgt: thermal: TC improve periodic report""
- Revert "Revert "hw-mgmgt: thermal: TC add configurable offset for module tmin/tmax calculation""
- Revert "Revert "hw-mgmgt: thermal: Add PWM experimental PWM avarage info""
- Revert "Revert "TC Fix pwm max""
- Revert "Revert "hw-mgmgt: thermal: TC code and log messages beautify""
- Revert "Revert "Separate TC flavours which was approved for the new and old systems""
> V.7.0040.4000 BR sholeksandr5651

- usr/usr/bin/hw_management_sync.py
- usr/usr/bin/hw_management_thermal_control_2_5.py
TC add support module with TEC cooling.
> hw-mgmgt: thermal: TC add support module with TEC cooling

- usr/usr/bin/hw-management.sh
New SED PBA, versions 83.01.0008 and up, reports version through EFI variable.
If applicable hw-management reads this ERFI variable and report to NOS.
> hw-mgmt: scripts: Add attribute with SED PBA version.

- usr/etc/hw-management-thermal/tc_config_sn5640.json
- usr/usr/bin/hw-management-start-post.sh
> hw-mgmt: thermal: Update TC data for SN5640

- debian/changelog
> Update version V.7.0050.0933

- usr/etc/hw-management-thermal/tc_config_sn5640.json
- usr/usr/bin/hw-management-start-post.sh
This reverts commit a0a149597cba2356ce1191dc6ae0dcb4e3c08368.
> Revert "hw-mgmt: thermal: Update TC data for SN5640"

- debian/changelog
> Update version V.7.0040.4012

- usr/usr/bin/hw_management_thermal_control.py
- usr/usr/bin/hw_management_thermal_control_2_5.py
TC fix for asic sensor read error handling. PWM was not increased in
case asic temperature file read error.
Bug: 4458074
> hw-mgmt: thermal: TC fix for asic sensor read error handling

- usr/usr/bin/hw_management_thermal_control.py
- usr/usr/bin/hw_management_thermal_control_2_5.py
- hw-mgmgt: thermal: TC: Fix default input val smoothing level
- hw-mgmt: thermal: TC fix for asic sensor read error handling
> V.7.0040.4000 BR sholeksandr1295

- usr/usr/bin/hw_management_sync.py
Fix moduleX_temp_crit value. Was wrong sourse for moduleX_temp_crit
Wrong:
/sys/module/sx_core/asic0/moduleX/temperature/threshold_lo
Correct:
/sys/module/sx_core/asic0/moduleX/temperature/threshold_hi
Bug: 4452224
> hw-mgmgt: thermal: Fix module temp_crit.

- usr/usr/bin/hw_management_thermal_control.py
- usr/usr/bin/hw_management_thermal_control_2_5.py
- hw-mgmgt: thermal: TC: Fix default input val smoothing level
- hw-mgmt: thermal: TC fix for asic sensor read error handling
- hw-mgmgt: thermal: TC: Fix default input val smoothing level
> hw-mgmgt: thermal: TC: Fix default input val smoothing level

- usr/usr/bin/hw-management-generate-dump.sh
- usr/usr/bin/hw-management-helpers.sh
- usr/usr/bin/hw-management.sh
- hw-mgmgt: scripts: Add cpld registers dump on system start
- hw-mgmgt: scripts: Add cpld registers dump to cyclic rotating log file
> hw-mgmgt: scripts: Add cpld registers dump to cyclic rotating log file (2 commits)

- usr/usr/bin/hw_management_thermal_control_2_5.py
hw-management TermalControl searching user_config.json in default
folder: "/var/run/hw-management/config".
But if hw-mgmt will restart - user_config will be wiped together with
all other files in /var/run/hw-management/
This commit add second source folder for user config searching: /etc/hw-management-thermal.
TC will read user config from this folder if tc_config_user.json missing
in the default folder.
Motivation: default folder /var/run/hw-management/config is non-persistent
location and OS must monitor "hw-management.service" status and copy 
user config file from persistent location to non-persistent location
when "hw-management.service" restarts.
Part of
FR: 4403807
> hw-mgmt: thermal: TC add second source path for user config.

- usr/usr/bin/hw_management_sync.py
- Revert "hw-mgmt: thermal: Fix module temp_crit."
- hw-mgmt: thermal: Fix module temp_crit.
> hw-mgmt: thermal: Fix module temp_crit. (2 commits)

- debian/changelog
> Update version V.7.0050.0940

- usr/usr/bin/hw-management-vpd-parser.py
- usr/usr/bin/hw_management_dpu_thermal_update.py
- usr/usr/bin/hw_management_independent_mode_update.py
- usr/usr/bin/hw_management_parse_labels.py
- usr/usr/bin/hw_management_psu_fw_update_common.py
- usr/usr/bin/hw_management_psu_fw_update_delta.py
- usr/usr/bin/hw_management_psu_fw_update_murata.py
- usr/usr/bin/hw_management_redfish_client.py
- usr/usr/bin/hw_management_sync.py
- usr/usr/bin/hw_management_thermal_control.py
- usr/usr/bin/hw_management_thermal_control_2_5.py
- usr/usr/bin/sxd_read_cpld_ver.py
Cleanup and beautify *.py scripts
> hw-mgmt: scripts: Cleanup and beautify *.py scripts

- usr/usr/bin/hw_management_redfish_client.py
changed the open method to "with" and added an exception of no file or no permission for safer execution
> make platform file check safer

- usr/usr/bin/hw_management_thermal_control_2_5.py
hw-mgmt: scripts: Cleanup and beautify thermal_control v.2.5 script
> hw-mgmt: scripts: Cleanup and beautify thermal_control v.2.5 script

- unittest/hw_mgmt_thermal_control_2_5/Fan_thermal_insert_fault_test.txt
- usr/etc/hw-management-thermal/tc_config_sn5610.json
- usr/etc/hw-management-thermal/tc_config_sn5640.json
- usr/usr/bin/hw_management_thermal_control_2_5.py
- hw-mgmt: thermal: Add fan state validation after re-insertion
- hw-mgmt: thermal: TC add attention_fans config for SN5610/5640
> hw-mgmt: thermal: TC add attention_fans config for SN5610/5640 (2 commits)

- unittest/bom_decoder_cli.py
> Add helper for BOM string test

- usr/usr/bin/hw_management_thermal_control.py
Beautify thermal_control v.2.0 script
> hw-mgmt: scripts: Beautify thermal_control v.2.0 script

- debian/Release.txt
- debian/changelog
Update Release notes and changelog to V.7.0040.4021
> Update Release notes and changelog to V.7.0040.4021

- usr/usr/bin/hw_management_thermal_control.py
- usr/usr/bin/hw_management_thermal_control_2_5.py
TC improve logging system
1. Changed priorities for error/warning/notice messages
2. Improvement logging to syslog for critical messages
This feature is a part of improve robustness initiated after bugfix #4494119
FR: 4532813
> hw-mgmt: thermal: TC improve logging system

- unittest/hw_mgmgt_sync/module_populate/test_module_temp_populate_unit.py
- unittest/mock_hw_management_redfish_client.py
- usr/usr/bin/hw_management_sync.py
Bug: 4494119
Fix module_temp_populate function based on customer feedback Exception Handling Gaps - FIXED
Fix: Replaced bare except: statements with specific exception types (IOError, OSError, ValueError) and added detailed logging Module Counter Update Risk - CLARIFIED
Fix: Added clarifying comment to make the logic explicit and prevent future confusion Existing Symlink Bypass - DOCUMENTED
Fix: Added explanatory comment documenting why symlink validation was intentionally omitted Software Control Mode Skip Risk - DOCUMENTED
Fix: Added explanatory comment documenting the scope boundary File System Race Conditions - ANALYZED
Analysis: This script is the only one touching these files, so no race conditions exist Fix: Added explanatory comment and maintained direct file writes for …
> hw-mgmt: scripts: Fix customer comments on hw mgmt sync service

- debian/changelog
> Update version V.7.0050.1432

- usr/usr/bin/hw-management.sh
1. Search SED disk dynamically and not hardcoded NVMe.
So, the code will also work on a SATA SSD.
2. Make code more robust and effective.
Bug: 4598452
> hw-mgmt: scripts: improve sed_pba version report.

- unittest/hw_management_lib/HW_Mgmt_Logger/README.md
- unittest/hw_management_lib/HW_Mgmt_Logger/advanced_tests.py
- unittest/hw_management_lib/HW_Mgmt_Logger/run_tests.py
- unittest/hw_management_lib/HW_Mgmt_Logger/test_hw_mgmt_logger.py
- usr/usr/bin/hw-management-generate-dump.sh
- usr/usr/bin/hw_management_lib.py
- usr/usr/bin/hw_management_sync.py
Add logging functionality to sync service. It will print state/trace logs
to private log /var/log/hw_management_sync_log.
Log class implemented and added to dedicated hw_management_lib.py library.
This library can be shred between other hw-mgmt services/utils like TC.
Testing: added comprehensive test suite in unittest folder
unittest/hw_management_lib/HW_Mgmt_Logger
Bug: 4280981
> hw-mgmt: scripts: Add logging to sync service.

- unittest/hw_mgmgt_sync/asic_populate_temperature/README.md
- unittest/hw_mgmgt_sync/asic_populate_temperature/run_tests.sh
- unittest/hw_mgmgt_sync/asic_populate_temperature/test_asic_temp_populate.py
- usr/usr/bin/hw_management_lib.py
- usr/usr/bin/hw_management_sync.py
Add retry for fro ASIC temperature reading in sync script. It will
increase robustness in case of single error ASIC temperature/input
file reading.
Bug: 4280981 4625429
> hw-management: thermal: Add retry for fro ASIC temperature reading

- unittest/hw_management_lib/HW_Mgmt_Logger/README.md
- unittest/hw_management_lib/HW_Mgmt_Logger/advanced_tests.py
- unittest/hw_management_lib/HW_Mgmt_Logger/run_tests.py
- unittest/hw_management_lib/HW_Mgmt_Logger/test_hw_mgmt_logger.py
- unittest/hw_mgmgt_sync/asic_populate_temperature/README.md
- unittest/hw_mgmgt_sync/asic_populate_temperature/run_tests.sh
- unittest/hw_mgmgt_sync/asic_populate_temperature/test_asic_temp_populate.py
- usr/usr/bin/hw-management-generate-dump.sh
- usr/usr/bin/hw_management_lib.py
- usr/usr/bin/hw_management_sync.py
- **hw-mgmt: scripts: Add logging to sync service.**
- **hw-management: thermal: Add retry for fro ASIC temperature reading**
> hw-managment: thermal: Add retry for fro ASIC temperature reading (2 commits)
